import assert from "node:assert/strict";
import test from "node:test";
import { createAgentWorkflowCoverage, parseSkillReferenceSource } from "../scripts/agent-workflow-coverage.mjs";
const names = ["asgard-host-project","asgard-plugin-development","asgard-dotnet-10-csharp-14","asgard-api-development","asgard-backend-guard","asgard-configuration","asgard-host-features","asgard-database","asgard-security","asgard-identity-userinfo","identity-integration","asgard-auth-authorization","heimdall-service-integration","heimdall-application-rbac","heimdall-mcp-management"];
const skillsManifest = { schemaVersion: 1, source: { ref: "abc", releaseStatus: "audited-snapshot" }, skills: names.map((name) => ({ name })) };
const mappings = Object.fromEntries([["quick-start",["asgard-host-project","asgard-plugin-development","asgard-dotnet-10-csharp-14"]],["api-development",["asgard-api-development","asgard-dotnet-10-csharp-14","asgard-backend-guard"]],["configuration",["asgard-configuration","asgard-host-features"]],["database-operations",["asgard-database","asgard-backend-guard"]],["security-operations",["asgard-security","asgard-configuration"]],["heimdall-integration",["identity-integration","asgard-host-features","asgard-auth-authorization"]],["heimdall-quick-start",["identity-integration","asgard-configuration","asgard-host-features","asgard-security"]],["heimdall-deployment",["identity-integration","asgard-configuration","asgard-security"]],["heimdall-resource-server-revocation",["identity-integration","asgard-auth-authorization","heimdall-service-integration"]],["heimdall-management-api",["heimdall-application-rbac","asgard-api-development","asgard-auth-authorization"]],["heimdall-application-rbac",["heimdall-application-rbac","asgard-identity-userinfo","identity-integration","asgard-auth-authorization"]],["heimdall-mcp",["heimdall-mcp-management","identity-integration","asgard-auth-authorization","asgard-backend-guard"]]]);
function search(overrides={}) { return { schemaVersion:1, baseline:{reviewedAt:"2026-07-18"}, entries:Object.entries(mappings).flatMap(([slug,skills])=>["zh","en"].map(locale=>({id:`${locale}:${slug}`,kind:"doc",locale,product:slug.startsWith("heimdall")?"heimdall":"asgard",slug,path:`/${locale}/docs/${slug}`,skills:[...skills],...overrides[`${locale}:${slug}`]}))) }; }
test("reports bilingual canonical guide to audited Skill coverage",()=>{const r=createAgentWorkflowCoverage({searchData:search(),skillsManifest,declaredMappings:mappings});assert.equal(r.status,"coverage-contract-passed");assert.equal(r.summary.criticalRuleCount,12);assert.equal(r.policy.projectFileCoverageOutOfScope,true);});
test("fails closed on locale drift, unknown Skills, and orphan mappings",()=>{assert.throws(()=>createAgentWorkflowCoverage({searchData:search({"en:quick-start":{skills:["asgard-host-project"]}}),skillsManifest,declaredMappings:mappings}),/locale-drifted/);const m={...mappings,"quick-start":[...mappings["quick-start"],"unknown-skill"]};assert.throws(()=>createAgentWorkflowCoverage({searchData:search({"zh:quick-start":{skills:m["quick-start"]},"en:quick-start":{skills:m["quick-start"]}}),skillsManifest,declaredMappings:m}),/unknown Skill/);assert.throws(()=>createAgentWorkflowCoverage({searchData:search(),skillsManifest,declaredMappings:{...mappings,orphan:["asgard-security"]}}),/orphan/);});
test("parses the TypeScript mapping as a strict data contract",()=>assert.deepEqual(parseSkillReferenceSource('export const skillReferencesBySlug: Record<string, string[]> = {\n  overview: ["asgard-framework-overview"],\n  "quick-start": ["asgard-host-project"],\n};'),{overview:["asgard-framework-overview"],"quick-start":["asgard-host-project"]}));
