import type { DocPage, Locale } from "./content";

const packageReference = `<ItemGroup>
  <PackageReference Include="Asgard.Analyzers"
                    Version="5.1.3"
                    PrivateAssets="all"
                    IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
</ItemGroup>`;

const editorConfig = `root = true

[*.cs]
# Keep repository rules visible in local builds and CI.
dotnet_diagnostic.ASG0001.severity = error
dotnet_diagnostic.ASG0002.severity = error
dotnet_diagnostic.ASG0003.severity = error
dotnet_diagnostic.ASG0004.severity = error
dotnet_diagnostic.ASG0005.severity = error
dotnet_diagnostic.ASG0006.severity = error
dotnet_diagnostic.ASG0007.severity = error
dotnet_diagnostic.ASG0008.severity = error`;

const ciCommands = `dotnet restore --locked-mode
dotnet build -c Release --no-restore \
  -p:ContinuousIntegrationBuild=true \
  -p:RunAnalyzersDuringBuild=true

# Inspect the produced package when changing analyzer packaging.
dotnet pack Common/Asgard.Analyzers/Asgard.Analyzers.csproj \
  -c Release --no-restore`;

const sectionIds = [
  "contract",
  "installation",
  "diagnostics",
  "scope",
  "comments",
  "severity",
  "ci",
  "limitations",
  "agent-workflow",
  "acceptance",
  "sources",
] as const;

function makePage(locale: Locale): DocPage {
  const zh = locale === "zh";

  return {
    slug: "analyzers-operations",
    group: zh ? "工具链" : "Tooling",
    eyebrow: "ASGARD 5.1.3 · ROSLYN GUARDRAILS",
    title: zh ? "Analyzers 与 CI 代码守卫" : "Analyzers and CI code guardrails",
    description: zh
      ? "把 Asgard.Analyzers 作为编译期护栏接入项目，理解八条规则的真实边界，并用 Skills、评审与运行测试补齐证明链。"
      : "Wire Asgard.Analyzers into builds, understand the exact boundaries of its eight rules, and complete the evidence chain with Skills, review, and runtime tests.",
    sections: [
      {
        id: sectionIds[0],
        title: zh ? "先确认分析器的合同" : "Start with the analyzer contract",
        paragraphs: [
          zh
            ? "Asgard.Analyzers 是仅在编译期执行的 Roslyn 分析器包。5.1.3 源码公开 ASG0001–ASG0008，分类均为 Asgard、默认启用、默认严重级别均为 Error。包把程序集放入 analyzers/dotnet/cs，不向应用暴露普通运行时程序集。"
            : "Asgard.Analyzers is a build-time-only Roslyn analyzer package. The 5.1.3 source exposes ASG0001 through ASG0008; every diagnostic uses category Asgard, is enabled by default, and defaults to Error. The package places its assembly under analyzers/dotnet/cs rather than exposing a normal runtime library.",
          zh
            ? "它负责尽早发现一组确定的仓库约定，不负责证明 API 行为、授权表达式、租户隔离、事务边界、乐观锁或生产恢复正确。把分析器通过只不代表实现已经可上线。"
            : "It catches a specific set of repository conventions early. It does not prove API behavior, authorization expressions, tenant isolation, transaction boundaries, optimistic locking, or production recovery. A clean analyzer result is not release approval.",
        ],
      },
      {
        id: sectionIds[1],
        title: zh ? "以 Analyzer 资产安装，不产生运行时依赖" : "Install as analyzer assets without a runtime dependency",
        paragraphs: [
          zh
            ? "业务仓库通过 NuGet PackageReference 接入时建议保留 PrivateAssets=all，防止分析器被意外传播为下游依赖。IncludeAssets 显式包含 analyzers，便于集中依赖管理工具重写引用时仍保留编译期资产。"
            : "When consuming the NuGet package, keep PrivateAssets=all so the analyzer does not accidentally flow as a downstream dependency. Explicitly retaining analyzers in IncludeAssets also protects the build-time asset when dependency-management tooling rewrites references.",
          zh
            ? "Asgard 主仓库不是用 NuGet 自举：Directory.Build.props 在 EnableAsgardRepositoryAnalyzers=true 时，以 OutputItemType=Analyzer、ReferenceOutputAssembly=false 的 ProjectReference 接入，并排除 Asgard.Analyzers 自身。外部仓库不应复制这个源码相对路径。"
            : "The Asgard repository does not bootstrap from its own NuGet package. Directory.Build.props uses a ProjectReference with OutputItemType=Analyzer and ReferenceOutputAssembly=false when EnableAsgardRepositoryAnalyzers=true, excluding the analyzer project itself. External repositories should not copy that source-relative reference.",
        ],
        code: { language: "xml", value: packageReference },
      },
      {
        id: sectionIds[2],
        title: zh ? "八条当前规则" : "The eight current diagnostics",
        bullets: zh
          ? [
              "ASG0001：禁止普通 using 指令；global using 不报错，建议集中到 GlobalUsings.cs",
              "ASG0002：文件名不能包含 { 或 }，阻止 {T} 一类占位符命名",
              "ASG0003：含拉丁字母且没有中文字符的注释报错；纯符号、空注释和 <auto-generated 开头内容跳过",
              "ASG0004：显式 throw new ArgumentNullException 的语句和 throw 表达式报错，要求 ThrowIfNull",
              "ASG0005：单个语法树根节点最多一个顶层 class/struct/interface/enum/record/delegate",
              "ASG0006：非 Test/Tests 路径中，顶层类型声明的前导注释覆盖率必须至少 80%",
              "ASG0007：单个 .cs 语法树物理行数最多 400 行",
              "ASG0008：直接丢弃非 void 调用、对象创建或带结果 await 时，要求显式 _ =；无结果 Task/ValueTask await 例外",
            ]
          : [
              "ASG0001: rejects non-global using directives; global using is accepted and normally centralized in GlobalUsings.cs",
              "ASG0002: rejects { or } in a file name, preventing placeholder names such as {T}",
              "ASG0003: rejects comments containing Latin letters but no Chinese character; empty, symbol-only, and <auto-generated-prefixed content is skipped",
              "ASG0004: rejects explicit throw new ArgumentNullException statements and throw expressions in favor of ThrowIfNull",
              "ASG0005: permits at most one root-level class, struct, interface, enum, record, or delegate per syntax tree",
              "ASG0006: outside Test/Tests paths, at least 80% of root-level type declarations must have leading comments",
              "ASG0007: limits a .cs syntax tree to 400 physical lines",
              "ASG0008: requires explicit _ = when discarding a non-void invocation, object creation, or result-bearing await; awaiting non-generic Task/ValueTask is exempt",
            ],
      },
      {
        id: sectionIds[3],
        title: zh ? "理解跳过范围与语法边界" : "Understand skip paths and syntax boundaries",
        paragraphs: [
          zh
            ? "分析器调用 ConfigureGeneratedCodeAnalysis(None)，并按 Windows 路径跳过 obj、bin、.codex-build 与 Asgard.Analyzers 目录；没有文件路径的语法树也跳过。ASG0006 额外跳过路径中的 Test 与 Tests，但其他规则不会因为它是测试文件而自动跳过。"
            : "The analyzer calls ConfigureGeneratedCodeAnalysis(None) and also skips Windows paths containing obj, bin, .codex-build, or Asgard.Analyzers; syntax trees without a file path are skipped. ASG0006 additionally skips paths containing Test or Tests, but the other diagnostics are not automatically disabled for test files.",
          zh
            ? "ASG0005 和 ASG0006 只统计语法树根节点的类型声明。文件作用域 namespace 下的类型不是 root.ChildNodes() 里的类型，因此当前实现可能不计入这两条规则。CI 规则要以真实诊断为准，不能把 README 的概括当成更宽的实现。"
            : "ASG0005 and ASG0006 count type declarations only among the syntax-tree root children. A type under a file-scoped namespace is not itself a root child, so the current implementation may not include it in those two checks. CI expectations must follow observed diagnostics, not a broader README summary.",
        ],
      },
      {
        id: sectionIds[4],
        title: zh ? "注释规则不是文档质量评分器" : "Comment rules are not a documentation quality score",
        paragraphs: [
          zh
            ? "ASG0003 会去掉注释符号、星号和 XML 标签，再对包含拉丁字母的文本检查是否至少存在一个中文字符。它没有判断语义质量，也不会要求纯中文之外的文本必须出现。一个中文字符可以让中英混合注释通过。"
            : "ASG0003 removes comment markers, asterisks, and XML tags, then checks text containing Latin letters for at least one Chinese character. It does not assess semantic quality and does not require text that contains no Latin letters to appear at all. A single Chinese character can allow a mixed-language comment through.",
          zh
            ? "ASG0006 只判断顶层声明的 leading trivia 是否有非空注释，并按声明数量计算覆盖率。公开 API 的 summary、param、returns 完整性仍由编译器警告、API 评审与文档构建验证。"
            : "ASG0006 only checks whether root-level declarations have non-empty comment trivia and computes a declaration count ratio. Completeness of summary, param, and returns for public APIs still belongs to compiler warnings, API review, and documentation-build validation.",
        ],
      },
      {
        id: sectionIds[5],
        title: zh ? "严重级别属于消费仓库的策略" : "Severity is a consuming-repository policy",
        paragraphs: [
          zh
            ? "包内八条规则默认就是 Error；.editorconfig 可以显式固定策略，或在有证据的迁移窗口内按 ID 调整。不要全局关闭分析器，也不要用 NoWarn 隐藏未知问题。任何例外都应记录负责人、范围、原因和删除日期。"
            : "All eight package diagnostics already default to Error. An .editorconfig can make that policy explicit or adjust a specific ID during an evidence-backed migration window. Do not disable analyzers globally or hide unknown issues with a blanket NoWarn. Every exception needs an owner, scope, reason, and removal date.",
          zh
            ? "当前源码没有 CodeFixProvider，IDE 只能定位和解释诊断，不能承诺一键修复。批量整改前先在小范围验证机械重写不会改变作用域、异步语义或 API 表面。"
            : "The current source contains no CodeFixProvider. The IDE can locate and explain diagnostics, but there is no promised one-click fix. Validate any mechanical rewrite on a small scope before applying it broadly so scope, async semantics, and API surface are preserved.",
        ],
        code: { language: "ini", value: editorConfig },
      },
      {
        id: sectionIds[6],
        title: zh ? "让 CI 运行同一套证据" : "Run the same evidence in CI",
        paragraphs: [
          zh
            ? "CI 至少应锁定还原、Release 构建并显式开启构建期分析器。Asgard 主仓库还通过 Directory.Build.props 对核心项目开启 EnforceCodeStyleInBuild、RunAnalyzersDuringBuild，并把 CS1591 提升为错误；这些是仓库策略，不是 Asgard.Analyzers 包自动提供的规则。"
            : "CI should at minimum use locked restore, a Release build, and explicitly enable build-time analyzers. The Asgard repository additionally enables EnforceCodeStyleInBuild and RunAnalyzersDuringBuild for core projects and promotes CS1591 to an error through Directory.Build.props. Those are repository policies, not diagnostics automatically supplied by the package.",
          zh
            ? "修改分析器本身时还要 pack 并检查 nupkg 中的 analyzers/dotnet/cs 资产。当前源码树没有独立的 Asgard.Analyzers.Tests 项目，因此新增或改变规则前应补 Roslyn 测试矩阵，覆盖正例、反例、生成代码、测试路径、文件作用域 namespace 与不同返回类型。"
            : "When changing the analyzer itself, also pack it and inspect the analyzers/dotnet/cs assets in the nupkg. The current source tree has no dedicated Asgard.Analyzers.Tests project, so rule additions or changes should add a Roslyn test matrix for positive and negative cases, generated code, test paths, file-scoped namespaces, and return-type variants.",
        ],
        code: { language: "bash", value: ciCommands },
      },
      {
        id: sectionIds[7],
        title: zh ? "通过分析器之后仍要证明什么" : "What remains unproven after a clean build",
        bullets: zh
          ? [
              "Controller 路由、Response 包装、DTO 映射与错误语义需要 API 契约测试",
              "tenant_id 过滤、跨租户拒绝与审计字段需要数据库集成测试",
              "AsgardAuth 表达式、token_type、角色/权限/scope 组合需要授权矩阵测试",
              "版本列、受影响行数和冲突响应需要并发测试，分析器不验证乐观锁",
              "缓存降级、消息重试、作业重放、关闭恢复需要故障注入和运行证据",
              "安全密钥、敏感配置与日志脱敏需要配置审计和威胁建模",
            ]
          : [
              "Controller routes, Response envelopes, DTO mapping, and error semantics need API contract tests",
              "tenant_id filters, cross-tenant rejection, and audit fields need database integration tests",
              "AsgardAuth expressions and token_type/role/permission/scope combinations need an authorization matrix",
              "Version columns, affected-row checks, and conflict responses need concurrency tests; the analyzer does not validate optimistic locking",
              "Cache degradation, message retries, job replay, and shutdown recovery need fault injection and runtime evidence",
              "Security keys, sensitive configuration, and log redaction need configuration review and threat modeling",
            ],
      },
      {
        id: sectionIds[8],
        title: zh ? "AI Ready：让 Skill、源码与诊断闭环" : "AI Ready: close the loop across Skills, source, and diagnostics",
        paragraphs: [
          zh
            ? "让 agent 先加载 asgard-dotnet-10-csharp-14 作为强制编码规则，再用 asgard-backend-guard 检查 Controller、Service、Repository、Entity、租户与并发边界。分析器输出是可机器验证的反馈，但每项判断仍要引用当前源码、配置与测试证据。"
            : "Have an agent load asgard-dotnet-10-csharp-14 as the mandatory coding authority, then use asgard-backend-guard for Controller, Service, Repository, Entity, tenant, and concurrency boundaries. Analyzer output is machine-verifiable feedback, but every conclusion still needs current source, configuration, and test evidence.",
          zh
            ? "推荐循环是：读取相关 Skill → 定位源码合同 → 小步修改 → 运行定向测试与分析器 → 用后端守卫复查 → 运行完整 CI。不要让 AI 只为消除诊断而删除注释、吞掉返回值、关闭规则或改变公开行为。"
            : "Use this loop: read the relevant Skill, locate the source contract, make a small change, run targeted tests and analyzers, review with the backend guard, then run full CI. Never let an agent silence diagnostics by deleting documentation, swallowing results, disabling rules, or changing public behavior.",
        ],
      },
      {
        id: sectionIds[9],
        title: zh ? "接入验收清单" : "Adoption acceptance checklist",
        bullets: zh
          ? [
              "在一个故意违反 ASG0001–ASG0008 的样例项目中证明八条诊断都会让 Release 构建失败",
              "证明发布产物没有 Asgard.Analyzers 运行时程序集依赖，nupkg 的分析器资产位于 analyzers/dotnet/cs",
              "验证生成代码、obj/bin 与 Test/Tests 路径的真实跳过行为，并把差异写进团队约定",
              "为每个临时 severity 例外建立负责人和到期日，CI 禁止无范围的 NoWarn",
              "在分析器之后继续运行 API、授权、租户、数据库并发和故障恢复测试",
              "升级包版本时比较 SupportedDiagnostics 与实现范围，而不是只读 README 或版本号",
            ]
          : [
              "Use a fixture that intentionally violates ASG0001–ASG0008 and prove every diagnostic fails a Release build",
              "Prove the application has no runtime dependency on Asgard.Analyzers and the nupkg places analyzer assets under analyzers/dotnet/cs",
              "Verify real skip behavior for generated code, obj/bin, and Test/Tests paths, documenting any difference in team policy",
              "Give every temporary severity exception an owner and expiry; reject unscoped NoWarn in CI",
              "Continue with API, authorization, tenant, database-concurrency, and failure-recovery tests after analyzer success",
              "On package upgrades, compare SupportedDiagnostics and implementation scope rather than reading only the README or version number",
            ],
      },
      {
        id: sectionIds[10],
        title: zh ? "源码核验入口" : "Source verification anchors",
        paragraphs: [
          zh
            ? "规则元数据在 Common/Asgard.Analyzers/AsgardDiagnosticDescriptors.cs；注册、跳过逻辑和实际判定在 AsgardCodeStyleAnalyzer.cs 与 CommentAnalysisHelper.cs；打包合同在 Asgard.Analyzers.csproj；主仓库接入与 CI 策略在 Directory.Build.props。"
            : "Rule metadata lives in Common/Asgard.Analyzers/AsgardDiagnosticDescriptors.cs. Registration, skip behavior, and actual checks live in AsgardCodeStyleAnalyzer.cs and CommentAnalysisHelper.cs. Packaging is defined in Asgard.Analyzers.csproj, while repository wiring and CI policy live in Directory.Build.props.",
          zh
            ? "本页按 5.1.3 源码描述当前行为。升级后重新核对 SupportedDiagnostics、Initialize、每条 Report 方法、项目引用条件与包内容，再更新文档。"
            : "This page describes the 5.1.3 source contract. After an upgrade, re-check SupportedDiagnostics, Initialize, every Report method, project-reference conditions, and package contents before updating the documentation.",
        ],
      },
    ],
    relatedDocs: [
      { product: "asgard", docSlug: "analyzers", label: zh ? "分析器概览" : "Analyzer overview" },
      { product: "asgard", docSlug: "typescript-generation", label: zh ? "TypeScript 生成" : "TypeScript generation" },
      { product: "asgard", docSlug: "api-development", label: zh ? "API 开发" : "API development" },
      { product: "asgard", docSlug: "authorization", label: zh ? "授权" : "Authorization" },
    ],
  };
}

export const zhAsgardAnalyzersOperationsDocs: DocPage[] = [makePage("zh")];
export const enAsgardAnalyzersOperationsDocs: DocPage[] = [makePage("en")];
