import type { DocPage } from "./content";

const miniIssuerInstallCode = `dotnet add package Asgard.Heimdall.JwtSigning --version 5.3.19
dotnet add package Asgard.Heimdall.JwtSigning.AspNetCore --version 5.3.19`;

const miniIssuerSetupCode = `builder.Services.AddAsgardHeimdallJwtSigning(options =>
{
    options.Issuer = "https://auth.example.com/7c80e227-ec0d-40bf-9909-e6f8e75ba6bf";
    options.Audience = "scm-api";
    options.DiscoveryPathPrefix = "/7c80e227-ec0d-40bf-9909-e6f8e75ba6bf";
    options.KeyId = "scm-main";
    options.RsaPrivateKeyPem = privateKeyPem;
    options.AccessTokenLifetime = TimeSpan.FromHours(1);
});

app.MapAsgardHeimdallJwtSigningDiscovery();`;

const miniIssuerUserTokenCode = `var token = issuer.Issue(new AsgardJwtSubject
{
    Subject = user.Id,
    UserId = user.Id,
    TenantId = "7c80e227-ec0d-40bf-9909-e6f8e75ba6bf",
    Roles = ["scm-user"],
    Permissions = ["scm.api"],
    Scope = ["api"],
    Name = user.DisplayName,
    AuthenticationTime = DateTimeOffset.UtcNow
});`;

const miniIssuerServiceTokenCode = `var token = issuer.Issue(new AsgardJwtSubject
{
    Subject = "orders-worker",
    ClientId = "orders-worker",
    TokenType = AsgardJwtConstants.BackendServiceTokenType,
    Scope = ["jobs.execute"]
});

[AsgardAuthMatch("token_type = 'BackendService' and scope = 'jobs.execute'")]`;

const miniIssuerResourceCode = `host:
  auth:
    enabled: true
    jwt:
      issuerTemplate: "https://auth.example.com/{tenant}/"
      audience: "scm-api"
      requireHttpsMetadata: true
      discoveryCacheMinutes: 60
      jwksCacheMinutes: 60`;

const mcpCredentialCode = `POST /api/mcp-credentials
Authorization: Bearer <user-access-token>
Content-Type: application/json

{ "name": "production-agent" }

// SecretKey is returned only by create or reset-secret.
{
  "data": {
    "name": "production-agent",
    "accessKey": "hmcp_t_...",
    "secretKey": "...",
    "enabled": true
  }
}`;

const mcpRequestCode = `POST /mcp HTTP/1.1
Host: id.example.com
Authorization: Basic <base64(AK:SK)>
Content-Type: application/json
Accept: application/json, text/event-stream

// Alternative headers:
// X-Heimdall-Access-Key: <AK>
// X-Heimdall-Secret-Key: <SK>`;

const identityWebhookConfigCode = `identity_webhook:
  poll_interval_seconds: 5
  request_timeout_seconds: 10
  batch_size: 20
  max_attempts: 8
  base_retry_seconds: 5
  max_retry_seconds: 3600
  allow_localhost_http: false`;

const identityWebhookRoutesCode = `GET    /api/IdentityWebhook/tenant/{tenantId}/subscriptions
POST   /api/IdentityWebhook/tenant/{tenantId}/subscriptions
PUT    /api/IdentityWebhook/tenant/{tenantId}/subscriptions/{id}
DELETE /api/IdentityWebhook/tenant/{tenantId}/subscriptions/{id}
POST   /api/IdentityWebhook/tenant/{tenantId}/subscriptions/{id}/rotate-secret
GET    /api/IdentityWebhook/tenant/{tenantId}/deliveries
POST   /api/IdentityWebhook/tenant/{tenantId}/deliveries/{id}/retry

Required permission (any):
platform.admin | platform.security.manage`;

const identityWebhookEventCode = `{
  "event_id": "<guid>",
  "event_type": "identity.subject.invalidated",
  "schema_version": 1,
  "occurred_at": "<utc timestamp>",
  "tenant_id": "<tenant id>",
  "subject_id": "<subject id>",
  "revoked_at": "<utc timestamp>",
  "reason": "disabled | deleted | admin_revoke",
  "operator_id": "<operator id>"
}`;

const identityWebhookSignatureCode = `X-Heimdall-Event-Id: <event_id>
X-Heimdall-Timestamp: <unix-seconds>
X-Heimdall-Key-Id: <key_id>
X-Heimdall-Signature: sha256=<lowercase-hex>

signed_bytes = UTF8(timestamp + "." + raw_request_body)
expected = HMACSHA256(Base64Decode(secret), signed_bytes)`;

const federationFlowCode = `Tenant provider configuration
  → validate upstream metadata / connection / certificate
  → enable provider
  → /external-login/{oidc|ldap|saml}/...
  → resolve or JIT-provision a local tenant user
  → synchronize explicitly mapped external groups
  → optional Heimdall MFA challenge
  → local login cookie → original OIDC authorization flow`;

const mfaRoutesCode = `POST /api/account/login
  → { mfaRequired, mfaToken, expiresIn }
POST /api/account/login/mfa
  → { mfaToken, code }

GET  /api/account/me/totp
POST /api/account/me/totp/provision
POST /api/account/me/totp/confirm
POST /api/account/me/totp/disable

GET  /api/account/me/mfa/recovery-codes
POST /api/account/me/mfa/recovery-codes/rotate`;

const scimSetupCode = `POST /api/TenantScim/tenant/{tenantId}/token/rotate
Authorization: Bearer <admin-access-token>

POST /api/TenantScim/tenant/{tenantId}/status
Authorization: Bearer <admin-access-token>
Content-Type: application/json

{ "enabled": true }`;

const scimRequestCode = `GET /scim/v2/{tenantId}/Users?startIndex=1&count=100 HTTP/1.1
Host: id.example.com
Authorization: Bearer hscim_...
Accept: application/scim+json

GET /scim/v2/{tenantId}/Users?filter=userName%20eq%20%22alice%22
GET /scim/v2/{tenantId}/Groups?filter=externalId%20eq%20%22group-42%22`;

const siemRequestCode = `GET /api/security-events/export?format=ndjson&limit=500&cursor=...
Authorization: Bearer <access-token>

X-Heimdall-Event-Count: 500
X-Heimdall-Has-More: true
X-Heimdall-Next-Cursor: <opaque-cursor>`;

const siemLoopCode = `cursor = loadCheckpoint()

while true:
  batch = GET export(cursor)
  persistEveryEventToSiem(batch.body)
  commitSiemTransaction()
  saveCheckpoint(batch.nextCursor)
  if not batch.hasMore: break`;

export const zhHeimdallAdvancedDocs: DocPage[] = [
  {
    slug: "heimdall-jwt-signing",
    group: "生态",
    eyebrow: "MINI JWT ISSUER · 5.3.19",
    title: "轻量 JWT 签发与 Asgard API 对接",
    description: "不部署完整 Heimdall IDP，也能签发符合 Asgard Claims 契约的用户与后端服务 Access Token，并自动暴露 Discovery/JWKS。",
    sections: [
      { id: "product-and-version-boundary", title: "产品与版本边界", paragraphs: ["mini issuer 是两个 NuGet 包，不等同于完整 Heimdall Server。两个项目已移除旧 0.2.0 项目级版本覆盖，当前 v5.3.19 / 0032070 统一从 Directory.Build.props 生成 5.3.19 包。", "它只在业务完成身份验证后签发 Asgard Access Token，并提供最小 Discovery/JWKS。浏览器 Authorization Code + PKCE、Refresh Token、同意、SSO、撤销和会话治理应使用完整 Heimdall。"], bullets: ["Asgard.Heimdall.JwtSigning：签发、Claims 与 RSA JWKS", "Asgard.Heimdall.JwtSigning.AspNetCore：DI、启动验证和端点映射", "资源 API 不引用签发包，只配置 Asgard host.auth.jwt"] },
      { id: "packages-and-installation", title: "安装、启动验证与 Secret", paragraphs: ["两个包均固定 5.3.19。注册阶段会验证 Issuer、Audience、KeyId、静态绝对 DiscoveryPathPrefix、1 秒到 int.MaxValue 秒的 Token 生命周期，以及密钥/算法组合；必须且只能提供 RSA 私钥或对称密钥之一。签发器以 Singleton 注册并固定配置和密钥。"], code: { language: "shell", value: miniIssuerInstallCode }, note: "私钥必须由 Secret Manager 或受控文件注入；不要写入 appsettings、源码、日志、镜像层或 Agent 提示词。" },
      { id: "rsa-only-public-discovery", title: "公开 Discovery/JWKS 强制 RSA", paragraphs: ["5.3.19 已关闭旧版对称 JWKS 泄密路径：对称模式可以在核心包内签发，但 CreateJwksDocument 会拒绝，MapAsgardHeimdallJwtSigningDiscovery() 也会抛出异常。", "公开 Discovery/JWKS 必须使用至少 2048 位且公私钥匹配的 RSA；只允许 RS256/384/512 或 PS256/384/512。对称模式仅允许 HS256/384/512，并分别要求至少 32/48/64 字节密钥，通过独立安全通道向验证方分发。"], bullets: ["上线门禁：JWKS 不得出现 k、d、p、q、dp、dq 或 qi", "KeyId 必须与 Token header kid 及 JWKS kid 一致", "Discovery 不再宣称 id_token_signing_alg_values_supported；mini issuer 只签发 Access Token"] },
      { id: "issuer-and-endpoints", title: "Issuer、路径与端点契约", paragraphs: ["使用官方扩展注册 IAsgardJwtIssuer 并映射端点。DiscoveryPathPrefix 决定实际路由；默认 jwks_uri 却由 Issuer + /.well-known/jwks.json 派生，并不会自动拼接 DiscoveryPathPrefix。Issuer 自带同一路径段时二者才自然一致，否则必须显式设置 JwksUriOverride 并从公网真实 GET 验证。", "返回的文档只有 issuer、jwks_uri、claims_supported、签名算法、public subject type 和空 response_types；它不是完整 OIDC Provider，不应被宣传为可执行 authorize/token 流程。"], code: { language: "csharp", value: miniIssuerSetupCode } },
      { id: "issue-user-and-service", title: "签发用户与后端服务 Token", paragraphs: ["业务必须先验证密码、OTP 或外部身份，再注入 IAsgardJwtIssuer 调用 Issue。Subject 必填；默认 Lifetime 为一小时，token_type=UserLogin，Roles、Permissions、Scope 自动序列化为 JSON 数组，Metadata 为 JSON 对象。"], code: { language: "csharp", value: miniIssuerUserTokenCode }, bullets: ["BackendService 必须提供 Subject、ClientId 和 BackendService token_type，且禁止 UserId", "AsgardJwtIssueOptions 可单次覆盖 Audience、Lifetime、IssuedAt 与 Jti", "Issuer 不提供 Refresh Token、撤销、黑名单、Introspection 或账号状态复查"], note: miniIssuerServiceTokenCode },
      { id: "asgard-resource-integration", title: "对接 Asgard 5.1.3 资源 API", paragraphs: ["Asgard 5.1.3 内置 host.auth 要求 issuerTemplate 恰好包含一个 {tenant}，并把替换后的 Issuer、Discovery issuer 与 Token iss 精确对齐；配置的单个 audience 必须精确匹配 Token 的一个 aud。示例把同一 GUID 同时用于 Issuer 路径、DiscoveryPathPrefix 和 tenant_id。"], code: { language: "yaml", value: miniIssuerResourceCode }, bullets: ["生产保持 requireHttpsMetadata=true", "资源服务通过 Discovery/JWKS 验签，不读取 RSA 私钥", "401 检查路由、issuer、jwks_uri、kid、aud、过期和时钟；403 检查 token_type、roles、permissions、scope 与 tenant_id"] },
      { id: "key-lifecycle-and-rotation", title: "密钥生命周期与轮换", paragraphs: ["5.3.19 的 Singleton 仍只持有一个活动 Key，RSA JWKS 也只发布该 Key；没有配置热重载、多 Key overlap、active/retiring 状态、KMS/HSM Provider 或托管轮换。直接替换 Key 并重启会让旧 Token 在资源端刷新 JWKS 后失去验证材料。"], bullets: ["优先把 Access Token Lifetime 缩到可接受的最短窗口", "轮换前发布新旧双 Key overlap 需要外部扩展或后续正式能力；当前单实例做不到", "没有 overlap 时安排维护窗口，协调全部副本、JWKS 缓存和旧 Token 生命周期，并验证回滚", "不要用相同 KeyId 复用不同密钥材料"] },
      { id: "revocation-and-security-operations", title: "撤销与端点安全运维", paragraphs: ["mini issuer 不保存 Token、会话或主体状态，也没有 revoke/introspection；一个已签发 Token 在过期前不会因用户被禁用而由该包自动失效。需要即时撤销时，选择完整 Heimdall 或设计已发布且验收过的 deny-list/introspection/invalidation。", "Discovery/JWKS 端点本身没有包级认证、Cache-Control、限流、健康检查或审计策略。由反向代理和宿主补齐 HTTPS、可信 Host/Forwarded Headers、合理缓存、限流、可用性监控与响应大小限制；禁止缓存私钥或 Token。"], bullets: ["监控 Discovery/JWKS 的 HTTPS 状态、MIME、issuer、jwks_uri、kid 和响应延迟", "多副本必须发布完全相同的 Issuer、KeyId 和公钥", "日志只记录 jti/kid/失败分类等非 Secret 元数据，不记录完整 Token"] },
      { id: "production-acceptance", title: "生产验收清单", bullets: ["空 Issuer/Audience/KeyId、非法前缀和无 Key 时启动必须失败", "从公网 GET Discovery 与 jwks_uri；二者可达且 issuer 精确一致", "JWKS 只含 RSA 公钥，不含 k 或任何私钥参数；Token kid 可命中唯一 Key", "用户与 BackendService Claims、默认一小时及单次覆盖均通过测试", "Asgard 对错 tenant、错 issuer、错 audience、错 kid、过期 Token 返回 401，对权限不足返回 403", "多副本轮询结果一致；重启不意外生成新 Key", "演练轮换、缓存刷新、旧 Token 行为和回滚，并记录实际不可用窗口"] },
      { id: "release-boundaries", title: "Release 与未证明边界", paragraphs: ["Release：v5.3.19 / 0032070 提供 5.3.19 包、应用域授权 Claims、严格密钥/算法/生命周期/路径验证、RSA-only 公共 Discovery/JWKS、单 Key JWT 签发，以及用户与 BackendService Token；HEAD 与 tag 相同。", "未证明/不提供：完整 OIDC Provider、Refresh Token、撤销/Introspection、密钥热重载、多 Key overlap、自动轮换、KMS/HSM、端点缓存与限流策略、动态多租户 Issuer，以及生产多副本或轮换端到端证明。" ] },
    ],
  },
  {
    slug: "heimdall-mcp",
    group: "生态",
    eyebrow: "HEIMDALL 5.3.19 · GOVERNED MCP",
    title: "Heimdall MCP 接入",
    description: "使用 v5.3.19 的有状态 Streamable HTTP 管理面，正确接入 OAuth/AK-SK、策略、二阶段写入与审计。",
    sections: [
      { id: "status", title: "v5.3.19 Release 合同", paragraphs: ["v5.3.19 / 0032070 在 /mcp 发布有状态 Streamable HTTP 管理面。5.3.0 首次完整交付平台/租户管理 Tools、5 个 Resources、6 个 Prompts、有界 Tasks、OAuth 与 AK/SK、凭据策略、二阶段确认和安全事件审计；后续 5.3.x 补齐 Application/OIDC Client 工具与前端工作区。", "客户端必须通过 tools/list、resources/list、prompts/list 动态发现；工具名使用稳定 platform_、tenant_、heimdall_ 前缀。不要把静态文档清单当运行时权威。"] },
      { id: "model", title: "身份、Application 与端点边界", paragraphs: ["OAuth 客户端先读取 /.well-known/oauth-protected-resource/mcp，再携带 Heimdall Access Token；端点级策略要求 Token 由内建 Heimdall 管理 Application 签发，并覆盖 Tools、Resources、Prompts 与 Tasks。", "AK/SK 使用 hmcp_p_ 或 hmcp_t_ 前缀；租户身份由服务端凭据记录确定，工具不能接收可切换 tenantId。认证会重建实时账号、Application、角色和权限边界；AllowedPermissions 只能与实时权限取交集，不能扩权。"], code: { language: "http", value: mcpRequestCode } },
      { id: "create", title: "凭据策略与一次性 Secret", paragraphs: ["token_type=UserLogin 的当前账号通过 /api/mcp-credentials 管理自己的凭据。创建/重置只返回一次 SK；数据库保存哈希。策略包含 allowedTools、allowedPermissions、allowedCidrs、expiresAt、environment、rateLimitPerMinute 与 maxConcurrentCalls。", "空工具或权限列表表示“不额外收窄”，不是拒绝全部。受限凭据委派另一凭据时，新工具/权限必须是调用方边界的子集；调用方已有白名单时，不得用空列表绕过该限制。"], code: { language: "http", value: mcpCredentialCode }, bullets: ["GET /api/mcp-credentials/catalog：动态工具与权限目录", "PUT /api/mcp-credentials/{id}/policy：更新策略", "POST /api/mcp-credentials/{id}/reset-secret：轮换 SK", "PUT /api/mcp-credentials/{id}/status 与 DELETE：失效凭据"] },
      { id: "safe-writes", title: "所有写工具都要两阶段确认", paragraphs: ["每个非只读工具第一次调用不带 confirmationToken，只返回影响预览与短期令牌；人工或 Agent 审阅后，以完全相同载荷和令牌再次调用才执行。", "令牌绑定 CredentialId、ToolName 与规范化载荷哈希，单次使用。改参数、换凭据、换工具或重放都必须失败；MCP 工具仍调用既有 Service 与资源 AccessGuard，不能直接写 Repository/Entity。"], bullets: ["分页统一返回 McpPageResult<T>", "写入统一返回 McpMutationResult<T>", "高影响动作标记 Destructive；创建、轮换、重投按真实语义标记非幂等", "按 ID 写入前读取资源并校验 Application/Tenant 归属"] },
      { id: "tools", title: "管理能力与权限", bullets: ["平台域：Tenant/Onboarding、SystemUser、Application/Manifest/Grant、平台 RBAC、运行时/安全/对象存储、日志/Trace、安全事件/SIEM/TOTP", "租户域：用户/目录、Application RBAC、OIDC Client/Scope/Key、联合身份、会话/授权、黑名单、SCIM、Webhook 与 TOTP", "MCP 治理：凭据 Catalog/Lifecycle、Policy、审计、确认、限流/并发、Resources、Prompts 与 Tasks", "5.3.8 新增平台 Application/OIDC Client 工具；显式 allowedTools 的旧凭据不会自动获得新增工具，必须审核后加入"] },
      { id: "tasks-and-audit", title: "Tasks、审计与多副本", paragraphs: ["协议 Tasks 具有 TTL、全局/会话容量和最短轮询限制；当前生产假设单 Heimdall 应用容器并使用内存 Store。横向扩容前必须替换共享持久化 Store，验证恢复、配额与并发。", "每次工具调用成功或失败都写 mcp.tool.invoked 安全事件，记录工具、凭据、环境、结果、耗时和错误类型，不含 SK、Client Secret、Webhook Secret、私钥或完整敏感请求头。"] },
      { id: "migration-and-acceptance", title: "迁移与发布验收", paragraphs: ["auto_sync_schema=false 时，除旧 20260715_mcp_credentials 外，还要在应用更新前执行 20260720_mcp_credential_policy.postgresql.sql；前者建立 credential_name 等凭据列，后者将平台/租户凭据的策略扩展列扩大到 varchar(8192)。", "上线必须覆盖 OAuth metadata、内建 Application Token 与外部 Application Token 拒绝、AK/SK 停用/过期/CIDR/速率/并发、平台/租户目录隔离、委派子集、每个写工具确认令牌，以及 tools/resources/prompts/tasks 的共同端点保护。"] },
    ],
  },
  {
    slug: "heimdall-identity-webhooks",
    group: "生态",
    eyebrow: "HEIMDALL 5.3.19 · IDENTITY WEBHOOK",
    title: "身份失效 Webhook",
    description: "在主体禁用、删除或管理员撤销时可靠撤销本地身份，并向可信下游发送签名事件。",
    sections: [
      { id: "status", title: "Heimdall 5.3.19 已发布合同", paragraphs: ["Identity Webhook 最初在 5.1.2 发布；当前 clean tag v5.3.19 / commit 0032070 仍包含 Controller、Outbox、Worker、HMAC、重试、PostgreSQL 增量、JSON Schema 与管理前端。HTTP 合同固定为 event_type=identity.subject.invalidated、version=1，reason 仅允许 disabled、deleted 或 revoked。", "发布制品存在不等于下游已经完成接入；必须以真实 Tenant Client、Webhook Secret、签名、防重放、幂等、撤销水位和旧 JWT 拒绝做端到端验收。"] },
      { id: "flow", title: "身份失效与 Outbox", paragraphs: ["租户用户从 Enabled 变为禁用、被单个/批量删除，或执行管理员主体撤销时，Heimdall 在同一数据库事务内写主体会话撤销，撤销 Access/Refresh Token、授权、授权码、设备码、Consent 与活动会话，并创建 identity.subject.invalidated v1 Outbox。平台用户不在 Webhook 范围内；普通会话撤销、自助登出、密码变更或单个授权撤销也不会触发该事件。", "最新 dirty SysUser 删除会在用户与登录信息事务提交后调用内部 RevokeSubjectAsync，写平台主体水位并撤销持久化 Access/Refresh 记录，但不创建 identity.subject.invalidated Outbox；后置撤销失败时，删除事务不会回滚。平台用户禁用依靠登录、Cookie authorize 和 code/refresh/device exchange 的实时状态门禁，也不投递该 Webhook。", "每个当时启用的订阅生成一条 delivery。生命周期内部调用可使用可选 idempotencyKey；管理员 revoke API 则要求请求体提供非空 idempotencyKey，缺失或空白返回 400。顺序重复调用返回已有 event_id，但重放响应里的当前 revoked access-token count 为 0；并发同 Key 仍可能由唯一索引拒绝其中一笔。没有订阅时 Outbox 状态为 no_subscribers。Webhook 异步成功与否不影响 Heimdall 内部撤销事务。"], code: { language: "json", value: identityWebhookEventCode } },
      { id: "configure", title: "Worker 配置与范围", paragraphs: ["identity_webhook.* 属于 Heimdall plugin.yaml。它没有 enabled 开关；插件始终注册后台 Worker。配置在启动时校验，避免忙轮询、无限批次或无界重试。"], code: { language: "yaml", value: identityWebhookConfigCode }, bullets: ["poll_interval_seconds：1–300", "request_timeout_seconds：1–60", "batch_size：1–200", "max_attempts：1–100", "base_retry_seconds：1–3600", "max_retry_seconds：不得小于 base_retry_seconds", "allow_localhost_http：默认 false，仅供本机开发"] },
      { id: "manage", title: "订阅与投递管理 API", paragraphs: ["所有接口要求已认证，并具备 platform.admin 或 platform.security.manage。Controller 使用 api/[controller]，当前 canonical 路径保留 IdentityWebhook 大小写。创建与轮换生成 32 个随机字节并只返回一次 Base64 HMAC Secret；列表和后续查询不返回明文。当前路由只声明 platform.* 权限，未看到 current tenant_id 与 path tenantId 的显式相等检查，因此它是平台管理面，不是租户自助 API。", "管理员主动触发主体失效使用 POST /api/AuthorizationAdmin/tenant/{tenantId}/subject/{subjectId}/revoke，需要 platform.admin 或 platform.authorization.revoke，并必须提交请求体 { idempotencyKey }；缺失或空白返回 400。"], code: { language: "text", value: identityWebhookRoutesCode } },
      { id: "signature", title: "接收端验签", paragraphs: ["签名覆盖 Unix 秒时间戳、英文句点和原始 UTF-8 请求体。接收端必须在解析 JSON 前使用原始字节重算 HMAC-SHA256，常量时间比较小写十六进制签名，并校验 timestamp 的短期容差与 event_id 幂等。"], code: { language: "text", value: identityWebhookSignatureCode }, note: "轮换立即覆盖服务端 Secret，没有原生双 Key 宽限期。先让接收端准备新 Key，再轮换并验证；失败事件手动重投会保留原 event_id，但使用当前订阅 Key 重新签名。" },
      { id: "endpoint", title: "HTTPS 与 SSRF 边界", bullets: ["订阅 URL 必须是无 user-info 的绝对 HTTPS；只有 allow_localhost_http=true 且主机名恰为 localhost 时允许 HTTP，127.0.0.1 不享受例外", "创建、更新和每次投递前解析 DNS；当前明确拒绝 IPv4 0/8、10/8、127/8、169.254/16、172.16/12、192.168/16、>=224，以及 IPv6 loopback/any/none/link-local/multicast/site-local/ULA fc00::/7", "HttpClient 禁止自动重定向，避免通过 30x 跳入内网", "当前仍未明确排除 IPv4 100.64/10 与 198.18/15；IPv6 ULA fc00::/7 已明确拒绝。DNS 校验与实际连接也是两次解析，仍存在覆盖缺口和 rebinding/TOCTOU，生产必须叠加出站代理、防火墙或目的 allowlist"] },
      { id: "delivery", title: "投递、重试与消费语义", bullets: ["Worker 轮询到期 pending 记录，按 batch_size 顺序处理，并用条件更新与 timeout+30 秒租约降低多实例重复发送", "2xx 视为成功；非 2xx、超时或异常进入持久化指数退避并封顶 max_retry_seconds。自定义轮次无 jitter/Retry-After，但底层另有标准 HTTP resilience handler，因此 attempt_count 不等于物理 HTTP 请求次数", "delivery 只冻结 event_id/subscription_id；发送时读取当前 URL、enabled、KeyId 与 Secret，所以更新/轮换会影响历史 pending，禁用/删除会使其失败，新订阅不会补发旧事件", "达到 max_attempts 后进入 failed；管理员可查询错误并手动 retry，重置尝试次数并保留原 event_id/payload，但当前 operatorId 未形成重试审计", "这是至少一次投递而不是恰好一次：任一层重试、租约过期、响应丢失或进程中止都可能重复，接收端必须用 event_id 幂等", "错误文本会去换行并截断到 2048 字符，但下游响应体不被读取或持久化"] },
      { id: "operations", title: "迁移与运维", bullets: ["oidc.bootstrap.auto_sync_schema 默认 false；生产先应用 Database/Migrations/20260715_identity_webhook.postgresql.sql，只有明确打开 auto-sync 才由 CodeFirst 扫描建表", "监控 pending/failed 数、最老 NextAttemptAt、投递延迟、2xx 比例与手动重试", "Secret 在数据库中使用 Asgard Encryption 加密；其安全性继承当前固定 IV、无 AEAD 与无原生轮换信封的边界", "Heimdall 自身在线校验会读取 token 记录与主体撤销水位；只做 JWKS 离线验签的外部 API 不会自动立即失效，必须消费 Webhook、维护 revoked_at 水位、采用适合其架构的 introspection 或缩短 Token TTL", "Webhook 是身份失效通知，不替代 SIEM 安全事件导出"] },
    ],
  },
  {
    slug: "heimdall-federation-mfa",
    group: "部署与运维",
    eyebrow: "HEIMDALL 5.3.19 · FEDERATION + MFA",
    title: "联合身份与 MFA 生产运维 Runbook",
    description: "以可审计的 Schema、上游信任、账号映射、MFA 与故障恢复边界，把 OIDC、LDAP/AD、SAML 和 Passkey 安全投入生产。",
    sections: [
      { id: "baseline-and-schema", title: "上线基线与 Schema 阻断条件", paragraphs: ["外部身份源只证明上游身份；Heimdall 把已验证主体绑定到本地租户用户，同步显式映射的受管角色，执行本地 MFA，再建立 Heimdall Cookie 并返回原 OIDC 授权流程。Token、租户和最终授权仍由 Heimdall 控制。", "clean v5.3.19 的 Database/Migrations 目录仍没有任何 SQL 覆盖 tenant_external_oidc_provider、tenant_external_group_role_mapping、tenant_saml_provider、tenant_saml_identity_binding、tenant_ldap_provider、tenant_ldap_identity_binding、passkey_credential、mfa_recovery_code 这 8 张相关表，也没有完整空 PostgreSQL baseline、迁移 ledger 或 down scripts。生产不得假设按文件名顺序运行现有目录会创建它们。"], bullets: ["发布前在目标 PostgreSQL 对 8 张表、列、索引与租户约束逐项做 Schema diff；任一缺失都阻断上线", "把已审查的组织自有 migration 及其 digest 绑定到 Heimdall 镜像 digest，先 expand、再发布、最后 contract", "不要把 oidc.bootstrap.auto_sync_schema 或 FreeSql CodeFirst 当作生产迁移账本；本页不虚构当前仓库不存在的 SQL", "备份并演练恢复；数据库变化不向后兼容时，回滚镜像本身不构成回滚"], code: { language: "text", value: federationFlowCode } },
      { id: "provider-secrets-and-rotation", title: "Provider Secret 与证书轮换", bullets: ["External OIDC Client Secret、LDAP Bind Password、SAML 签名证书私钥或上游断言绝不进入源码、普通配置、日志、Trace、截图或 Agent 提示词", "先创建或接受新上游凭据，在 Heimdall 更新 Provider 后执行 validate/真实登录，再撤销旧 Secret；没有双 Secret 窗口时安排可回退维护窗口", "SAML 证书轮换必须核对 Entity ID、SSO URL、证书指纹、有效期、签名算法和 IdP/SP 时钟；当前 Provider 模型不是自动信任链轮换控制面", "变更前记录 tenantId、providerId、类型、旧/新非敏感指纹、操作者与时间；不要记录明文 Secret、Bind Password 或完整证书私钥", "启用前先验证，轮换失败时保持或恢复上一个已验证配置，并立即停止继续扩大流量"] },
      { id: "external-oidc-security", title: "External OIDC 信任与 SSRF 边界", paragraphs: ["ExternalOidcDiscoveryService 要求生产 HTTPS、Issuer 精确匹配，验证 authorization_endpoint、token_endpoint 与 jwks_uri，要求 Authorization Code 支持，并拒绝 3xx；发现文档上限为 1 MiB。登录使用随机 state、nonce 与 PKCE，ID Token 校验 issuer、audience、lifetime、签名 key 与 nonce。", "URI 校验只明确拒绝 production loopback、unspecified/link-local 字面 IP；它没有先解析普通 hostname 再全面阻断 RFC1918、IPv6 ULA 或 DNS rebinding。因此这不是完整 SSRF 防护，生产必须用目的域名 allowlist、出站代理/防火墙和受控 DNS 限制 Discovery、Token、JWKS 与 UserInfo 出站。"], bullets: ["OIDC 路由：GET /external-login/oidc/providers、/start/{providerId}、/callback", "管理变更后调用 Provider validate，再用真实上游完成 start → callback → 本地 Cookie → 原 authorize 流程", "Discovery HttpClient 的请求 timeout 为 10 秒，并启用标准 resilience handler；这仍不构成端点 failover 或整体上游可用性证明，上游最终失败必须关闭且不得回退为未验证 Claims", "监控 issuer mismatch、unknown kid、nonce/state/PKCE 失败、Discovery/JWKS 超时与 callback 错误，但不得记录 Code、Token 或断言"] },
      { id: "ldap-tls-and-directory", title: "LDAP/AD 传输、目录与故障边界", paragraphs: ["LdapDirectoryClient 使用 LDAPv3、Basic bind、10 秒 timeout，并关闭 referral chasing。它先用服务账号搜索且要求恰好一条用户记录，再用该用户 DN 和用户密码进行第二次 bind；用户输入会按 RFC 4515 转义后进入 UserFilter。", "生产必须使用受信任 CA 的 LDAPS 或受控 StartTLS，并用真实目录验证证书链、主机名、协议、端口、Base DN、Bind DN、UserFilter、稳定 Subject 属性和 group/memberOf 属性。当前源码没有文档化的连接池、重试、failover 或自定义证书信任策略，不能把一次 validate 成功当作高可用证明。"], bullets: ["LDAP 路由：GET /external-login/ldap/providers；POST /external-login/ldap/{providerId}/login", "服务账号只授予搜索所需最小权限；轮换 Bind Password 后立即 validate 并做用户 bind 冒烟", "目录返回 0 或多条记录、稳定 Subject 属性缺失、TLS/Bind 失败都应拒绝登录，不得 JIT 创建猜测身份", "监控连接/搜索/bind 延迟与失败率；不要在错误中泄露密码、Bind DN 细节或可用于用户枚举的差异"] },
      { id: "saml-certificate-and-clock", title: "SAML 证书、断言与时钟", paragraphs: ["SAML 路径是 SP-Initiated SSO。Heimdall 保存短期登录事务，校验返回的 SAML Response、IdP Entity ID、回调地址、签名证书和事务上下文，再解析稳定 NameID/Subject、邮箱与组。returnUrl 必须继续停留在 Heimdall 允许的本地授权流程。"], bullets: ["路由：GET /external-login/saml/providers、/start/{providerId}；POST /external-login/saml/callback", "上线前对签名篡改、错误 Audience/Recipient/InResponseTo、过期/未来断言、重复 callback、错误租户与未签名响应做负向测试", "所有节点使用 UTC/NTP；在 IdP 与 Heimdall 同时观察证书到期和时钟漂移，提前演练证书切换", "v5.3.19 仍没有证明自动元数据刷新或双证书无缝轮换；把 IdP 证书变化视为受控发布并保留回退配置"] },
      { id: "group-role-reconciliation", title: "本地绑定与受管角色对账", paragraphs: ["稳定绑定键是 Provider + 外部 Subject，不能长期把可变邮箱当主键。OIDC 可要求 email_verified 后才按邮箱关联；LDAP/SAML 是否 JIT 创建和按邮箱关联由 Provider 显式控制。必须先证明目标租户、Client、Cookie 与 Provider 一致，防止跨租户绑定。", "只有 /api/tenants/{tenantId}/external-group-role-mappings 中的显式规则才能把上游 groups/memberOf/属性同步成受管本地角色。下一次同步会移除已撤组或已删除映射对应的受管角色；业务手工角色与受管角色的所有权必须分开。"], bullets: ["先用影子用户验证 JIT、已存在绑定、邮箱冲突、Subject 变化、禁用用户和跨租户拒绝", "修改映射前导出非敏感快照，评估受影响用户；变更后强制登录/对账并抽样有效权限", "Provider 禁用或删除时确认绑定/受管角色撤销行为；不要假设已签发外部 API JWT 会即时失效", "前端角色展示只改善 UX；后端授权和 tenant/resource ownership 仍是安全边界"] },
      { id: "mfa-ticket-totp-recovery-passkey", title: "MFA Ticket、TOTP、恢复码与 Passkey", paragraphs: ["密码或联合登录要求 MFA 时，MfaLoginTicketService 生成 32 字节随机 mfaToken，在 IMultiLevelCache 中保存 300 秒，并用 distributed lock 实现取出即消费。TOTP 验证还应通过 replay protection；恢复码是一次性凭据，轮换前验证 TOTP，明文批次只展示一次。", "Passkey 登录和注册也把一次性 WebAuthn 事务放入缓存 5 分钟，并在消费时获取分布式锁。绑定要求 auth_time 证明最近 10 分钟重新认证；Assertion 要求 User Verification，验证 Credential owner、public key、signature counter 和 user handle。"], code: { language: "http", value: mfaRoutesCode }, bullets: ["Passkey 登录：POST /external-login/passkey/options 与 /complete；管理：GET/POST/DELETE /api/account/me/passkeys", "Registration/Assertion 请求体上限 256 KiB；mfaToken、TOTP Secret、恢复码、Challenge、Credential 和 Assertion 不进入日志或安全事件详情", "生产多实例必须使用真实 Redis/多级缓存和分布式锁验证单次消费、TTL、节点切换、Redis 重启与锁超时；单进程单元测试不能证明这些语义", "至少保留两种独立恢复路径和强身份核验流程，避免删除最后一个因素后永久锁定账户"] },
      { id: "failure-recovery-and-disable", title: "故障恢复、禁用与回退", bullets: ["上游 OIDC/LDAP/SAML 不可用时失败关闭；不要绕过签名、TLS、nonce/state、目录 bind 或 MFA 来维持可用性", "先禁用有问题的 Provider 并保留审计/绑定，再修复和 validate；确认依赖方迁移后才删除，避免不可逆丢失关联上下文", "错误映射导致提权时立即禁用映射或 Provider、撤销本地主体/session、消费 identity.subject.invalidated Webhook，并评估外部 API 离线 JWT 的剩余 TTL", "Redis/分布式锁故障会影响 state、MFA 与 Passkey 单次事务；按失败关闭处理并监控缓存/锁错误，恢复后重新开始登录而不是重放旧 callback", "证书或 Secret 轮换失败时恢复上一份已验证的 Secret/证书配置；若数据库 schema 已不兼容，不得只回滚容器"] },
      { id: "monitoring-and-audit", title: "监控与审计", bullets: ["按 tenantId/providerId/type 统计 provider validate、start、callback、JIT/link、role sync、MFA、Passkey 成功率与延迟，但对用户标识做最小化/脱敏", "告警 Discovery/JWKS/Token Endpoint、LDAP TLS/bind/search、SAML signature/assertion、Redis、distributed lock、TOTP replay 和 WebAuthn counter 异常", "监控 Provider Secret 与 SAML 证书到期、未验证 Provider、长期未用 Provider、角色映射变更、恢复码剩余量和 Passkey 删除", "审计管理员、租户、资源 ID、动作、结果和时间；禁止记录密码、Secret、Token、Cookie、mfaToken、TOTP Seed、恢复码、SAML Response 或 WebAuthn 原始载荷", "将可用性指标与安全事件/SIEM、主体失效 Webhook 相关联；Webhook 投递成功不等于资源 API 已拒绝旧 JWT"] },
      { id: "production-acceptance", title: "生产接受测试", bullets: ["在目标 PostgreSQL 证明 8 张表及约束存在，并在备份副本演练 migration/restore；明确记录仓库没有对应 SQL baseline", "分别以真实 External OIDC、LDAPS/StartTLS、SAML IdP 跑成功和负向流程，包括错误 issuer/key/nonce/state、TLS/certificate、Audience/Recipient/时钟和跨租户", "覆盖 JIT 开/关、email_verified、重复邮箱、已有绑定、组增删/映射删除、禁用/删除 Provider 和本地用户失效", "两节点下用真实 Redis/分布式锁覆盖 state、mfaToken、Passkey transaction 的并发单次消费、TTL、节点切换、锁失败和 Redis 重启", "覆盖 TOTP replay、恢复码一次性/轮换、recent auth_time、Passkey 重放/错误 owner/signature counter/最后因素恢复", "确认日志、Trace、Security Event、Webhook、错误响应和 Agent 材料均不泄露凭据或断言；最后完成 Heimdall Cookie、Authorization Code + PKCE、Token 与资源 API 冒烟"] },
      { id: "release-boundaries", title: "5.3.19 Release 与未证明边界", paragraphs: ["External OIDC Discovery/ID Token 验证、LDAP 双 Bind、SAML SP-Initiated 登录、本地绑定与显式组角色映射、MFA Ticket、TOTP replay protection、一次性恢复码及 Passkey 管理/登录最初在 5.1.2 发布，并继续存在于 clean v5.3.19 / 0032070。当前事实以该不可变 tag 为准。", "未证明：相关 8 张表的发布 migration 或空库 baseline、完整 SSRF 防护、LDAP retry/failover/自定义证书策略、多实例缓存/锁行为，以及真实 IdP/LDAP/SAML/WebAuthn + PostgreSQL + Redis 的端到端生产链路。缺少 ExternalOidcLoginService 与 PasskeyLoginService 完整 E2E 测试；这些必须作为每个部署的接受条件，而不是由类型或局部单元测试推断。"] },
    ],
  },
  {
    slug: "heimdall-scim",
    group: "生态",
    eyebrow: "SCIM 2.0",
    title: "SCIM 用户与用户组供给",
    description: "用租户级 Bearer Token 从企业目录自动创建、更新、停用用户与用户组。",
    sections: [
      { id: "enable", title: "为租户启用 SCIM", paragraphs: ["SCIM 使用独立于 OIDC Access Token 的租户级高熵 Bearer Token。先由拥有 platform.admin 或 platform.tenant.directory.manage 权限的管理员轮换 Token，再显式启用租户 SCIM。明文 Token 只返回一次，数据库保存 SHA-256 哈希并用固定时间比较。"], code: { language: "http", value: scimSetupCode } },
      { id: "base", title: "协议基地址与认证", paragraphs: ["租户基地址是 /scim/v2/{tenantId}。所有协议请求携带 Authorization: Bearer hscim_...，响应使用 application/scim+json。Token 无效、停用或不属于路由租户时返回 SCIM 401 与 WWW-Authenticate。"], code: { language: "http", value: scimRequestCode } },
      { id: "resources", title: "支持的资源与操作", bullets: ["Users：GET 列表/详情、POST、PUT、PATCH、DELETE", "Groups：GET 列表/详情、POST、PUT、PATCH、DELETE", "ServiceProviderConfig、ResourceTypes、Schemas 能力发现", "POST 创建返回 201 与 Location；DELETE 返回 204", "externalId 在同一租户同类资源中唯一，冲突返回 409 uniqueness"] },
      { id: "limits", title: "当前协议能力", bullets: ["PATCH：支持", "Filter：支持，单页最多 200", "Users 仅支持 userName 或 externalId 的 eq", "Groups 仅支持 displayName 或 externalId 的 eq", "Bulk、Sort、ETag、ChangePassword：不支持", "startIndex 从 1 开始；count 会限制到 0–200"] },
      { id: "operations", title: "轮换与故障处理", bullets: ["先在目录系统准备新 Secret，再调用 token/rotate；旧 Token 会立即失效", "确认新 Token 成功读取 ServiceProviderConfig 后再恢复同步任务", "停用租户 SCIM 会拒绝所有协议请求，但不会自动删除已有用户/组", "保存 SCIM request id 与响应状态用于排障，但不记录 Bearer Token 或完整敏感资源", "400 invalidFilter/invalidValue、401、404、409 按 SCIM 错误体处理，不按 Asgard Response 解包"] },
    ],
  },
  {
    slug: "heimdall-siem",
    group: "生态",
    eyebrow: "HEIMDALL 5.3.19 · SECURITY OPERATIONS",
    title: "安全事件与 SIEM 导出",
    description: "查询、处置并按稳定游标把脱敏安全事件送入 SIEM、日志采集器或数据平台。",
    sections: [
      { id: "event-and-authorization-boundary", title: "事件与授权边界", paragraphs: ["Heimdall 记录登录失败/锁定、联合登录与 Passkey 失败、授权码/Refresh Token 重放、会话撤销、恢复码与外部组变化。severity 为 low/medium/high/critical；manual 事件可从 open 处置为 acknowledged、closed 或 dismissed。安全事件用于身份安全运营，不替代 Asgard Trace、数据库日志或业务审计。", "GET /api/security-events/summary 返回 openIncidentCount、acknowledgedIncidentCount 与 auditLast24HoursCount。分页、summary、login-failure-trends、export 与 disposition 都要求已认证且拥有 platform.admin 或 platform.security.manage。export 的 tenantId 是可选过滤器，不是授权边界：具备该平台权限的采集者默认可读跨租户事件。为 SIEM 使用独立主体、短期 Access Token、最小平台权限和受控网络出口。"] },
      { id: "policy-and-operator-queue", title: "处理策略与人工队列", paragraphs: ["SecurityEventPolicy 将 high、critical 和未知类型固定为 manual；明确白名单中的低/中风险事件可成为 automatic。LoginLocked 仍是 manual，但登录失败/锁定可产生不含原始登录标识的 SHA-256 correlationKey。actionableOnly 只返回 manual 且 open/acknowledged 的事件。", "只有 manual、未 archived 的事件可以人工处置。处置备注保留在运营记录但不进入 SIEM 导出。值班流程应先 acknowledge 领取，再调查并 close/dismiss；当前服务没有 assignee、claim lease 或队列所有权字段，多个分析员仍需在外部工单/SOAR 中协调。"] },
      { id: "pull-export-contract", title: "拉取导出合同", paragraphs: ["GET /api/security-events/export 是同步只读 pull API，不是 push delivery/outbox。format 支持 json、ndjson、cef，默认 ndjson；limit clamp 为 1–1000；过滤器为 tenantId、eventType、severity、occurredFrom、occurredTo。响应以 X-Heimdall-Event-Count、X-Heimdall-Has-More 和可选 X-Heimdall-Next-Cursor 描述批次。", "Heimdall 不保存每个 SIEM 消费者的 checkpoint、确认状态、重试计数或 dead-letter。采集器必须自己持久化 cursor、退避、告警和重放策略；不要把 API 200 视为 SIEM 已提交。"], code: { language: "http", value: siemRequestCode } },
      { id: "cursor-and-delivery-semantics", title: "游标与 at-least-once 交付", paragraphs: ["游标是 Base64Url 编码的 occurredAt ticks + event ID，但对消费者必须保持不透明。查询按 occurred_at、id 升序，游标对应事件被保留策略物理删除后仍可继续。只有整批在 SIEM 原子提交后才能保存 next cursor；提交后但 checkpoint 前崩溃会重放整批，因此消费端按 event id 去重，形成 at-least-once。", "若先保存 cursor 再提交会永久丢批；若多个 worker 共享一个 checkpoint 又没有外部锁，会乱序覆盖。每个独立数据流使用一个 durable checkpoint owner，记录过滤器与 schemaVersion，改变 tenant/time/filter 时创建新流而不是复用旧 cursor。"], code: { language: "text", value: siemLoopCode } },
      { id: "schema-formats-and-compatibility", title: "Schema、格式与兼容性", bullets: ["v5.3.19 JSON/NDJSON schemaVersion=1.1，包含 id、UTC occurredAt、tenant/subject/client/session、eventType、severity、handlingMode、correlationKey、status、sourceIp、userAgent、details、disposedBy/disposedAt、archivedAt", "JSON 是带 events 的批次信封；NDJSON 每行一条并固定 LF；消费者按 schemaVersion 和字段名解析，不依赖顺序", "CEF severity 映射 low=2、medium=5、high=8、critical=10，cs4=handlingMode、cs5=correlationKey，archivedAt 不进入 CEF", "当前 CEF header 仍固定输出产品版本 4.1，即使运行 Heimdall 5.3.19；SIEM parser 不应把该 header 当真实部署版本，部署版本由采集器元数据补充", "无效 format、时间范围或 cursor 是应用错误；采集器应隔离坏 checkpoint 并人工恢复，不无限快速重试"] },
      { id: "redaction-and-data-governance", title: "脱敏与数据治理", paragraphs: ["details JSON 会递归检查字段名；包含 password、secret、token、credential、assertion、privatekey、recoverycode 的字段替换为 [REDACTED]，非法 JSON 变为 {invalid:true}。这是 key-name based 防线，不检查普通字符串值、未知别名或上游已写入的自由文本；sourceIp、User-Agent、subject/client/session 标识仍属于敏感运营数据。", "在写事件源头避免放入凭据和无关 PII；导出后再按组织政策做字段 allowlist、加密、访问审计、地域和保留控制。不要把完整 SIEM 权限与 Trace 错误快照权限授予同一低权限角色，并用合成 canary secret 定期验证脱敏而非使用真实 Secret。"] },
      { id: "lifecycle-and-retention", title: "归档、保留与导出滞后", paragraphs: ["SecurityEventLifecycleJob 每 15 分钟注册并带 DisallowConcurrentExecution。默认 enabled、quiet 60 分钟、routine 30/ resolved 180/ high 365/ critical 730 天、batch 1000、每轮最多 20 批，支持 dry_run。typed config 为 security_event.lifecycle.*，Runtime Settings 为 security.event_lifecycle.*。", "归档只处理 automatic + identity.login.failed + low/medium + open。物理删除只处理已归档 routine 登录失败，或 closed/dismissed manual 事件；open/acknowledged 永不删除，其他 automatic 类型当前也没有归档/删除路径。SIEM lag 必须小于最短实际保留窗，否则 cursor 虽能继续但期间被删除的事件不可恢复。先 dry_run、对账计数与 oldest-exported time，再开启删除。"] },
      { id: "aggregation-and-database-boundaries", title: "聚合与数据库边界", paragraphs: ["login-failure-trends 使用固定时间桶和 correlationKey 聚合。aggregation_window_minutes 会影响趋势查询窗口并被传入 Job options，但 lifecycle core 的 quiet cutoff 仍按每条 OccurredAt 判断，不按 correlation group 最后活动；不要宣称相关事件会形成可延长静默期的 incident。", "20260716_security_event_lifecycle.postgresql.sql 最初随 5.1.2 发布，并继续存在于 v5.3.19；它增加生命周期字段/索引和历史回填。PostgreSQL 登录保护使用 ProtectionKey 原子 UPSERT 与 LockoutTriggeredAt；其他 provider 仍有非原子读改写边界。数据库迁移、索引和生产数据量查询计划必须在启用 lifecycle/export 前单独验收。"] },
      { id: "failure-recovery-and-acceptance", title: "故障恢复与生产验收", bullets: ["从固定 UTC 起点全量回放到空 SIEM，逐批验证 count/has-more/cursor；重复同一批证明按 id 去重且无重复告警", "在 SIEM 提交前、提交后 checkpoint 前分别杀死采集器，证明前者不推进、后者安全重放", "并行产生相同 occurredAt 的事件，验证 id 次序无遗漏；归档/删除游标对应事件后继续拉取", "注入 401/403、400 坏 cursor、429、5xx、超时和数据库失败；分类退避，认证错误停机告警，不丢 durable checkpoint", "比较 Heimdall 时间窗 count、导出接收数、SIEM 去重数与 checkpoint lag；对 high/critical 建立独立实时延迟 SLO", "多 Heimdall 副本读取同一数据库时验证相同 cursor/filter 返回一致事件顺序；Quartz DisallowConcurrentExecution 不等于已证明的跨节点 lifecycle 单例", "回滚采集器时保留旧 parser/checkpoint；回滚 Heimdall 前证明 schemaVersion 与查询字段兼容，不清空事件表或重置 cursor"] },
      { id: "release-boundaries", title: "Release 与未证明边界", paragraphs: ["lifecycle job/config、策略/summary/actionable 队列、趋势聚合、JSON/NDJSON/CEF 1.1 导出、稳定游标、递归脱敏、保留 SQL 及相关合同测试最初随 5.1.2 发布，并继续存在于 clean v5.3.19 / 0032070。", "未证明/未发布：push connector、Kafka/Syslog/Webhook delivery、consumer registry/checkpoint、exactly-once、服务端 retry/dead-letter、assignee/claim lease、跨节点 lifecycle 分布式锁、CEF 中真实 5.3.19 版本、通用内容级 DLP、所有 provider 的原子登录保护，以及生产规模 SIEM 端到端测试。"] },
    ],
  },
];

export const enHeimdallAdvancedDocs: DocPage[] = [
  {
    slug: "heimdall-jwt-signing", group: "Ecosystem", eyebrow: "MINI JWT ISSUER · 5.3.19", title: "Lightweight JWT signing for Asgard APIs", description: "Issue Asgard-compatible user and backend-service access tokens with Discovery/JWKS, without deploying the full Heimdall IDP.", sections: [
      { id: "product-and-version-boundary", title: "Product and version boundary", paragraphs: ["The mini issuer is two NuGet packages, not the full Heimdall Server. Both projects removed the old project-level 0.2.0 override and now build package version 5.3.19 from Directory.Build.props at v5.3.19 / 0032070.", "It issues Asgard access tokens only after the application authenticates a subject and exposes minimal Discovery/JWKS. Use full Heimdall for Authorization Code + PKCE, refresh tokens, consent, SSO, revocation, and session governance."], bullets: ["Asgard.Heimdall.JwtSigning: issuing, claims, and RSA JWKS", "Asgard.Heimdall.JwtSigning.AspNetCore: DI, startup validation, and endpoint mapping", "Resource APIs reference neither package; they configure Asgard host.auth.jwt"] },
      { id: "packages-and-installation", title: "Install, validate startup, and protect secrets", paragraphs: ["Pin both packages to 5.3.19. Registration validates Issuer, Audience, KeyId, a static absolute DiscoveryPathPrefix, a token lifetime from one second through int.MaxValue seconds, and the key/algorithm combination. Provide exactly one RSA private or symmetric key. The issuer is a Singleton with fixed configuration and key."], code: { language: "shell", value: miniIssuerInstallCode }, note: "Inject the private key from a secret manager or protected file; never place it in appsettings, source, logs, image layers, or agent prompts." },
      { id: "rsa-only-public-discovery", title: "Public Discovery/JWKS enforces RSA", paragraphs: ["Version 5.3.19 closes the old symmetric-JWKS disclosure path. Core symmetric signing remains possible, but CreateJwksDocument rejects it and MapAsgardHeimdallJwtSigningDiscovery() throws.", "Public Discovery/JWKS requires a matching RSA key pair of at least 2048 bits and RS256/384/512 or PS256/384/512. Symmetric mode permits only HS256/384/512 with minimum 32/48/64-byte keys distributed separately through a secure channel."], bullets: ["Release gate: JWKS contains no k, d, p, q, dp, dq, or qi", "Token header kid and JWKS kid match", "Discovery no longer advertises id_token_signing_alg_values_supported; the mini issuer issues access tokens only"] },
      { id: "issuer-and-endpoints", title: "Issuer, paths, and endpoint contract", paragraphs: ["Use the official extensions. DiscoveryPathPrefix controls mapped routes, but the default jwks_uri is derived from Issuer + /.well-known/jwks.json and does not use DiscoveryPathPrefix. They align naturally only when Issuer carries the same path segment; otherwise set JwksUriOverride and verify it with a real public GET.", "The document exposes issuer, jwks_uri, claims_supported, signing algorithms, public subject type, and empty response_types. It is not a complete OIDC Provider and cannot run authorize/token flows."], code: { language: "csharp", value: miniIssuerSetupCode } },
      { id: "issue-user-and-service", title: "Issue user and backend-service tokens", paragraphs: ["The application validates passwords, OTPs, or external identities first, then calls Issue. Subject is required; default lifetime is one hour and token_type is UserLogin. Roles, Permissions, and Scope become JSON arrays and metadata becomes JSON objects."], code: { language: "csharp", value: miniIssuerUserTokenCode }, bullets: ["BackendService requires Subject, ClientId, and BackendService token_type and forbids UserId", "AsgardJwtIssueOptions overrides Audience, Lifetime, IssuedAt, and Jti per issue", "The issuer has no refresh, revocation, blacklist, introspection, or account-state recheck"], note: miniIssuerServiceTokenCode },
      { id: "asgard-resource-integration", title: "Integrate an Asgard 5.1.3 resource API", paragraphs: ["Asgard 5.1.3 built-in host.auth requires issuerTemplate to contain exactly one {tenant}; the resolved issuer, Discovery issuer, and token iss must match exactly. Its single configured audience must exactly match one token aud. The example uses the same GUID for Issuer path, DiscoveryPathPrefix, and tenant_id."], code: { language: "yaml", value: miniIssuerResourceCode }, bullets: ["Keep requireHttpsMetadata=true in production", "The resource validates through Discovery/JWKS and never receives the RSA private key", "For 401 inspect routes, issuer, jwks_uri, kid, aud, expiry, and clock; for 403 inspect token_type, roles, permissions, scope, and tenant_id"] },
      { id: "key-lifecycle-and-rotation", title: "Key lifecycle and rotation", paragraphs: ["The 5.3.19 Singleton still holds one active key and RSA JWKS publishes that key only. There is no configuration reload, multi-key overlap, active/retiring state, KMS/HSM provider, or managed rotation. Replacing the key and restarting causes old tokens to lose verification material after verifier caches refresh."], bullets: ["Keep token lifetime as short as operationally acceptable", "Publishing old and new keys together requires an external extension or a later released capability; one current instance cannot overlap them", "Without overlap, coordinate a maintenance window, every replica, JWKS caches, old-token lifetime, and rollback", "Never reuse a KeyId for different key material"] },
      { id: "revocation-and-security-operations", title: "Revocation and endpoint operations", paragraphs: ["The mini issuer stores no token, session, or subject state and has no revoke/introspection endpoint. A token does not automatically fail before expiry when a user is disabled. Use full Heimdall or a released, accepted deny-list/introspection/invalidation design for immediate revocation.", "Package endpoints add no authentication, Cache-Control, rate-limit, health, or audit policy. The host and reverse proxy must supply HTTPS, trusted host/forwarded-header handling, caching, limits, monitoring, and response-size controls."], bullets: ["Monitor public Discovery/JWKS status, MIME, issuer, jwks_uri, kid, and latency", "All replicas publish identical Issuer, KeyId, and public key", "Log non-secret metadata such as jti/kid and failure class, never complete tokens"] },
      { id: "production-acceptance", title: "Production acceptance", bullets: ["Invalid issuer/audience/kid/prefix/key input fails startup", "Public Discovery and jwks_uri are reachable and issuer matches exactly", "JWKS is RSA-public-only; token kid resolves to exactly one key", "User and BackendService claims, one-hour default, and per-issue overrides pass tests", "Asgard rejects wrong tenant, issuer, audience, kid, and expired tokens with 401, and insufficient permission with 403", "Replicas return identical documents and restart does not generate a new key", "Rotation, cache refresh, old-token behavior, rollback, and downtime are rehearsed and recorded"] },
      { id: "release-boundaries", title: "Release and unproven boundaries", paragraphs: ["Release: v5.3.19 / 0032070 provides package version 5.3.19, Application authorization claims, strict key/algorithm/lifetime/path validation, RSA-only public Discovery/JWKS, single-key JWT issuance, and user plus BackendService tokens. HEAD equals the tag.", "Unproven/not provided: complete OIDC Provider, refresh, revoke/introspection, key reload, multi-key overlap, automatic rotation, KMS/HSM, endpoint caching or rate-limit policy, dynamic multi-tenant issuers, and production replica or rotation E2E proof."] },
    ],
  },
  {
    slug: "heimdall-mcp", group: "Ecosystem", eyebrow: "HEIMDALL 5.3.19 · GOVERNED MCP", title: "Connect to Heimdall MCP", description: "Use the v5.3.19 stateful Streamable HTTP management plane with correct OAuth/AK-SK, policy, two-phase write, and audit boundaries.", sections: [
      { id: "status", title: "v5.3.19 Release contract", paragraphs: ["v5.3.19 / 0032070 exposes a stateful Streamable HTTP management plane at /mcp. Version 5.3.0 first completed platform/tenant management Tools, five Resources, six Prompts, bounded Tasks, OAuth and AK/SK, credential policy, two-phase confirmation, and security-event audit; later 5.3.x releases complete Application/OIDC Client tools and the management workspace.", "Clients discover tools/list, resources/list, and prompts/list dynamically. Stable names use platform_, tenant_, or heimdall_ prefixes; a static documentation list is not runtime authority."] },
      { id: "model", title: "Identity, Application, and endpoint boundary", paragraphs: ["OAuth clients read /.well-known/oauth-protected-resource/mcp and send a Heimdall Access Token. The endpoint policy requires the built-in Heimdall management Application and protects Tools, Resources, Prompts, and Tasks.", "AK/SK uses hmcp_p_ or hmcp_t_ prefixes. The server fixes tenant identity from the credential; tools cannot accept a tenant switch. Authentication reconstructs current account, Application, role, and permission boundaries. AllowedPermissions only intersects current permissions and cannot add privilege."], code: { language: "http", value: mcpRequestCode } },
      { id: "create", title: "Credential policy and one-time secrets", paragraphs: ["The current token_type=UserLogin account manages its own credentials under /api/mcp-credentials. Create/reset returns SK once and persists only a hash. Policy covers allowedTools, allowedPermissions, allowedCidrs, expiresAt, environment, rateLimitPerMinute, and maxConcurrentCalls.", "An empty tool or permission list means no additional narrowing, not deny all. A restricted credential delegating another credential must stay within its own tool and permission subset; an empty list cannot bypass an existing caller allowlist."], code: { language: "http", value: mcpCredentialCode }, bullets: ["GET /api/mcp-credentials/catalog: dynamic tool and permission catalog", "PUT /api/mcp-credentials/{id}/policy: update policy", "POST /api/mcp-credentials/{id}/reset-secret: rotate SK", "PUT status and DELETE: invalidate credentials"] },
      { id: "safe-writes", title: "Every write tool uses two-phase confirmation", paragraphs: ["The first call to any non-read-only tool omits confirmationToken and returns an impact preview plus a short-lived token. Execution occurs only after a human or agent reviews it and repeats the exact payload with that token.", "The token binds CredentialId, ToolName, and normalized payload hash and is single-use. Changed arguments, caller, tool, or replay fails. Tools still call existing Services and resource AccessGuards rather than writing Repositories/Entities directly."], bullets: ["Paging returns McpPageResult<T>", "Mutations return McpMutationResult<T>", "High-impact actions are Destructive; create, rotate, and redeliver use their real non-idempotent semantics", "Read the target and validate Application/Tenant ownership before ID-based writes"] },
      { id: "tools", title: "Management capabilities and permissions", bullets: ["Platform: Tenant/onboarding, SystemUser, Application/Manifest/Grant, platform RBAC, runtime/security/object storage, logs/Trace, security events/SIEM/TOTP", "Tenant: users/directory, Application RBAC, OIDC Clients/Scopes/Keys, federation, sessions/authorizations, deny list, SCIM, Webhooks, and TOTP", "MCP governance: credential Catalog/Lifecycle, Policy, audit, confirmation, rate/concurrency, Resources, Prompts, and Tasks", "Version 5.3.8 adds platform Application/OIDC Client tools. Old explicit allowedTools lists do not gain them until reviewed and added"] },
      { id: "tasks-and-audit", title: "Tasks, audit, and replicas", paragraphs: ["Protocol Tasks have TTL, global/session capacity, and minimum-polling limits. The current production assumption is one Heimdall application container with an in-memory Store. Horizontal scaling first requires a shared durable Store plus recovery, quota, and concurrency acceptance.", "Every successful or failed tool call emits mcp.tool.invoked with tool, credential, environment, result, duration, and error type—never SK, Client Secret, Webhook Secret, private key, or full sensitive headers."] },
      { id: "migration-and-acceptance", title: "Migration and release acceptance", paragraphs: ["With auto_sync_schema=false, apply 20260720_mcp_credential_policy.postgresql.sql in addition to the older 20260715_mcp_credentials increment before updating the application; the older increment creates credential columns such as credential_name, while the later one expands platform and tenant credential-policy columns to varchar(8192).", "Acceptance covers OAuth metadata, built-in-Application tokens and rejection of external-Application tokens, AK/SK disable/expiry/CIDR/rate/concurrency, platform/tenant catalog isolation, delegation subsets, every write confirmation, and common endpoint protection for tools/resources/prompts/tasks."] },
    ],
  },
  {
    slug: "heimdall-identity-webhooks", group: "Ecosystem", eyebrow: "HEIMDALL 5.3.19 · IDENTITY WEBHOOK", title: "Identity invalidation webhooks", description: "Revoke local identity and deliver signed events to trusted downstream systems when a subject is disabled, deleted, or administratively revoked.", sections: [
      { id: "status", title: "Shipped Heimdall 5.3.19 contract", paragraphs: ["Identity Webhooks first shipped in 5.1.2. The current clean tag v5.3.19 at commit 0032070 still contains the controller, Outbox, worker, HMAC signing, retry, PostgreSQL increment, JSON Schema, and management UI. The HTTP contract uses event_type=identity.subject.invalidated, version=1, and reason disabled, deleted, or revoked.", "A shipped artifact is not a completed downstream integration. Accept a real Tenant Client, Webhook secret, signatures, replay protection, idempotency, the revocation watermark, and rejection of old JWTs end to end."] },
      { id: "flow", title: "Identity invalidation and Outbox", paragraphs: ["When a tenant user transitions out of Enabled, is deleted individually/in bulk, or is administratively subject-revoked, Heimdall writes subject-session revocation, revokes access/refresh tokens, grants, authorization codes, device codes, consent, and active sessions, and creates an identity.subject.invalidated v1 Outbox in the same database transaction. Platform users are outside the Webhook scope; ordinary session revocation, self logout, password change, or revoking one authorization does not emit this event.", "The latest dirty SysUser delete calls internal RevokeSubjectAsync after the user/login-info transaction commits. It writes a platform-subject watermark and revokes persisted Access/Refresh records but creates no identity.subject.invalidated Outbox; a later revocation failure cannot roll back the committed deletion. Platform-user disable relies on live login, Cookie authorize, and code/refresh/device exchange state gates and likewise emits no Webhook.", "Lifecycle-internal calls may use an optional idempotencyKey. The administrator revoke API requires a nonblank idempotencyKey body; missing or blank input returns 400. Sequential replay returns the existing event_id, but its current revoked-access-token count is 0; concurrent same-key calls can still make one transaction lose to the unique index. An event with no subscription is marked no_subscribers. Asynchronous webhook success is not part of Heimdall's internal revocation transaction."], code: { language: "json", value: identityWebhookEventCode } },
      { id: "configure", title: "Worker configuration and ranges", paragraphs: ["identity_webhook.* belongs in Heimdall plugin.yaml. It has no enabled flag; the plugin always registers the background worker. Startup validation prevents busy polling, unbounded batches, and unrestricted retries."], code: { language: "yaml", value: identityWebhookConfigCode }, bullets: ["poll_interval_seconds: 1–300", "request_timeout_seconds: 1–60", "batch_size: 1–200", "max_attempts: 1–100", "base_retry_seconds: 1–3600", "max_retry_seconds must be at least base_retry_seconds", "allow_localhost_http defaults false and is development-only"] },
      { id: "manage", title: "Subscription and delivery management APIs", paragraphs: ["Every endpoint requires authentication plus platform.admin or platform.security.manage. The controller uses api/[controller], so the current canonical path retains IdentityWebhook casing. Create and rotate generate 32 random bytes and return the Base64 HMAC secret once; list and later queries omit it. Current routes declare only platform.* permissions and do not visibly compare current tenant_id with path tenantId, so treat this as a platform administration surface, not tenant self-service.", "An administrator explicitly invalidates a subject through POST /api/AuthorizationAdmin/tenant/{tenantId}/subject/{subjectId}/revoke with platform.admin or platform.authorization.revoke and must send { idempotencyKey }; missing or blank input returns 400."], code: { language: "text", value: identityWebhookRoutesCode } },
      { id: "signature", title: "Verify on the receiver", paragraphs: ["The signature covers the Unix-seconds timestamp, one ASCII period, and the raw UTF-8 request body. Before JSON parsing, recompute HMAC-SHA256 over the original bytes, compare the lowercase hexadecimal signature in constant time, enforce a short timestamp tolerance, and deduplicate event_id."], code: { language: "text", value: identityWebhookSignatureCode }, note: "Rotation immediately replaces the server-side secret and has no dual-key grace period. Prepare the receiver, rotate, and verify. Manual redelivery preserves event_id but signs with the subscription's current key." },
      { id: "endpoint", title: "HTTPS and SSRF boundary", bullets: ["The endpoint must be an absolute HTTPS URL without user-info; HTTP is allowed only when allow_localhost_http=true and the hostname is exactly localhost—127.0.0.1 receives no exception", "Create, update, and every delivery resolve DNS. Current explicit blocks cover IPv4 0/8, 10/8, 127/8, 169.254/16, 172.16/12, 192.168/16, >=224 and IPv6 loopback/any/none/link-local/multicast/site-local/ULA fc00::/7", "The HttpClient disables automatic redirects so a 30x cannot intentionally hop into a private network", "IPv4 100.64/10 and 198.18/15 are still not explicitly blocked; IPv6 ULA fc00::/7 is now rejected. Validation and connection also resolve separately, leaving coverage and DNS-rebinding/TOCTOU gaps; production must add an egress proxy/firewall or destination allowlist"] },
      { id: "delivery", title: "Delivery, retry, and consumer semantics", bullets: ["The worker polls due pending rows, processes up to batch_size in order, and uses a conditional claim with a timeout+30-second lease to reduce duplicate concurrent sends", "2xx succeeds; non-2xx, timeout, or exception enters persistent exponential backoff capped by max_retry_seconds. That custom round has no jitter/Retry-After, but a standard HTTP resilience handler also runs underneath, so attempt_count is not the physical HTTP request count", "A delivery snapshots event_id/subscription_id only. Send reads the current URL, enabled state, KeyId, and Secret: update/rotation affects old pending rows, disable/delete fails them, and a new subscription does not receive old events", "After max_attempts the delivery becomes failed; manual retry resets attempts and preserves event_id/payload, but its operatorId is currently not persisted as retry audit", "Delivery is at-least-once, not exactly-once: either retry layer, lease expiry, response loss, or process termination can duplicate a request, so receivers must deduplicate event_id", "Stored errors have line breaks removed and are capped at 2048 characters; downstream response bodies are neither read nor persisted"] },
      { id: "operations", title: "Migration and operations", bullets: ["oidc.bootstrap.auto_sync_schema defaults false; apply Database/Migrations/20260715_identity_webhook.postgresql.sql first unless CodeFirst auto-sync is explicitly enabled", "Monitor pending/failed counts, oldest NextAttemptAt, delivery lag, 2xx rate, and manual retries", "The database encrypts the Secret with Asgard Encryption, inheriting its fixed-IV, non-AEAD, and no-native-envelope boundaries", "Heimdall online validation reads token records and the subject revocation watermark. An external API doing JWKS-only offline verification does not become immediately aware; consume this webhook, maintain revoked_at state, use architecture-appropriate introspection, or shorten token TTL", "This webhook carries identity invalidation and does not replace SIEM security-event export"] },
    ],
  },
  {
    slug: "heimdall-federation-mfa", group: "Deployment & Operations", eyebrow: "HEIMDALL 5.3.19 · FEDERATION + MFA", title: "Federation and MFA production runbook", description: "Take OIDC, LDAP/AD, SAML, and Passkeys to production with auditable schema, upstream trust, account mapping, MFA, and recovery boundaries.", sections: [
      { id: "baseline-and-schema", title: "Go-live baseline and schema blocker", paragraphs: ["An upstream provider proves external identity. Heimdall binds a validated subject to a local tenant user, synchronizes explicitly managed roles, performs local MFA, then creates the Heimdall cookie and returns to the original OIDC authorization flow. Heimdall still owns tokens, tenancy, and final authorization.", "The clean v5.3.19 Database/Migrations directory still contains no SQL for the eight related tables: tenant_external_oidc_provider, tenant_external_group_role_mapping, tenant_saml_provider, tenant_saml_identity_binding, tenant_ldap_provider, tenant_ldap_identity_binding, passkey_credential, and mfa_recovery_code. It also has no complete empty-PostgreSQL baseline, migration ledger, or down scripts. Never assume running the current directory in filename order creates them."], bullets: ["Schema-diff all eight tables, columns, indexes, and tenant constraints in the target PostgreSQL; any missing contract blocks release", "Bind the organization's reviewed migration and digest to the Heimdall image digest; expand first, deploy compatible code, then contract", "Do not treat oidc.bootstrap.auto_sync_schema or FreeSql CodeFirst as a production migration ledger; this guide does not invent absent SQL", "Back up and rehearse restore; rolling back an image alone cannot undo an incompatible database change"], code: { language: "text", value: federationFlowCode } },
      { id: "provider-secrets-and-rotation", title: "Provider secret and certificate rotation", bullets: ["External OIDC Client Secrets, LDAP Bind Passwords, SAML private signing material, and upstream assertions never enter source, ordinary configuration, logs, traces, screenshots, or agent prompts", "Create or accept the new upstream credential first, update the Heimdall provider, run validate and a real sign-in, then revoke the old secret; schedule a rollback-capable maintenance window when no overlap exists", "For SAML rotation, verify Entity ID, SSO URL, certificate fingerprint and lifetime, signature algorithm, and IdP/SP clocks; the current provider model is not an automated trust-chain rotation control plane", "Record tenantId, providerId, type, old/new non-sensitive fingerprints, operator, and time; never record plaintext secrets, bind passwords, or private certificate material", "Validate before enabling. On rotation failure, retain or restore the last verified configuration and stop increasing traffic"] },
      { id: "external-oidc-security", title: "External OIDC trust and SSRF boundary", paragraphs: ["ExternalOidcDiscoveryService requires production HTTPS and exact issuer equality, validates authorization_endpoint, token_endpoint, and jwks_uri, requires Authorization Code support, rejects 3xx, and caps Discovery at 1 MiB. Sign-in uses random state, nonce, and PKCE; ID Token validation checks issuer, audience, lifetime, signing key, and nonce.", "URI validation explicitly rejects production loopback plus literal unspecified/link-local addresses only. It does not first resolve a normal hostname and comprehensively block RFC1918, IPv6 ULA, or DNS rebinding. This is not complete SSRF protection: constrain Discovery, Token, JWKS, and UserInfo egress with hostname allowlists, an egress proxy/firewall, and controlled DNS."], bullets: ["Routes: GET /external-login/oidc/providers, /start/{providerId}, and /callback", "After a provider change, call validate and complete a real upstream start → callback → local cookie → original authorize flow", "The Discovery HttpClient has a ten-second request timeout and the standard resilience handler. That still does not prove endpoint failover or overall upstream availability; final upstream failure closes authentication and never falls back to unverified claims", "Monitor issuer mismatch, unknown kid, nonce/state/PKCE failure, Discovery/JWKS timeout, and callback errors without logging codes, tokens, or assertions"] },
      { id: "ldap-tls-and-directory", title: "LDAP/AD transport, directory, and failure boundary", paragraphs: ["LdapDirectoryClient uses LDAPv3, Basic bind, a ten-second timeout, and ReferralChasing=None. It searches with a service account, requires exactly one entry, then binds again with that user's DN and password. User input is RFC 4515-escaped before entering UserFilter.", "Production requires LDAPS or controlled StartTLS with a trusted CA. Test certificate chain, hostname, protocol, port, Base DN, Bind DN, UserFilter, stable Subject attribute, and group/memberOf against the real directory. The source exposes no documented pool, retry, failover, or custom certificate-trust policy, so one validate success is not availability proof."], bullets: ["Routes: GET /external-login/ldap/providers; POST /external-login/ldap/{providerId}/login", "Grant the service account only required search rights; validate and perform a user-bind smoke test immediately after Bind Password rotation", "Zero/multiple search results, missing stable Subject, TLS failure, or bind failure reject login and never JIT-create a guessed identity", "Monitor connect/search/bind latency and failures without leaking passwords, sensitive Bind DN details, or user-enumeration differences"] },
      { id: "saml-certificate-and-clock", title: "SAML certificates, assertions, and clocks", paragraphs: ["SAML is SP-Initiated SSO. Heimdall stores a short-lived login transaction, validates the SAML Response, IdP Entity ID, callback address, signing certificate, and transaction context, then reads stable NameID/Subject, email, and groups. returnUrl remains inside Heimdall's permitted local authorization flow."], bullets: ["Routes: GET /external-login/saml/providers and /start/{providerId}; POST /external-login/saml/callback", "Before release, negatively test signature tampering, wrong Audience/Recipient/InResponseTo, expired/future assertions, replayed callback, wrong tenant, and unsigned response", "Keep every node on UTC/NTP; monitor certificate expiry and clock drift at both IdP and Heimdall and rehearse certificate cutover early", "Version 5.3.19 still does not prove automatic metadata refresh or seamless dual-certificate rotation; treat IdP certificate changes as controlled releases with rollback configuration"] },
      { id: "group-role-reconciliation", title: "Local binding and managed-role reconciliation", paragraphs: ["Provider + external Subject is the stable binding key; mutable email is not a durable primary key. OIDC can require email_verified before email linking, while LDAP/SAML JIT and email linking are explicit provider choices. Prove the target tenant, client, cookie, and provider agree before binding.", "Only rules under /api/tenants/{tenantId}/external-group-role-mappings turn upstream groups/memberOf/attributes into managed local roles. The next synchronization removes managed roles after upstream group removal or mapping deletion. Keep ownership of manually assigned business roles separate."], bullets: ["Use shadow users to test JIT on/off, existing bindings, email collision, Subject changes, disabled users, and cross-tenant denial", "Export a non-sensitive snapshot and estimate affected users before changing mappings; force sign-in/reconciliation and sample effective permissions afterwards", "Verify binding/managed-role behavior when disabling or deleting a provider; do not assume an issued JWT at an external API becomes invalid immediately", "Frontend role display improves UX only; backend authorization and tenant/resource ownership remain the security boundary"] },
      { id: "mfa-ticket-totp-recovery-passkey", title: "MFA tickets, TOTP, recovery codes, and Passkeys", paragraphs: ["When password or federated sign-in requires MFA, MfaLoginTicketService creates a random 32-byte mfaToken, stores it in IMultiLevelCache for 300 seconds, and uses a distributed lock for take-once consumption. TOTP also needs replay protection. Recovery codes are one-time credentials; rotation verifies TOTP and reveals plaintext only once.", "Passkey sign-in and registration likewise keep one-time WebAuthn transactions in cache for five minutes and acquire a distributed lock on consumption. Binding requires auth_time proving reauthentication within ten minutes. Assertions require User Verification and validate credential owner, public key, signature counter, and user handle."], code: { language: "http", value: mfaRoutesCode }, bullets: ["Passkey sign-in: POST /external-login/passkey/options and /complete; management: GET/POST/DELETE /api/account/me/passkeys", "Registration/assertion bodies are capped at 256 KiB; mfaToken, TOTP secrets, recovery codes, challenges, credentials, and assertions stay out of logs and security-event details", "A multi-node production deployment must prove single consumption, TTL, node handoff, Redis restart, and lock timeout with real Redis/multi-level cache and distributed locks; a single-process unit test cannot prove these semantics", "Retain at least two independent recovery paths and a strong identity-verification process so deleting the final factor does not permanently lock the account"] },
      { id: "failure-recovery-and-disable", title: "Failure recovery, disable, and rollback", bullets: ["Fail closed when upstream OIDC/LDAP/SAML is unavailable; never bypass signatures, TLS, nonce/state, directory bind, or MFA to preserve availability", "Disable a faulty provider first and retain audit/bindings while repairing and validating it; delete only after dependents migrate so association context is not irreversibly lost", "On privilege escalation from a bad mapping, disable the mapping/provider, revoke local subject/session state, consume identity.subject.invalidated, and assess the remaining TTL of offline JWTs at external APIs", "Redis or distributed-lock failure affects state, MFA, and Passkey one-time transactions. Fail closed, monitor errors, and restart sign-in after recovery rather than replaying an old callback", "Restore the prior verified secret/certificate configuration after a failed rotation; when schema is incompatible, changing only the container is not rollback"] },
      { id: "monitoring-and-audit", title: "Monitoring and audit", bullets: ["Measure provider validate, start, callback, JIT/link, role sync, MFA, and Passkey success/latency by tenantId/providerId/type while minimizing or redacting user identifiers", "Alert on Discovery/JWKS/Token Endpoint, LDAP TLS/bind/search, SAML signature/assertion, Redis, distributed lock, TOTP replay, and WebAuthn counter failures", "Monitor provider secrets and SAML certificate expiry, unvalidated or stale providers, mapping changes, remaining recovery codes, and Passkey deletion", "Audit administrator, tenant, resource ID, action, result, and time. Never record passwords, secrets, tokens, cookies, mfaToken, TOTP seeds, recovery codes, SAML Responses, or raw WebAuthn payloads", "Correlate availability with security events/SIEM and subject-invalidation webhooks; successful webhook delivery does not prove a resource API rejected an old JWT"] },
      { id: "production-acceptance", title: "Production acceptance", bullets: ["Prove all eight tables and constraints in target PostgreSQL and rehearse migration/restore on a backup copy, explicitly recording that the repository has no matching SQL baseline", "Run positive and negative flows against a real external OIDC, LDAPS/StartTLS directory, and SAML IdP, including wrong issuer/key/nonce/state, TLS/certificate, Audience/Recipient/clock, and cross-tenant cases", "Cover JIT on/off, email_verified, duplicate email, existing binding, group add/remove and mapping deletion, provider disable/delete, and local-user invalidation", "On two nodes with real Redis/distributed locks, cover concurrent single consumption, TTL, node handoff, lock failure, and Redis restart for state, mfaToken, and Passkey transactions", "Cover TOTP replay, one-time recovery/rotation, recent auth_time, Passkey replay/wrong owner/signature counter, and final-factor recovery", "Prove that logs, traces, security events, webhooks, errors, and agent material leak no credentials/assertions, then complete Heimdall-cookie, Authorization Code + PKCE, token, and resource-API smoke tests"] },
      { id: "release-boundaries", title: "5.3.19 release and unproven boundaries", paragraphs: ["External OIDC Discovery/ID Token validation, LDAP double-bind, SAML SP-Initiated sign-in, local bindings and explicit group-role mapping, MFA tickets, TOTP replay protection, one-time recovery codes, and Passkey management/sign-in first shipped in 5.1.2 and remain present in clean v5.3.19 at 0032070. This immutable tag is the current authority.", "Unproven: a released migration for the eight tables or empty-database baseline, complete SSRF protection, LDAP retry/failover/custom certificate policy, multi-instance cache/lock behavior, and a real IdP/LDAP/SAML/WebAuthn + PostgreSQL + Redis end-to-end production path. ExternalOidcLoginService and PasskeyLoginService lack complete E2E coverage; treat these as deployment acceptance conditions, never infer them from types or focused unit tests."] },
    ],
  },
  {
    slug: "heimdall-scim", group: "Ecosystem", eyebrow: "SCIM 2.0", title: "SCIM user and group provisioning", description: "Use a tenant Bearer token to create, update, and deactivate users and groups from an enterprise directory.", sections: [
      { id: "enable", title: "Enable SCIM for a tenant", paragraphs: ["SCIM uses a tenant-specific high-entropy Bearer token, independent of OIDC access tokens. An administrator with platform.admin or platform.tenant.directory.manage rotates a token, then explicitly enables SCIM. Plaintext is returned once; the database stores a SHA-256 hash and validates it in fixed time."], code: { language: "http", value: scimSetupCode } },
      { id: "base", title: "Protocol base and authentication", paragraphs: ["The tenant base is /scim/v2/{tenantId}. Every protocol request sends Authorization: Bearer hscim_... and receives application/scim+json. An invalid, disabled, or cross-tenant token returns a SCIM 401 plus WWW-Authenticate."], code: { language: "http", value: scimRequestCode } },
      { id: "resources", title: "Resources and operations", bullets: ["Users: list/detail GET, POST, PUT, PATCH, DELETE", "Groups: list/detail GET, POST, PUT, PATCH, DELETE", "ServiceProviderConfig, ResourceTypes, and Schemas discovery", "Create returns 201 and Location; delete returns 204", "externalId is unique per tenant and resource type; conflicts return 409 uniqueness"] },
      { id: "limits", title: "Current protocol capabilities", bullets: ["PATCH: supported", "Filter: supported, at most 200 results per page", "Users support only userName or externalId eq", "Groups support only displayName or externalId eq", "Bulk, Sort, ETag, and ChangePassword: unsupported", "startIndex begins at 1; count is clamped to 0–200"] },
      { id: "operations", title: "Rotation and failures", bullets: ["Prepare the new secret in the directory system, then call token/rotate; the old token becomes invalid immediately", "Verify ServiceProviderConfig with the new token before resuming synchronization", "Disabling SCIM rejects protocol calls but does not delete existing users or groups", "Keep request IDs and statuses for diagnostics, but never log the Bearer token or complete sensitive resources", "Handle 400 invalidFilter/invalidValue, 401, 404, and 409 as SCIM errors, not Asgard Response envelopes"] },
    ],
  },
  {
    slug: "heimdall-siem", group: "Ecosystem", eyebrow: "HEIMDALL 5.3.19 · SECURITY OPERATIONS", title: "Security events and SIEM export", description: "Operate the released security-event queue, lifecycle, and cursor export with explicit delivery, retention, and data-governance boundaries.", sections: [
      { id: "event-and-authorization-boundary", title: "Event and authorization boundary", paragraphs: ["Heimdall records failed/locked login, federation and Passkey failures, authorization-code/refresh-token replay, session revocation, recovery-code activity, and external-group changes. Severity is low/medium/high/critical; manual events can move from open to acknowledged, closed, or dismissed. These events support identity security operations; they do not replace Asgard Trace, database logs, or business audit.", "GET /api/security-events/summary returns openIncidentCount, acknowledgedIncidentCount, and auditLast24HoursCount. Paging, summary, login-failure-trends, export, and disposition all require authentication plus platform.admin or platform.security.manage. export tenantId is an optional filter, not an authorization boundary: that platform principal can read cross-tenant events by default. Use a dedicated SIEM identity, short-lived access token, minimum platform permission, and controlled egress."] },
      { id: "policy-and-operator-queue", title: "Policy and operator queue", paragraphs: ["SecurityEventPolicy makes high, critical, and unknown event types manual; an explicit low/medium allowlist can be automatic. LoginLocked remains manual, while failed/locked login can receive a SHA-256 correlationKey without the raw login identifier. actionableOnly returns only manual open/acknowledged records.", "Only manual, non-archived events permit disposition. Notes remain in operations but are excluded from SIEM export. Analysts should acknowledge before investigation and then close/dismiss; there is no assignee, claim lease, or queue-owner field, so concurrent analysts still coordinate in an external case/SOAR system."] },
      { id: "pull-export-contract", title: "Pull-export contract", paragraphs: ["GET /api/security-events/export is synchronous read-only pull, not push delivery/outbox. format is json, ndjson, or cef (default ndjson); limit clamps to 1–1000; filters are tenantId, eventType, severity, occurredFrom, and occurredTo. Headers expose X-Heimdall-Event-Count, X-Heimdall-Has-More, and optional X-Heimdall-Next-Cursor.", "Heimdall stores no per-consumer checkpoint, acknowledgment, retry count, or dead letter. The collector owns durable cursors, backoff, alerting, and replay; an HTTP 200 does not mean the SIEM transaction committed."], code: { language: "http", value: siemRequestCode } },
      { id: "cursor-and-delivery-semantics", title: "Cursor and at-least-once delivery", paragraphs: ["The cursor encodes occurredAt ticks plus event ID but remains opaque to consumers. Results order by occurred_at then id, and continue after the cursor event is physically deleted. Persist next cursor only after the complete SIEM transaction commits. A crash after commit but before checkpoint replays the batch, so deduplicate by event id for at-least-once delivery.", "Saving cursor before commit loses data. Multiple workers sharing a checkpoint without external locking can overwrite order. Give each data stream one durable checkpoint owner, store filters/schemaVersion with it, and create a new stream when changing tenant/time/filter rather than reusing a cursor."], code: { language: "text", value: siemLoopCode } },
      { id: "schema-formats-and-compatibility", title: "Schema, formats, and compatibility", bullets: ["Version 5.3.19 JSON/NDJSON schemaVersion=1.1 includes id, UTC occurredAt, tenant/subject/client/session, eventType, severity, handlingMode, correlationKey, status, sourceIp, userAgent, details, disposedBy/disposedAt, and archivedAt", "JSON is an events envelope; NDJSON is one LF-terminated record per line; parse by schemaVersion and names, never property order", "CEF maps low=2, medium=5, high=8, critical=10, cs4=handlingMode, cs5=correlationKey; archivedAt is absent", "The current CEF header still hard-codes product version 4.1 even on Heimdall 5.3.19; do not treat it as deployment version—add that as collector metadata", "Invalid format, time range, or cursor is an application error; quarantine a bad checkpoint for operator recovery instead of tight-loop retry"] },
      { id: "redaction-and-data-governance", title: "Redaction and data governance", paragraphs: ["details recursively redacts fields whose names contain password, secret, token, credential, assertion, privatekey, or recoverycode; invalid JSON becomes {invalid:true}. This is a key-name defense, not content inspection: plain strings, unknown aliases, sourceIp, User-Agent, and identity/session IDs remain sensitive operations data.", "Avoid credentials and unrelated PII at event creation. Downstream, apply a field allowlist, encryption, access audit, residency, and retention. Do not grant complete SIEM and Trace-error-snapshot access to the same low-privilege role. Test redaction with synthetic canary secrets, never production credentials."] },
      { id: "lifecycle-and-retention", title: "Archive, retention, and export lag", paragraphs: ["SecurityEventLifecycleJob registers every 15 minutes with DisallowConcurrentExecution. Defaults are enabled, quiet 60 minutes, routine 30/resolved 180/high 365/critical 730 days, batch 1000, at most 20 batches/run, and dry_run support. Typed keys are security_event.lifecycle.* while Runtime Settings are security.event_lifecycle.*.", "Archive targets only automatic + identity.login.failed + low/medium + open. Physical deletion targets archived routine login failures or closed/dismissed manual events; open/acknowledged are retained, and other automatic types have no current archive/delete path. SIEM lag must stay below the shortest applicable retention or deleted events are unrecoverable even though the cursor advances. Start with dry_run and reconcile counts/oldest-exported time before deletion."] },
      { id: "aggregation-and-database-boundaries", title: "Aggregation and database boundaries", paragraphs: ["login-failure-trends groups fixed time buckets with correlationKey. aggregation_window_minutes affects that query and is passed into job options, but lifecycle quiet cutoff still evaluates each OccurredAt rather than correlation-group last activity. Do not claim a correlated incident whose quiet period extends with activity.", "Released 20260716_security_event_lifecycle.postgresql.sql adds lifecycle fields/indexes and historical backfill. PostgreSQL login protection uses atomic ProtectionKey UPSERT plus LockoutTriggeredAt; other providers retain a non-atomic read/modify/write boundary. Accept migration, indexes, and production-scale query plans separately before lifecycle/export."] },
      { id: "failure-recovery-and-acceptance", title: "Failure recovery and production acceptance", bullets: ["Replay from a fixed UTC start into an empty SIEM; reconcile count/has-more/cursor and prove repeated batches deduplicate without duplicate alerts", "Kill the collector before SIEM commit and after commit-before-checkpoint; prove no advance in the first case and safe replay in the second", "Create events with identical occurredAt and prove id ordering; delete/archive the cursor event and continue", "Inject 401/403, bad-cursor 400, 429, 5xx, timeout, and database failure; classify backoff and stop-alert on auth errors without losing checkpoint", "Compare Heimdall-window count, received count, deduplicated SIEM count, and checkpoint lag; give high/critical a separate latency SLO", "Across multiple Heimdall replicas prove identical cursor/filter ordering; Quartz DisallowConcurrentExecution is not proof of a cross-node lifecycle singleton", "Rollback collectors with old parser/checkpoint retained; before Heimdall rollback prove schemaVersion/query compatibility and never truncate events or reset cursor"] },
      { id: "release-boundaries", title: "Release and unproven boundaries", paragraphs: ["The lifecycle job/config, policy/summary/actionable queue, trend aggregation, JSON/NDJSON/CEF 1.1 export, stable cursor, recursive redaction, retention SQL, and related contract tests first shipped in 5.1.2 and remain present in clean v5.3.19 at 0032070.", "Unproven/unshipped: push connector, Kafka/Syslog/Webhook delivery, consumer registry/checkpoint, exactly-once, server retry/dead letter, assignee/claim lease, distributed cross-node lifecycle lock, an accurate 5.3.19 CEF version, general content DLP, atomic login protection on every provider, or production-scale SIEM end-to-end acceptance."] },
    ],
  },
];
