import type { DocPage } from "./content";

const resourceApiYaml = [
  "host:",
  "  auth:",
  "    enabled: true",
  "    jwt:",
  "      issuerTemplate: \"https://id.example.com/{tenant}/\"",
  "      audience: \"orders-api\"",
  "      requireHttpsMetadata: true",
  "      discoveryCacheMinutes: 60",
  "      jwksCacheMinutes: 15",
  "  cors:",
  "    enabled: true",
  "    defaultPolicy:",
  "      allowAnyOrigin: false",
  "      allowedOrigins:",
  "        - \"https://app.example.com\"",
  "      allowAnyMethod: true",
  "      allowAnyHeader: true",
  "      allowCredentials: false",
].join("\n");

const tenantScopeRequest = [
  "POST /api/TenantOidcScope",
  "Authorization: Bearer <heimdall-admin-access-token>",
  "Content-Type: application/json",
  "",
  "{",
  "  \"tenantId\": \"7c80e227-ec0d-40bf-9909-e6f8e75ba6bf\",",
  "  \"name\": \"orders.api\",",
  "  \"displayName\": \"Orders API\",",
  "  \"description\": \"Call the Orders resource API\",",
  "  \"resources\": \"orders-api\",",
  "  \"claims\": \"roles,permissions\",",
  "  \"required\": false,",
  "  \"isSystem\": false,",
  "  \"status\": 1",
  "}",
].join("\n");

const spaClientRequest = [
  "POST /api/TenantOidcClient",
  "Authorization: Bearer <heimdall-admin-access-token>",
  "Content-Type: application/json",
  "",
  "{",
  "  \"tenantId\": \"7c80e227-ec0d-40bf-9909-e6f8e75ba6bf\",",
  "  \"clientName\": \"Orders Web\",",
  "  \"applicationType\": \"web\",",
  "  \"clientType\": \"public\",",
  "  \"grantTypes\": \"authorization_code,refresh_token\",",
  "  \"redirectUris\": \"https://app.example.com/callback\",",
  "  \"postLogoutRedirectUris\": \"https://app.example.com/logout-complete\",",
  "  \"allowedCorsOrigins\": \"https://app.example.com\",",
  "  \"scopes\": \"openid,profile,email,offline_access,orders.api\",",
  "  \"defaultScopes\": \"openid,profile,orders.api\",",
  "  \"responseTypes\": \"code\",",
  "  \"responseModes\": \"query\",",
  "  \"tokenEndpointAuthMethods\": \"none\",",
  "  \"requirePkce\": true,",
  "  \"allowOfflineAccess\": true,",
  "  \"allowAccessTokensViaBrowser\": false,",
  "  \"accessTokenFormat\": \"jwt\",",
  "  \"requireNonce\": true,",
  "  \"status\": 1",
  "}",
].join("\n");

const spaOidcCode = [
  "import { UserManager } from \"oidc-client-ts\";",
  "",
  "export const userManager = new UserManager({",
  "  authority: \"https://id.example.com/7c80e227-ec0d-40bf-9909-e6f8e75ba6bf\",",
  "  client_id: \"<client-id-returned-by-heimdall>\",",
  "  redirect_uri: \"https://app.example.com/callback\",",
  "  post_logout_redirect_uri: \"https://app.example.com/logout-complete\",",
  "  response_type: \"code\",",
  "  scope: \"openid profile email offline_access orders.api\",",
  "  automaticSilentRenew: true,",
  "});",
  "",
  "export async function callOrdersApi() {",
  "  const user = await userManager.getUser();",
  "  if (!user || user.expired) {",
  "    await userManager.signinRedirect();",
  "    return;",
  "  }",
  "",
  "  return fetch(\"https://api.example.com/api/orders/whoami\", {",
  "    headers: { Authorization: \"Bearer \" + user.access_token },",
  "  });",
  "}",
].join("\n");

const callbackCode = [
  "// /callback",
  "await userManager.signinRedirectCallback();",
  "window.location.replace(\"/\");",
  "",
  "// Sign out through Heimdall and return to the registered URI.",
  "await userManager.signoutRedirect();",
].join("\n");

const controllerCode = [
  "using Asgard.Abstractions;",
  "using Asgard.Abstractions.AspNetCore.Authorization;",
  "using Asgard.Abstractions.AspNetCore.Controller;",
  "using Asgard.Abstractions.AspNetCore.Model;",
  "using Microsoft.AspNetCore.Mvc;",
  "",
  "namespace Orders.Api.Controllers;",
  "",
  "[Route(\"api/tenants/{tenantId:guid}/orders\")]",
  "public sealed class TenantOrdersController(AbsAsgardContext asgardContext)",
  "    : BaseController(asgardContext)",
  "{",
  "    [HttpGet]",
  "    [AsgardAuthMatch(",
  "        \"token_type = 'UserLogin' and permission = 'orders.read'\")]",
  "    public ActionResult<Response<object>> Get(Guid tenantId)",
  "    {",
  "        var identity = AsgardContext.IdentityContext",
  "            ?? throw new InvalidOperationException(\"Identity is unavailable.\");",
  "        var currentTenantId = identity.GetCurrentTenantId();",
  "",
  "        if (tenantId != currentTenantId)",
  "        {",
  "            return Fail<object>(403, \"Cross-tenant access is forbidden.\");",
  "        }",
  "",
  "        return Success<object>(new",
  "        {",
  "            currentTenantId,",
  "            identity.TokenType,",
  "            identity.UserInfo?.Sub,",
  "            identity.UserInfo?.UserId,",
  "            identity.UserInfo?.Permissions,",
  "            identity.UserInfo?.Scope",
  "        });",
  "    }",
  "}",
].join("\n");

const verifyCode = [
  "curl.exe https://id.example.com/<tenant-id>/.well-known/openid-configuration",
  "curl.exe https://id.example.com/<tenant-id>/.well-known/jwks",
  "",
  "# Send the access token, never the ID token.",
  "curl.exe https://api.example.com/api/tenants/<tenant-id>/orders \\",
  "  -H \"Authorization: Bearer <access-token>\"",
].join("\n");

export const zhAsgardIntegrationDocs: DocPage[] = [{
  slug: "resource-api-authentication",
  group: "身份与安全",
  eyebrow: "OIDC RESOURCE API",
  title: "验证 Heimdall Access Token",
  description: "把 Heimdall 租户 Authority、API audience、JWT 验签、Asgard 身份快照和接口授权接成一条可验收链路。",
  relatedDocs: [{ product: "heimdall", docSlug: "heimdall-integration", label: "在 Heimdall 注册 SPA 与 API Scope" }],
  sections: [
    { id: "topology", title: "先分清四个角色", bullets: ["Heimdall：授权服务器，登录用户并签发 Access Token", "浏览器 SPA：public client，使用 Authorization Code + PKCE", "Asgard API：资源服务器，只接受为自身 audience 签发且校验通过的 Bearer Token", "AsgardAuth 判断角色、权限、scope 与 token_type；Service 继续校验租户和资源归属"], note: "ID Token 证明用户在客户端完成登录，不是 API 凭据。调用 API 必须发送 Access Token。" },
    { id: "audience", title: "在 Heimdall 建立 API audience", paragraphs: ["为租户创建自定义 scope，并把 Resources 设置为 API 所期望的 audience。Heimdall 根据申请到的 scope 解析资源并写入 access token 的 aud；没有资源时回退到 client_id。"], code: { language: "http", value: tenantScopeRequest }, note: "openid、profile、email、offline_access 等内置 scope 不会自动产生 API audience。客户端还必须被允许并实际申请 orders.api。" },
    { id: "host-auth", title: "让 Asgard 宿主管理 JWT 验签", paragraphs: ["host.auth.enabled=true 注册默认 JWT Bearer。issuerTemplate 是 issuer 允许列表，不是路由提示，必须且只能含一个 {tenant}；audience 与 Heimdall scope Resources 区分大小写地精确匹配。"], code: { language: "yaml", value: resourceApiYaml }, note: "当前 5.1.3 内置验证器只覆盖租户 issuer。无占位符的平台 issuer https://id.example.com、平台+租户混合验证或 opaque token 都需要外部认证方案，不能宣称 host.auth 已覆盖。" },
    { id: "jwt-boundary", title: "JWT 进入 API 后发生什么", bullets: ["严格校验 issuer、audience、签名、有效期和 signed-token；ClockSkew 为零", "issuer 先匹配模板，之后才读取该租户的 Discovery 与 JWKS，并按 kid 选密钥", "完全缺少 tenant_id 时从 issuer 补入；已有空值或冲突值不会被修复或核对", "UserLogin 至少需要 sub、user_id；BackendService 需要 sub、client_id、token_type 且禁止 user_id", "UseAsgardTenant 在认证后建立 AsgardIdentitySnapshot，业务读取 AsgardContext.IdentityContext"] },
    { id: "authorize", title: "在 Controller 授权并守住租户", paragraphs: ["AsgardAuth 特性继承 AuthorizeAttribute。它只判断调用资格；路由、请求体和资源的 tenantId 仍必须与当前快照显式比较。真实业务继续遵循 Controller → Service → Repository → Entity。"], code: { language: "csharp", value: controllerCode } },
    { id: "smoke", title: "按 200 / 401 / 403 验收", paragraphs: ["先确认租户 Discovery 的 issuer 与 Token iss 相同，JWKS 含 Token header 的 kid，再携带 Access Token 调用 API。"], code: { language: "powershell", value: verifyCode }, bullets: ["200：签名、iss、aud、有效期、Token profile 与 AsgardAuth 全部通过", "401：无 Token，或签名/iss/aud/exp/kid/Discovery/JWKS/必填 claim 失败；前端最多续期一次", "403：认证成功但权限、scope、token_type 或资源租户归属不满足；不要循环刷新"] },
    { id: "revocation", title: "撤销与当前边界", bullets: ["host.auth 只验证 JWT；opaque access token 必须另接 introspection", "一个宿主当前只有一个全局 audience；多个资源 audience 需要拆分宿主或自定义验证器", "本地 JWT+JWKS 验证不会每次回查 Heimdall token 数据库或黑名单，logout/revoke 后旧 Token 仍可能有效到 exp", "identity.subject.invalidated Webhook 由 Heimdall 5.1.2 引入，并已在 clean 5.3.19 重新核对保留；只有下游验签、幂等消费并维护 revoked_at 水位后，才能用它拒绝旧 JWT，否则仍依赖短 Access Token TTL", "API host.cors 管 /api/**；Heimdall allowedCorsOrigins 只管浏览器协议端点，两边分别配置"] },
  ],
}];

export const enAsgardIntegrationDocs: DocPage[] = [{
  slug: "resource-api-authentication",
  group: "Identity & Security",
  eyebrow: "OIDC RESOURCE API",
  title: "Validate Heimdall access tokens",
  description: "Connect a Heimdall tenant authority, API audience, JWT validation, Asgard identity snapshot, and endpoint authorization into one testable path.",
  relatedDocs: [{ product: "heimdall", docSlug: "heimdall-integration", label: "Register the SPA and API scope in Heimdall" }],
  sections: [
    { id: "topology", title: "Separate the four roles", bullets: ["Heimdall is the authorization server that issues access tokens", "A browser SPA is a public client using Authorization Code + PKCE", "The Asgard API is the resource server and accepts only Bearer tokens issued for its audience", "AsgardAuth qualifies roles, permissions, scopes, and token_type; the service still enforces tenant and resource ownership"], note: "An ID token proves sign-in to the client. It is not an API credential; send the access token to the API." },
    { id: "audience", title: "Create the API audience in Heimdall", paragraphs: ["Create a tenant custom scope whose Resources value is the API audience. Heimdall resolves resources from granted scopes and writes them to access-token aud; without resources it falls back to client_id."], code: { language: "http", value: tenantScopeRequest }, note: "Built-in openid, profile, email, and offline_access scopes do not create an API audience. The client must be allowed to request orders.api and actually request it." },
    { id: "host-auth", title: "Let the Asgard host validate JWTs", paragraphs: ["host.auth.enabled=true registers JWT Bearer. issuerTemplate is an issuer allow-list, not a routing hint, and must contain exactly one {tenant}. audience is an ordinal, case-sensitive exact match for one Heimdall scope Resource."], code: { language: "yaml", value: resourceApiYaml }, note: "The 5.1.3 built-in validator covers tenant issuers only. The placeholder-free platform issuer https://id.example.com, mixed platform+tenant validation, and opaque tokens require an external authentication scheme." },
    { id: "jwt-boundary", title: "What happens when a JWT enters the API", bullets: ["Issuer, audience, signature, lifetime, and signed-token requirements are validated with zero ClockSkew", "The issuer must match before tenant Discovery and JWKS are loaded; kid selects the key", "A completely missing tenant_id is inferred from issuer; an existing empty or conflicting value is neither repaired nor reconciled", "UserLogin requires sub and user_id; BackendService requires sub, client_id, and token_type and forbids user_id", "UseAsgardTenant builds AsgardIdentitySnapshot after authentication; business code reads AsgardContext.IdentityContext"] },
    { id: "authorize", title: "Authorize and enforce tenant ownership", paragraphs: ["AsgardAuth attributes inherit AuthorizeAttribute. They qualify the caller but do not replace a route/body/resource tenant comparison. Production code still follows Controller → Service → Repository → Entity."], code: { language: "csharp", value: controllerCode } },
    { id: "smoke", title: "Verify 200, 401, and 403", paragraphs: ["Confirm tenant Discovery issuer equals token iss and JWKS contains the token header kid, then call the API with the access token."], code: { language: "powershell", value: verifyCode }, bullets: ["200: signature, iss, aud, lifetime, token profile, and AsgardAuth passed", "401: token missing or signature/iss/aud/exp/kid/Discovery/JWKS/required claims failed; renew and retry at most once", "403: authentication passed but permission, scope, token_type, or tenant ownership failed; do not enter a renewal loop"] },
    { id: "revocation", title: "Revocation and current boundaries", bullets: ["host.auth validates JWTs only; opaque access tokens require introspection", "One host currently configures one global audience; split hosts or add a custom validator for multiple resource audiences", "Local JWT+JWKS validation does not query Heimdall's token database or blacklist per request, so a logged-out or revoked JWT may remain valid until exp", "Heimdall 5.1.2 introduced the identity.subject.invalidated Webhook and clean 5.3.19 re-verification confirms it remains present. Only a downstream that verifies, deduplicates, and maintains a revoked_at watermark can use it to reject old JWTs; otherwise keep access tokens short-lived", "API host.cors governs /api/** while Heimdall allowedCorsOrigins governs browser protocol endpoints; configure both"] },
  ],
}];

export const zhHeimdallIntegrationDocs: DocPage[] = [{
  slug: "heimdall-integration",
  group: "接入",
  eyebrow: "OIDC INTEGRATION",
  title: "接入 Heimdall",
  description: "注册租户 SPA，走 Authorization Code + PKCE，并把正确 audience 的 Access Token 交给 Asgard API。",
  relatedDocs: [{ product: "asgard", docSlug: "resource-api-authentication", label: "让 Asgard API 验证 Access Token" }],
  sections: [
    { id: "authority", title: "先选择 Authority", bullets: ["平台：https://id.example.com；Discovery 在 /.well-known/openid-configuration", "租户：https://id.example.com/{tenantId}；Discovery 在 /{tenantId}/.well-known/openid-configuration", "租户业务用户和多租户 API 使用租户 Authority；客户端租户、登录身份租户和路由租户必须一致"], note: "生产必须把 oidc.issuer 固定为反向代理后的 HTTPS 基础地址；不要靠前端请求头切换租户。" },
    { id: "audience", title: "先注册 API Scope", paragraphs: ["自定义 scope 的 Resources 决定 Access Token 的 aud。下面把 orders.api 映射为 orders-api；Asgard API 的 host.auth.jwt.audience 必须使用同一个值。"], code: { language: "http", value: tenantScopeRequest } },
    { id: "client", title: "注册 SPA public client", paragraphs: ["管理 API 会生成 client_id。SPA 无 Client Secret，令牌端点认证方法只能是 none，authorization_code 必须启用 PKCE S256，前通道 Access Token 被禁用。"], code: { language: "http", value: spaClientRequest }, note: "redirectUris、postLogoutRedirectUris 和 allowedCorsOrigins 是不同字段。Origin 只能含 scheme、host、port，不能带路径、查询或片段。" },
    { id: "pkce", title: "登录并调用 API", paragraphs: ["读取租户 Discovery，让成熟客户端处理 state、nonce、code_verifier、回调和续期。只把 access_token 放进业务 API 的 Authorization header；用户 Access Token 当前不保证包含 client_id。"], code: { language: "typescript", value: spaOidcCode } },
    { id: "callback", title: "完成回调与退出", paragraphs: ["回调 URI 必须精确匹配登记值。兑换授权码后清理回调参数；退出使用 Discovery 的 end_session_endpoint，post_logout_redirect_uri 也必须精确登记。"], code: { language: "typescript", value: callbackCode } },
    { id: "userinfo", title: "UserInfo 不是完整身份快照", bullets: ["/userinfo 返回 sub，并按 scope 返回 name、email、phone；租户路由还可返回 tenant_id", "它不返回 roles、permissions、userMetadatas 或 tenantMetadata", "Asgard API 从已验证的 Access Token claims 还原身份；完整当前用户详情应由独立业务 API 提供"] },
    { id: "cors", title: "配置两个 CORS 边界", bullets: ["Heimdall allowedCorsOrigins 允许 SPA 调 Token、UserInfo、Revoke、Device Authorization、Discovery 与 JWKS", "Asgard host.cors.defaultPolicy.allowedOrigins 允许 SPA 调业务 /api/**", "introspection 与 SCIM 不是浏览器 CORS 端点；配好一边不会自动修复另一边"] },
    { id: "refresh", title: "续期与错误处理", bullets: ["refresh token 仅在用户申请 offline_access、客户端允许 offline access 且启用 refresh_token grant 时签发", "刷新时 scope 可省略或缩小，不能扩大；updateAccessTokenClaimsOnRefresh 当前未接线，不能宣传会自动重载权限", "401 最多续期并重试一次；403 展示权限不足，不刷新循环", "只做 JWKS 本地验证的外部 API 不会立即感知 Heimdall logout/revoke"] },
    { id: "api", title: "对接 Asgard 资源 API", paragraphs: ["Asgard 产品站的“验证 Heimdall Access Token”给出 tenant issuer 模板、orders-api audience、Controller 和 200/401/403 验收。客户端必须使用 JWT accessTokenFormat；opaque token 需要 introspection。"] },
  ],
}];

export const enHeimdallIntegrationDocs: DocPage[] = [{
  slug: "heimdall-integration",
  group: "Integration",
  eyebrow: "OIDC INTEGRATION",
  title: "Integrate Heimdall",
  description: "Register a tenant SPA, use Authorization Code + PKCE, and hand an access token with the correct audience to an Asgard API.",
  relatedDocs: [{ product: "asgard", docSlug: "resource-api-authentication", label: "Validate the access token in an Asgard API" }],
  sections: [
    { id: "authority", title: "Choose the authority first", bullets: ["Platform: https://id.example.com with Discovery at /.well-known/openid-configuration", "Tenant: https://id.example.com/{tenantId} with Discovery at /{tenantId}/.well-known/openid-configuration", "Use tenant Authority for tenant users and APIs; client tenant, login tenant, and route tenant must match"], note: "Set oidc.issuer to the stable public HTTPS base address behind the proxy. Never switch tenancy with a frontend header." },
    { id: "audience", title: "Register the API scope first", paragraphs: ["A custom scope Resources value determines access-token aud. This maps orders.api to orders-api; the Asgard API host.auth.jwt.audience must use the same value."], code: { language: "http", value: tenantScopeRequest } },
    { id: "client", title: "Register the SPA public client", paragraphs: ["The management API generates client_id. A SPA has no client secret, token endpoint authentication must be none, authorization_code requires PKCE S256, and front-channel access tokens are disabled."], code: { language: "http", value: spaClientRequest }, note: "redirectUris, postLogoutRedirectUris, and allowedCorsOrigins are different fields. An Origin contains only scheme, host, and port—never path, query, or fragment." },
    { id: "pkce", title: "Sign in and call the API", paragraphs: ["Load tenant Discovery and let a mature client handle state, nonce, code_verifier, callback, and renewal. Put only access_token in the business API Authorization header. A user access token currently does not guarantee client_id."], code: { language: "typescript", value: spaOidcCode } },
    { id: "callback", title: "Complete callback and sign-out", paragraphs: ["The callback URI must exactly match registration. Remove callback parameters after redeeming the code. Sign out through the discovered end_session_endpoint; post_logout_redirect_uri must also be registered exactly."], code: { language: "typescript", value: callbackCode } },
    { id: "userinfo", title: "UserInfo is not the full identity snapshot", bullets: ["/userinfo returns sub and scope-dependent name, email, and phone; a tenant route can also return tenant_id", "It does not return roles, permissions, userMetadatas, or tenantMetadata", "The Asgard API restores identity from validated access-token claims; expose a separate business API for complete current-user details"] },
    { id: "cors", title: "Configure two CORS boundaries", bullets: ["Heimdall allowedCorsOrigins lets the SPA call Token, UserInfo, Revoke, Device Authorization, Discovery, and JWKS", "Asgard host.cors.defaultPolicy.allowedOrigins lets it call business /api/** routes", "Introspection and SCIM are not browser CORS endpoints. Correcting one boundary does not correct the other"] },
    { id: "refresh", title: "Renewal and error handling", bullets: ["A refresh token requires a user, offline_access, allowed offline access, and refresh_token grant", "Refresh scope may be omitted or narrowed, never expanded. updateAccessTokenClaimsOnRefresh is not wired today, so do not promise permission reload", "Renew and replay a 401 at most once; show a 403 without a renewal loop", "An external API doing local JWKS validation does not immediately observe Heimdall logout/revoke"] },
    { id: "api", title: "Connect the Asgard resource API", paragraphs: ["The Asgard product site's “Validate Heimdall access tokens” guide provides the tenant issuer template, orders-api audience, controller, and 200/401/403 checks. The client must use JWT accessTokenFormat; opaque tokens require introspection."] },
  ],
}];
