import type { DocPage } from "./content";

const hostLifecycleCode = `var host = YggdrasilHost.CreateBuilder("config/app.yaml")
    .BeforeConfigurationLoad(builder => { /* add a trusted config source */ })
    .AfterConfigurationLoad((builder, configuration) => { /* inspect merged config */ })
    .BeforeServiceRegistration(services => { /* register overrides */ })
    .AfterServiceRegistration(services => { /* register application services */ })
    .ConfigureMiddleware(app => { /* enrich identity before authorization */ })
    .AfterHostBuild(builtHost => { /* final host-only adjustment */ })
    .UseBuiltInPlugin<MyPlugin>()
    .Build();

await host.RunAsync();`;

const middlewarePipeline = `UseAsgardStaticFiles
UseAsgardRequestTracing
UseRouting
UseCors                         # when host.cors.enabled
UseRateLimiter                  # when host.rateLimiting.enabled
UseAuthentication              # when host.auth.enabled
UseAsgardTenant
Host ConfigureMiddleware hook
Plugin ConfigureMiddlewareAsync hooks
UseAuthorization               # always
UseSwagger / UseSwaggerUI      # when enabled
MapHealthChecks
MapTsGenerationEndpoint        # Development + enabled
MapControllers`;

const healthRateYaml = `host:
  rateLimiting:
    enabled: true
    policy: SlidingWindow       # FixedWindow | SlidingWindow | TokenBucket
    permitLimit: 100
    windowSeconds: 60
    segmentsPerWindow: 10
    queueLimit: 0

  healthCheck:
    enabled: true
    path: /health
    readyPath: /health/ready
    livePath: /health/live
    timeoutSeconds: 30`;

const tokenBucketYaml = `host:
  rateLimiting:
    enabled: true
    policy: TokenBucket
    permitLimit: 1          # still validated in 5.1.3
    windowSeconds: 1       # still validated in 5.1.3
    segmentsPerWindow: 1   # still validated in 5.1.3
    tokenLimit: 200
    tokensPerSecond: 20
    queueLimit: 0`;

const readinessRegistrationCode = `var builder = YggdrasilHost.CreateBuilder("config/app.yaml")
    .AfterServiceRegistration(services =>
    {
        _ = services.AddHealthChecks()
            .AddCheck<PostgresReadinessCheck>("postgres", tags: ["ready"])
            .AddCheck<RedisReadinessCheck>("redis", tags: ["ready"]);
    });

var app = builder.Build();
await app.RunAsync();`;

const healthRateAcceptance = `# Health semantics: dependency failure must affect ready, not live.
curl --fail http://127.0.0.1:8080/health/live
curl --fail http://127.0.0.1:8080/health/ready

# Capture status, headers, and body around the configured threshold.
curl --include http://127.0.0.1:8080/api/ping

# Repeat from each replica/network path. Static assets are a separate bypass path.
curl --include http://127.0.0.1:8080/assets/app.js`;

const pluginLifecycleCode = `public sealed class OrdersPlugin : PluginBase
{
    public override string Id => "orders";
    public override string Name => "Orders";
    public override Version Version => new(1, 0, 0);

    protected override Task OnConfigureServicesAsync(
        IPluginServiceConfigurationContext context,
        CancellationToken cancellationToken)
    {
        _ = context.Services.AddScoped<IOrderService, OrderService>();
        return Task.CompletedTask;
    }

    protected override Task OnInitializeAsync(CancellationToken cancellationToken)
    {
        var logger = CreateLogger();
        logger.LogInformation("订单插件初始化完成");
        return Task.CompletedTask;
    }

    protected override Task OnConfigureMiddlewareAsync(
        IPluginMiddlewareConfigurationContext context,
        CancellationToken cancellationToken)
    {
        if (context.App is IEndpointRouteBuilder endpoints)
        {
            _ = endpoints.MapFallback("/orders/{**path}", static () => Results.NotFound());
        }

        return Task.CompletedTask;
    }
}`;

const pluginAcceptance = `BASE_URL="http://127.0.0.1:8080"

# Critical plugin endpoint and its authorization contract.
curl --fail --show-error "$BASE_URL/orders/health"
curl --include "$BASE_URL/orders/admin"

# Capture the exact startup evidence for this release.
# Require: "Plugin system ready (N running)" and one plugin-owned ready check.

# Graceful stop: remove traffic first, then send the normal process stop signal.
# Verify background work stopped and the plugin's final marker was emitted.`;

const databaseBootstrapYaml = `oidc:
  bootstrap:
    auto_sync_schema: true  # controlled empty-database bootstrap only`;

const databaseProductionYaml = `oidc:
  bootstrap:
    auto_sync_schema: false # production after reviewed schema creation/migration`;

const migrationCommand = `psql "$HEIMDALL_POSTGRES_DSN" -X -v ON_ERROR_STOP=1 \\
  --single-transaction \\
  -f be/Database/Migrations/<reviewed-migration>.postgresql.sql`;

const migrationVerificationSql = `SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;

SELECT column_name, data_type, datetime_precision
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name IN ('tenant_profile', 'tenant_oauth2_client_info')
ORDER BY table_name, ordinal_position;`;

const reverseProxyIssuerYaml = `oidc:
  issuer: "https://id.example.com"`;

const nginxProxyCode = `# Operator-selected timeout values: accept them against real flows.
location / {
    proxy_pass http://heimdall:5000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Prefix "";

    proxy_connect_timeout 5s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
}

# Streamable HTTP MCP is not a WebSocket endpoint.
location = /mcp {
    proxy_pass http://heimdall:5000;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
}`;

const clientCredentialsBasic = `curl --request POST \\
  --url https://id.example.com/acme/connect/token \\
  --user "$CLIENT_ID:$CLIENT_SECRET" \\
  --header "Content-Type: application/x-www-form-urlencoded" \\
  --data-urlencode "grant_type=client_credentials" \\
  --data-urlencode "scope=orders.read orders.write"`;

const clientCredentialsPost = `curl --request POST \\
  --url https://id.example.com/acme/connect/token \\
  --header "Content-Type: application/x-www-form-urlencoded" \\
  --data-urlencode "grant_type=client_credentials" \\
  --data-urlencode "client_id=$CLIENT_ID" \\
  --data-urlencode "client_secret=$CLIENT_SECRET" \\
  --data-urlencode "scope=orders.read"`;

const keyGenerateCode = `curl --request POST \\
  --url https://id.example.com/api/TenantOidcKey/generate \\
  --header "Authorization: Bearer $ADMIN_TOKEN" \\
  --header "Content-Type: application/json" \\
  --data '{"tenantId":"acme","keySize":3072}'`;

const keyActivateCode = `curl --request POST \\
  --url "https://id.example.com/api/TenantOidcKey/$KEY_ID/activate" \\
  --header "Authorization: Bearer $ADMIN_TOKEN" \\
  --header "Content-Type: application/json" \\
  --data '{"activateAt":"2026-07-16T12:00:00Z","retentionDays":30}'`;

export const zhAsgardLifecycleDocs: DocPage[] = [
  {
    slug: "host-lifecycle", group: "宿主运行时", eyebrow: "BUILD PHASES", title: "宿主构建生命周期", description: "把配置、基础设施、服务、插件与 Web 管线放进正确的 Yggdrasil 构建阶段。", sections: [
      { id: "phases", title: "五阶段构建事实", bullets: ["Phase 1：合并 app.yaml、环境文件、环境变量与命令行配置", "Phase 2：加载并校验 Host、Logging、Trace、Cache、Database、MQ、Job 与 Plugin 配置", "Phase 3：同步初始化启用的 Trace、Cache、MQ 与 Job 管理器", "Phase 4：注册框架、数据库、安全、MVC、插件、健康检查、限流与宿主服务", "Phase 5：构建容器，初始化并启动插件，配置中间件，然后返回 WebApplication"] },
      { id: "hooks", title: "钩子应该放什么", paragraphs: ["BeforeConfigurationLoad 用于观察或增加 ASP.NET 配置源；AfterConfigurationLoad 读取合并视图。Asgard 强类型模块配置来自框架自己的配置图，不能假设在 hook 中追加 provider 会覆盖它。BeforeServiceRegistration 的注册仍可能被框架后续同类型注册覆盖；AfterServiceRegistration 更适合补应用服务，但 Swagger 仍在该 hook 之后注册。ConfigureMiddleware 固定位于租户上下文之后、授权之前；AfterHostBuild 是管线和插件已就绪、监听尚未开始的最后宿主钩子。", "每种 hook 只保存一个 delegate；重复调用会替换前一次，而不是累加。需要多个动作时放进同一个回调。"], code: { language: "csharp", value: hostLifecycleCode } },
      { id: "build", title: "Build 不只是构建容器", paragraphs: ["CreateBuilder 构造阶段已经直接读取基础 app.yaml、校验 HostConfig/LogConfig 并创建引导日志，所以基础文件必须独立合法，不能指望环境覆盖稍后补救。当前 Build() 会同步初始化基础设施，并初始化、启动插件；这些动作发生在 RunAsync 之前。配置错误、服务注册失败或插件依赖图错误会阻止构建。不要把可能无限等待的网络工作放进构建钩子。"] },
      { id: "availability", title: "能力可用时间", bullets: ["服务注册期间只有 IServiceCollection，不能解析最终 ServiceProvider", "插件 InitializeAsync 起才可使用 GetService、CreateLogger 与 GetAsgardContext", "JobManager 在 WebApplication 构建后获得最终 ServiceProvider", "插件中间件在插件已经完成 Initialize/Start 后接入管线"] },
      { id: "shutdown", title: "停机边界", paragraphs: ["宿主停止时 AsgardRuntimeHostedService 先关闭已启动的作业调度器，再释放 PluginManager。插件管理器负责 Stop、Dispose 与逻辑卸载；应用自己的后台工作仍必须响应 CancellationToken 并可重复清理。"] },
    ],
  },
  {
    slug: "middleware-pipeline", group: "宿主运行时", eyebrow: "REQUEST PIPELINE", title: "精确中间件顺序", description: "理解请求追踪、路由、认证、租户、插件扩展和授权的真实先后关系。", sections: [
      { id: "order", title: "Asgard 5.1.3 默认顺序", code: { language: "text", value: middlewarePipeline }, note: "这是当前 YggdrasilHostBuilder.Configurator 的执行顺序，不是可以任意调换的示意图。" },
      { id: "identity", title: "认证、租户与授权", paragraphs: ["UseAuthentication 只在 host.auth.enabled=true 时由宿主接入。UseAsgardTenant 始终位于认证之后；宿主和插件扩展点随后可以补充主体或声明；UseAuthorization 最后统一执行，即使宿主默认 JWT 已关闭也不会消失。"] },
      { id: "extensions", title: "扩展点边界", bullets: ["静态文件位于最前且可短路：静态响应不进入 Trace、CORS、限流、认证、租户或授权", "宿主 ConfigureMiddleware 回调先于插件中间件", "两个扩展点都在 Tenant 之后；auth=false 后才在这里添加自定义认证，可能来不及建立正确租户快照", "插件只映射端点时使用 IEndpointRouteBuilder.Map...", "插件不要调用 UseEndpoints；它会在授权中间件之前提前执行端点", "完全旁路 Yggdrasil 默认管线时，调用方才需要自行复刻认证授权顺序"] },
      { id: "routing", title: "为什么先 UseRouting", paragraphs: ["终结点元数据必须先解析，认证与授权才能读取 [Authorize]、AsgardAuth 和端点策略。把认证、租户或授权放到 UseRouting 前后错误的位置，会造成身份缺失或授权中间件缺失异常。"] },
      { id: "verify", title: "变更后的验证", bullets: ["未认证请求命中受保护端点返回 401", "已认证但权限不足返回 403", "tenant_id 能恢复正确租户上下文", "CORS 预检不被认证误拦截", "插件映射端点上的 Authorize/AsgardAuth 元数据确实执行", "Trace、Swagger、健康检查与控制器路由仍可访问"] },
    ],
  },
  {
    slug: "health-and-rate-limiting", group: "宿主运行时", eyebrow: "OPERATIONS", title: "健康检查与全局限流", description: "配置存活、就绪端点与三种全局限流器，并理解当前运行时边界。", sections: [
      { id: "config", title: "完整配置与节点语义", paragraphs: ["healthCheck 与 rateLimiting 都是可空节点：完全省略即不注册、不映射；节点存在且省略 enabled 时默认启用。路径、策略与数值即使 enabled=false 仍会在模块加载阶段校验，因此禁用的残缺节点也可能阻止启动。"], code: { language: "yaml", value: healthRateYaml } },
      { id: "health-semantics", title: "把 live、ready 与全量检查分开", bullets: ["path 默认 /health，运行全部注册检查", "readyPath 默认 /health/ready，只运行带 ready tag 的检查", "livePath 默认 /health/live，只运行带 live tag 的检查", "内建 self 同时带 live 与 ready，但只返回 Healthy，不能证明 PostgreSQL、Redis、RabbitMQ 或下游可用", "路径重复时按 path → readyPath → livePath 顺序只映射第一个；不要依赖冲突路径表达多个语义"] },
      { id: "dependency-checks", title: "显式注册依赖就绪检查", paragraphs: ["通过 AfterServiceRegistration 追加带 ready tag 的检查；live 保持进程级，避免依赖短暂故障触发编排器反复杀进程。检查必须使用轻量、只读、可取消的真实操作，并分别命名，不能用一次业务写入当探针。", "host.healthCheck.timeoutSeconds 当前只校验正数，没有传给 MapHealthChecks 或 HealthCheckRegistration。每个依赖检查必须自己实现明确超时并尊重 CancellationToken；不要把配置的 30 秒当成执行上限。"], code: { language: "csharp", value: readinessRegistrationCode } },
      { id: "health-surface", title: "健康端点也是公开动态请求", paragraphs: ["MapHealthChecks 使用 ASP.NET Core 默认响应，不提供 Asgard Response 包装、依赖明细 JSON 或内建授权。端点映射在全局限流中间件之后，因此会与其他动态请求争用同一个 limiter；不要让业务洪峰把编排器探针饿死。静态文件位于限流之前并可短路，不受该 limiter 保护。"], note: "若平台需要不受业务限流影响的探针，应在网关/编排网络隔离，或实现并验证自定义管线；5.1.3 配置面没有 endpoint exclusion。" },
      { id: "rate-policies", title: "三种策略与验证陷阱", bullets: ["FixedWindow 使用 permitLimit + windowSeconds", "SlidingWindow 额外使用 segmentsPerWindow", "TokenBucket 使用 tokenLimit，每秒补充 tokensPerSecond，AutoReplenishment=true", "策略字符串严格区分大小写", "TokenBucket 运行时不用 permitLimit/windowSeconds/segmentsPerWindow，但 Validate 仍要求三者全部为正数", "queueLimit 默认为 0；大于 0 时三种策略都按 OldestFirst 排队"] , code: { language: "yaml", value: tokenBucketYaml } },
      { id: "global-partition", title: "global 是一个进程一个桶", paragraphs: ["PartitionedRateLimiter 对所有进入 UseRateLimiter 的请求固定使用 key=global：没有按 IP、tenant_id、用户、client_id、路由或 HTTP method 分区。认证又位于 limiter 之后，所以该实现本来也无法安全按身份分桶。", "计数只在进程内；N 个副本的理论总许可接近 N 倍，但负载不均、连接复用、扩缩容和重启会改变实际结果，不能把它当集群配额或安全防滥用边界。租户公平与集群总量应由网关或经过设计的自定义 limiter 负责。"] },
      { id: "queue-rejection", title: "排队、拒绝与客户端合同", paragraphs: ["queueLimit>0 把延迟转成内存排队。队列与请求处理共享上游超时预算；客户端断开、代理超时和进程退出必须实测，不能把排队描述为可靠交付。生产默认优先 queueLimit=0，只有在明确容量模型下才开启有界队列。", "拒绝只设置 HTTP 429；当前 OnRejected 不写 Retry-After、Asgard Response、错误码或重试时间。客户端应把 429 作为独立传输结果，采用有界指数退避与 jitter，并遵守业务幂等；不要从响应猜测窗口何时恢复。"] },
      { id: "rollout-capacity", title: "滚动发布与容量规划", bullets: ["用每实例目标并发、延迟分位数和资源上限选择 permit/token 参数，不从峰值 QPS 反推一个孤立数字", "确保代理连接限制、Kestrel maxConcurrentConnections、全局 limiter、数据库连接池和下游配额层层一致", "滚动发布和自动扩缩容会新增空桶；不能依赖它阻止攻击或保证全局公平", "readiness 成功后再接流量；下线先从负载均衡摘除，再排空 limiter 队列和在途请求", "策略或副本数变化要记录为容量变更并做 canary 压测"] },
      { id: "failure-diagnostics", title: "故障诊断", bullets: ["live 与 ready 都绿但依赖已坏：检查依赖探针是否带 ready tag、是否误用 stub/self", "健康探针出现 429：证明它与业务共享 global bucket；检查业务洪峰与 queueLimit", "所有租户同时被限流：这是固定 global key 的预期，不是 tenant partition", "多副本阈值漂移：逐实例观察计数与负载分布，不要只看负载均衡入口", "429 没有 JSON/Retry-After：这是当前拒绝合同，不要让客户端按 Response<T> 反序列化", "静态资产未被限流：它们在 UseRateLimiter 之前短路"] },
      { id: "acceptance", title: "生产验收矩阵", bullets: ["分别验证 /health、/health/ready、/health/live 的检查集合和默认响应", "逐个断开 PostgreSQL、Redis、RabbitMQ 与下游：ready 失败、live 保持健康，恢复后 ready 自动恢复", "让依赖检查超时，证明实际超时来自检查实现而不是 timeoutSeconds", "对三种策略验证首个 429、窗口/令牌恢复、队列上限、取消与进程排空", "并发访问 API、Swagger、health 与静态文件，证明共享桶和静态绕过", "两副本及滚动重启下记录 per-instance 行为、429 比例、p95/p99 与资源使用"], code: { language: "bash", value: healthRateAcceptance } },
      { id: "ai-ready-sources", title: "AI Ready 与源码证据", paragraphs: ["Agent 维护本页先加载 asgard-host-features、asgard-host-project 与 asgard-configuration；接入具体依赖探针时再加载 database/cache/messaging 对应 Skill。必须从 RegisterHealthChecks、RegisterRateLimiting、ConfigureMiddlewarePipeline 与 MapHealthChecks 主路径证明行为，不能从 Options 字段推断端点排除、集群计数或 timeout 已接线。"] },
    ],
  },
  {
    slug: "plugin-lifecycle", group: "插件", eyebrow: "PLUGIN STATE", title: "插件生命周期与失败边界", description: "在正确阶段注册服务、初始化资源、映射端点、启动任务并安全停止插件。", sections: [
      { id: "build-sequence", title: "从服务注册到接流量的真实时序", bullets: ["插件发现、依赖排序与 ConfigureServicesAsync 发生在最终容器 Build 之前；只能修改 IServiceCollection，不能解析最终 ServiceProvider", "WebApplication Build 后，宿主同步调用 PluginManager.InitializeAsync(default)：按依赖顺序先 Initialize、再 Start", "PluginBase.StartAsync 先执行 OnStartAsync，再读取插件目录 plugin.yaml 并逐个注册 Job，全部成功后才写 Running", "插件初始化完成后，宿主构建中间件管线并同步等待所有 ConfigureMiddlewareAsync；之后才执行 AfterHostBuild 并把 app 返回给调用方", "app.RunAsync 尚未开始监听时生命周期钩子已执行；不要在钩子里调用依赖本机 HTTP listener 已就绪的自检"] },
      { id: "stage-capabilities", title: "每个阶段允许的能力", bullets: ["ConfigureServicesAsync：注册服务和配置；不要 BuildServiceProvider、启动线程、连接或解析 scoped 服务", "OnInitializeAsync：ServiceProvider、CreateLogger、GetService/GetOptionalService/GetAsgardContext 已可用；建立可失败的资源前准备补偿清理", "OnStartAsync：启动插件拥有的工作；自动 Job 注册发生在它之后，所以 OnStart 成功不代表 Job 已全部注册", "OnConfigureMiddlewareAsync：只装配中间件或通过 IEndpointRouteBuilder.Map... 映射端点；不要调用 UseEndpoints 提前执行 endpoint", "OnStopAsync：停止接收插件工作并等待在途任务；OnDisposeAsync：幂等释放剩余资源，不再依赖新请求"] },
      { id: "example", title: "阶段正确的插件", code: { language: "csharp", value: pluginLifecycleCode }, note: "示例映射端点，不调用 UseEndpoints；授权仍由宿主后续的 UseAuthorization 执行。" },
      { id: "observable-states", title: "只相信主路径真正写入的状态", paragraphs: ["PluginBase 主路径只写 Unloaded、Initialized、Running、Stopped，再在 Dispose 成功后写回 Unloaded。InitializeAsync 在调用 OnInitializeAsync 前就写 Initialized；若 OnInitialize 抛错，对象状态仍可能显示 Initialized，但不会加入 PluginManager.LoadedPlugins。Start 失败同样保留 Initialized。不要把 PluginState 枚举中的 Loading、Starting、Error 等值描述成 5.1.3 必然可观察的转换，也不要把生命周期状态持久化成业务状态。"] },
      { id: "failure-domains", title: "构建失败与部分启动是两种故障域", bullets: ["发现、重复 ID、缺失依赖/环、程序集加载或 ConfigureServices 失败发生在容器构建前，会阻止宿主构建", "Initialize 失败会记录 Error、跳过其所有 dependents 的 Initialize，但管理器继续处理独立插件", "Start 失败会记录 Error、跳过 dependents 的 Start；那些 dependent 已在前一轮 Initialize 并留在 LoadedPlugins", "宿主只记录 `Plugin system ready (N running)`，不会因为关键插件少于预期自动让 Build 或 RunAsync 失败", "关键插件必须提供业务 readiness/启动门禁；进程 live、默认 ready 或宿主已监听都不能替代 Running 数与功能验收"] },
      { id: "middleware-after-failure", title: "非 Running 插件仍可能装配 Web 管线", paragraphs: ["PluginManager.ConfigureMiddlewareAsync 遍历 LoadedPlugins，不检查 State。Start 失败的 Initialized 插件，以及因为依赖 Start 失败而未启动的 Initialized dependent，仍会收到 ConfigureMiddlewareAsync；它们可能映射端点或注册中间件。任何插件中间件异常又会通过同步 GetResult 阻止宿主 Build 返回。", "插件端点必须在 handler 内再次依赖真实 readiness，而不是仅因路由存在就报告可用。对于关键插件，发布门禁应把‘端点存在但插件未 Running’视为失败。"] },
      { id: "timeouts-cancellation", title: "5.1.3 没有生命周期超时托底", paragraphs: ["Yggdrasil 初始化插件时显式传 default CancellationToken，中间件配置也由构建线程同步等待；LoadTimeoutSeconds 没有接到这些主路径调用。一个不返回的 Initialize、Start、Job 注册或 ConfigureMiddleware 可以无限阻塞构建。插件必须自己给外部 I/O 设置超时、传递可用 cancellationToken，并避免在生命周期钩子启动不可追踪的 fire-and-forget Task。"] },
      { id: "resources-compensation", title: "初始化资源必须可补偿", bullets: ["OnInitialize 在状态写 Initialized 后失败，管理器不会把实例加入 LoadedPlugins，也不会在当前失败分支调用 Stop/Dispose；已打开资源必须在钩子自身 catch/finally 中回收", "OnStart 成功但自动 Job 注册中途失败时，插件仍停在 Initialized；OnStart 已创建的资源不会自动回滚", "把多个资源初始化写成可逆步骤，只有全部完成后才发布可用标记；失败按逆序补偿", "不要在生命周期钩子持有从根容器直接解析的 scoped 服务；为一次操作显式创建并释放 scope"] },
      { id: "shutdown", title: "停止、释放与尾部丢失边界", bullets: ["AsgardRuntimeHostedService 先 Shutdown JobManager，再 Dispose PluginManager；OnStop 不能依赖调度器仍接受或执行作业", "PluginManager 按依赖卸载顺序逐个 Unload；Running 插件先 Stop，再 Dispose", "Unload 在 Stop 前已从字典移除插件；OnStop 抛错会跳过该插件 Dispose，管理器记录 warning 后继续其他插件", "DisposeAsync 没有宿主停止 CancellationToken；钩子仍需有界、幂等，并允许进程被强制终止", "下线先停止接流量，再排空插件自有队列/连接；把 graceful 与 forced termination 的可接受数据丢失分别写入运行合同"] },
      { id: "reload-boundary", title: "Reload 不是生产热升级", paragraphs: ["内建插件明确不支持 Reload。外部 Reload 只卸载目标、重载 descriptor、Initialize 新实例并放回字典；它不调用 ConfigureServices、Start、自动 Job 注册或 ConfigureMiddleware，也不重建根 DI、MVC ApplicationParts、依赖拓扑和宿主管线。即使返回实例也不代表插件恢复 Running 或新 API 已接入。生产升级与回滚使用不可变进程替换。"] },
      { id: "release-rollback", title: "发布与回滚门禁", bullets: ["发布清单固定插件 DLL、依赖、plugin.yaml、配置与 digest；启动日志中的 expected/running 插件集合必须与清单一致", "关键插件注册自有 ready check，覆盖外部依赖、后台 loop 和必要 Job；未满足时不接流量", "canary 验证插件 Controller、Map endpoint、401/403、租户上下文、Job/消息副作用与独立插件故障隔离", "升级失败时停止新副本并恢复上一整套宿主+插件+配置，不在运行进程里替换 DLL 或调用 Reload 补救", "回滚后重复 Running 集合、endpoint、后台工作和优雅停止验收，避免旧插件读取新配置产生半兼容"] },
      { id: "acceptance", title: "真实进程验收矩阵", bullets: ["正常启动：依赖顺序、每阶段唯一 marker、expected Running 数及关键 ready 均正确", "故障注入：分别让 ConfigureServices、Initialize、Start、自动 Job 注册和 ConfigureMiddleware 抛错/挂起，记录宿主是否构建、哪些 dependent 被跳过、端点是否仍出现", "授权：插件 Map endpoint 与 Controller 的匿名/无权限/合法身份分别返回预期 401/403/成功，禁止 UseEndpoints 绕过宿主授权", "停止：有在途请求、后台 loop、Job 和外部连接时优雅退出，确认依赖卸载顺序、最终 marker 与超时后的强杀边界", "多副本滚动：新副本关键 ready 后才接流量，旧副本摘流后再停止；任一副本 Running 集合不符即停止 rollout", "回滚：恢复上一 artifact/config 后重新验证状态、端点、作业唯一性与无重复消费"], code: { language: "bash", value: pluginAcceptance } },
      { id: "ai-ready-sources", title: "AI Ready 与源码证据", paragraphs: ["Agent 维护本页先加载 asgard-plugin-lifecycle、asgard-host-project 与 asgard-host-features；涉及自动 Job 时再加载 asgard-job-scheduling。必须同时核对 PluginBase、PluginManager/PluginManager.Lifecycle、PluginServiceConfigurator、Yggdrasil PluginIntegration/Configurator 与 AsgardRuntimeHostedService，不能从完整 PluginState 枚举或 Skill 旧状态图发明主路径未写入的状态、超时、失败回滚或热升级保证。"] },
    ],
  },
];

export const zhHeimdallOperationsRunbooks: DocPage[] = [
  {
    slug: "heimdall-database-migrations", group: "部署与运维", eyebrow: "HEIMDALL 5.3.19 · POSTGRESQL", title: "数据库初始化、迁移与回滚", description: "以 12 个发布增量、CodeFirst 与真实数据库验收三条独立证据管理空库、升级和失败恢复。", sections: [
      { id: "release-inventory", title: "5.3.19 发布 SQL 精确清单", paragraphs: ["tag v5.3.19 / commit 0032070 的 be/Database/Migrations 共有 12 个 PostgreSQL 增量：原 7 个 identity_webhook、mcp_credentials、object_storage、tenant_login_branding、tenant_oidc_cors、security_event_lifecycle、sys_user_profile；另增 20260720_application_domain_00_precheck、01_migrate、02_postcheck、03_cleanup 与 20260720_mcp_credential_policy。", "Application 域四阶段不是可任意排序的同类文件：先用 precheck 阻断重复业务键、孤儿和非法状态，再 migrate 建结构/回填 ApplicationId/关系，随后 postcheck 证明数量与约束，cleanup 只能在新版本稳定且回滚窗口结束后执行。MCP policy 脚本把平台/租户凭据扩展列扩大到 varchar(8192)。"] },
      { id: "missing-migration-system", title: "仍缺 baseline、ledger 与 down", paragraphs: ["5.3.19 仍没有从空 PostgreSQL 重建完整 schema 的 baseline SQL，没有记录已应用版本/校验和/成功状态的内建 migration ledger，也没有 down scripts。部分幂等 DDL 不证明数据迁移、回填、去重和约束建立可在任意状态安全重跑。", "发布者必须外部维护起始版本、审核顺序、文件 SHA-256、执行者、UTC 时间、事务策略和结果。未知来源数据库先做 schema diff、precheck 与备份/PITR 演练。"] },
      { id: "auto-sync-boundary", title: "auto_sync_schema 的真实边界", paragraphs: ["oidc.bootstrap.auto_sync_schema 默认 false。开启后 OidcPlugin 在 OnStart 中对其发现的实体类型调用 FreeSql CodeFirst.SyncStructure；它是当前模型驱动的结构同步，不是版本化迁移引擎，不产生 ledger、reviewed SQL、down 或跨版本兼容证明。", "关闭只跳过 SyncStructure。后续仍按顺序运行 tenant CORS 回填、PostgreSQL 条件索引确保、runtime settings 迁移和默认管理员 seed；这些步骤会访问既有表。空库 + false 不是已发布初始化路径，多实例同时以 true 启动也没有 schema 级 leader/锁证明。"], code: { language: "yaml", value: databaseProductionYaml } },
      { id: "empty-database-bootstrap", title: "空库只能作为受控 bootstrap 验收", paragraphs: ["可审计的临时方案是固定 5.3.19 镜像、单 Heimdall 实例、专用空 PostgreSQL，显式开启 SyncStructure；禁止流量和其他副本。启动成功后导出 schema-only 快照，运行 schema/protocol 验收，停止实例，改回 false，再从同一数据库启动一次。", "PostgreSqlCompatibilityIntegrationTests 仍只是局部真实数据库证明，不是完整 stock host 的空库发布 baseline。"], code: { language: "yaml", value: databaseBootstrapYaml } },
      { id: "upgrade-and-order", title: "5.1.2 → 5.3.19 先确定起点与阶段", paragraphs: ["从实际 5.1.2 生产备份克隆演练，先验证 7 个旧增量状态，再按 Application 域 precheck → migrate → postcheck 执行；MCP policy 在 5.3.0 应用启动前完成。cleanup 与 schema 收缩另设发布窗口。", "每份文件用 psql -X -v ON_ERROR_STOP=1 执行并记录摘要。先在生产规模克隆测量锁、WAL、回填与失败重跑，不在生产首次发现重复 Application/Permission/Client 归属。"], code: { language: "bash", value: migrationCommand } },
      { id: "expand-contract", title: "Expand → deploy → contract", bullets: ["Expand：先运行 precheck，处理重复业务键/孤儿；建 Application 结构并回填包括软删除和历史 OIDC Client 的 ApplicationId", "Deploy：发布能读取 Application/Tenant 新模型的 5.3.19 后端与同 tag Web，观察登录、签发、Manifest、Grant、Tenant RBAC 与 MCP", "Contract：postcheck 全通过并结束回滚窗口后才运行 cleanup；仓库没有 down SQL，回滚依赖备份/PITR 与兼容镜像", "同一变更涉及大表 UPDATE/索引时，先证明锁、耗时、复制延迟和重复执行边界"] },
      { id: "backup-pitr-and-recovery", title: "备份、PITR 与失败恢复", paragraphs: ["迁移前保存一致性全库备份、schema dump、配置/Secrets 引用、镜像 digest 与脚本 digest，并确认 PostgreSQL WAL 归档和 PITR 恢复点可用。完成一次隔离 restore 验证；‘备份命令成功’不等于可恢复。", "失败后立即停止后续脚本与新版本副本，保存 psql 错误、事务状态和 schema diff。若事务已回滚，修正根因后从已验证状态重试；若存在已提交 DDL/回填，禁止猜测式反向 SQL。选择向前修复、经审核的补偿脚本，或恢复备份/PITR，并把应用流量恢复到与数据库兼容的镜像。"] },
      { id: "multi-instance-startup", title: "多副本启动门槛", paragraphs: ["schema 变更是部署前单独阶段：停止管理写入，由一个 migration runner 执行。不要让多个 5.3.19 副本同时 auto_sync_schema=true；启动回填、条件索引、RBAC sync、runtime settings 与 seed 不是集群迁移编排器。", "迁移/postcheck 完成后，以 auto_sync_schema=false 滚动启动；每个副本通过数据库、Discovery/JWKS、系统/租户登录、Application Client 与 MCP smoke 后再接流量。"] },
      { id: "schema-and-application-acceptance", title: "空库与升级库必须分别验收", code: { language: "sql", value: migrationVerificationSql }, bullets: ["空库：从全新数据库走受控 bootstrap，重启为 false；导出 schema 并与审核快照比较，不能只数表", "升级库：从每个受支持的真实起始版本备份演练，验证 7 个增量涉及的表、列、索引、回填与重复数据边界", "核对关键列类型/nullability/default、条件唯一索引谓词、主键/tenant_id、runtime settings/history；保存查询与结果", "根与租户 Discovery/JWKS、Authorization Code + S256 PKCE、Refresh、UserInfo、登出、管理 API、MCP/identity webhook/安全事件等受影响路径真实冒烟", "重复启动 auto_sync_schema=false 不产生额外结构变化；多副本并发业务写入与回滚镜像均通过", "在生产数据量克隆中记录 DDL 锁、执行时间、WAL、复制延迟、CPU/IO 和磁盘增长"] },
      { id: "release-boundaries", title: "Release 与未证明边界", paragraphs: ["Release：v5.3.19 / 0032070 证明上述 12 个增量、Application 四阶段脚本与 SQL 合同测试、默认 false 的 auto_sync_schema；HEAD 与 tag 相同且工作树 clean。", "未证明/未发布：完整 baseline、覆盖所有历史版本的通用顺序矩阵、内建 ledger/checksum、down scripts、全宿主空库验收、多实例 schema leader、自动回滚或仓库提供的 PITR 编排。"] },
    ],
  },
  {
    slug: "heimdall-reverse-proxy", group: "部署与运维", eyebrow: "HEIMDALL 5.3.19 · TLS BOUNDARY", title: "反向代理、TLS 与安全 Cookie", description: "把公网 Issuer、可信 Scheme、根路径路由、请求传输与真实浏览器 Cookie 作为独立的生产验收边界。", sections: [
      { id: "issuer-versus-scheme", title: "Issuer 与 Request.Scheme 是两条事实", paragraphs: ["生产显式配置浏览器真实访问的 HTTPS authority；租户 issuer 在其后追加 /{tenantId}。OidcAuthorityService 只有在 oidc.issuer 为空时才从 Request.Scheme、Host 与 PathBase 推导 Authority。固定 HTTPS oidc.issuer 会改变 Discovery、Token iss 和协议生成 URL，但不会改写内部 HTTP 请求的 Request.Scheme。", "因此“Discovery issuer 正确”不能证明 Cookie 安全。TLS 在代理终止时，必须在 Cookie/认证处理之前由受信任宿主层恢复真实 scheme/host，并拒绝不受信来源伪造 forwarded headers；两项必须分别测试。"], code: { language: "yaml", value: reverseProxyIssuerYaml } },
      { id: "stock-forwarded-header-gap", title: "stock 5.3.19 的 Forwarded Headers 缺口", paragraphs: ["当前 Heimdall 5.3.19 tag v5.3.19 / commit 0032070 与 Asgard 5.1.3 stock host 没有可验证的 UseForwardedHeaders、ForwardedHeadersOptions、KnownProxies 或 KnownNetworks 配置面。Nginx 发送 X-Forwarded-Proto/Host/For 只是输入，不证明应用消费它们，更不证明只信任该代理。", "生产必须选择其一：定制宿主，在所有 Cookie/认证/重定向逻辑之前注册并限制 Forwarded Headers；或使用能以等价方式恢复 Request.Scheme/Host 且有真实测试证据的平台。否则 Kestrel 必须视为不具备代理感知能力，不能依赖 forwarded 值做安全决策。"] },
      { id: "tls-and-network-boundary", title: "TLS termination 与网络隔离", bullets: ["客户端到唯一入口强制 TLS 1.2+、有效证书和完整链；HTTP 入口只做受控 HTTPS redirect 或完全关闭", "代理到 Kestrel 使用隔离的容器/私网；若风险模型要求端到端加密，再为上游启用并验证 TLS/mTLS", "Kestrel 5000 不得发布到公网或不受信 LAN；防火墙、安全组和容器网络只允许代理与运维探针", "覆盖而不是追加客户端提供的 Forwarded/X-Forwarded-*；限制 Host，拒绝未知 Host/SNI", "HSTS、证书续期、OCSP/链变化与代理时间同步属于入口运维合同，不由 oidc.issuer 提供"] },
      { id: "root-path-and-pathbase", title: "Path Base 与重写边界", paragraphs: ["OidcAuthorityService 的请求推导路径会使用 Request.PathBase，但当前 stock 启动没有已证明的 UsePathBase 或 X-Forwarded-Prefix 消费合同；hosted login/consent 资产和部分前端请求还使用根路径。5.3.19 的可发布指导是部署在专用域名根路径，例如 https://id.example.com，而不是 /heimdall。", "不要只在代理 strip/add prefix 后把 oidc.issuer 写成带路径 URL。若业务必须使用子路径，需要定制宿主和静态资产，并逐个验证 Discovery、JWKS、authorize/token/userinfo/introspect/revoke/end-session、login/consent callback、API、MCP 与所有 Location/表单/脚本 URL；在这些证据完成前标为未支持。"] },
      { id: "proxy-request-contract", title: "Header、请求体、流与超时", paragraphs: ["代理必须保留 Host、method、query、Content-Type、Authorization、Cookie、Set-Cookie、Location 与响应状态，不得记录 Authorization、Cookie、code、Token、密码、MFA 或 SAML Response。Token/consent 使用 form，管理 API 使用 JSON，SAML callback 使用 POST，品牌/Passkey 等端点各有请求体边界；统一的过小 body limit 会造成看似协议错误的 413。", "下面的连接/读写 timeout 只是可审查的运维起点，不是 Heimdall 默认合同。它们必须覆盖 Authorization Code、LDAP/SAML 回流、上传、Webhook 管理和故障注入；代理重试不得自动重放非幂等 POST。/mcp 是 Streamable HTTP，需要禁用响应缓冲。当前 5.3.19 没有需要 WebSocket Upgrade 的已发布协议端点，不要为整个站点盲目设置 Connection: upgrade；未来若新增 WebSocket，再单独路由和验收。"], code: { language: "nginx", value: nginxProxyCode } },
      { id: "secure-cookie-contract", title: "Asgard.Identity Cookie 合同", paragraphs: ["Heimdall 登录 Cookie 名为 Asgard.Identity，HttpOnly=true、SameSite=Lax、30 分钟滑动过期，SecurePolicy=SameAsRequest。固定 HTTPS issuer 不会让经内部 HTTP 请求签发的 Cookie 自动带 Secure；只有应用看到可信的 HTTPS Request.Scheme，SameAsRequest 才能产生 Secure。", "不要在代理层机械追加另一个 Set-Cookie 或仅重写 Secure 来掩盖错误 scheme：应用的重定向、外部登录回调和其他绝对 URL 仍可能错误。必须从根因恢复可信 scheme，并在真实浏览器 DevTools/存储和网络响应同时检查 Cookie。"] },
      { id: "multi-tenant-route-matrix", title: "多租户协议路由矩阵", bullets: ["平台：/.well-known/openid-configuration、/.well-known/jwks、/connect/authorize|token|userinfo|introspect|revoke|end-session", "租户：/{tenantId}/.well-known/openid-configuration、/{tenantId}/.well-known/jwks、/{tenantId}/connect/*；tenantId 不得被代理归一化、解码改写或丢失", "交互页与回流：/login.html、/consent.html、/logout-complete.html、/external-login/*、/external-logout/*；完整本地 returnUrl/query 必须保留", "管理/API：/api/*、/scim/v2/{tenantId}、/mcp 与健康检查按各自认证、body、buffering 和暴露策略转发", "平台 Client 不能混用租户端点，租户 Client 不能混用根端点；错误路由必须失败而不是被代理 fallback/SPA rewrite"] },
      { id: "browser-and-protocol-acceptance", title: "真实浏览器与协议验收", bullets: ["根与一个租户 Discovery 的 issuer、jwks_uri、authorization_endpoint、token_endpoint、userinfo_endpoint、introspection_endpoint、revocation_endpoint、end_session_endpoint 全部为预期公网 HTTPS 且路径正确", "真实浏览器完成平台和租户 Authorization Code + S256 PKCE、登录/MFA、Consent、UserInfo、Refresh 与 End Session；callback 和 post_logout_redirect_uri 精确匹配登记值", "在登录响应与浏览器 Cookie Store 中确认 Asgard.Identity 同时为 Secure、HttpOnly、SameSite=Lax，Domain/Path 符合预期；内部 HTTP 链路不能导致 Secure 缺失", "验证错误 Host、伪造 X-Forwarded-Proto/Host/For、直连 :5000、错误 tenant、双斜线/编码路径、超大 body、慢请求和上游超时都按策略失败", "验证 /mcp 流式响应不被缓冲；普通站点不出现无理由 WebSocket Upgrade；413/408/502/504 与应用 400/401/403 可被诊断区分"] },
      { id: "rollout-observability-and-rollback", title: "发布、观测与故障回滚", bullets: ["先在 canary hostname 验证证书、DNS、Host allowlist、Discovery 与浏览器 Cookie，再切正式 DNS/LB；保留旧代理配置和旧 upstream 可立即回切", "nginx -t/等价配置校验、reload、HTTP 冒烟与浏览器验收必须是同一发布门禁；当前 deploy.sh 不处理或回滚 Nginx", "监控 TLS handshake、4xx/413/429、502/504、upstream latency、登录/回调/登出失败、wrong issuer、unknown kid、Cookie 重复登录和按租户路由错误", "代理改动失败先回滚入口配置和流量，不重新生成 signing/encryption keys；数据库无变化时不要把身份事故扩大成密钥轮换", "回滚后重复 Discovery、PKCE、Cookie 和 logout 验收；保留已脱敏 request id、Host、path、status、upstream timing，禁止保留 Secret/Token/Cookie"] },
      { id: "release-boundaries", title: "Release、HEAD 与未证明边界", paragraphs: ["Release：显式/请求推导 Authority、平台与租户 Discovery/JWKS/协议路由、Asgard.Identity SameAsRequest Cookie、登录/Consent/回调/登出逻辑及 tenant 路由测试的核心合同由 5.1.2 引入；当前 clean v5.3.19 / 0032070 保留这些合同，并已包含友好登出错误展示、login.html UTC 本地化与过期 RP logout hint 校验修复。HEAD 与 tag 相同，仍未增加 forwarded-header 或代理配置能力。", "未证明/未发布：stock UseForwardedHeaders、KnownProxies/KnownNetworks 配置、可信 X-Forwarded-Prefix/UsePathBase 子路径部署、自动 Secure Cookie 修复、Nginx 管理/回滚、代理 body/timeout 默认值、WebSocket 端点或端到端 mTLS。Nginx 示例和 rollout 是运维策略，必须在目标平台真实验收，不能当成 Heimdall 内建控制面。"] },
    ],
  },
  {
    slug: "heimdall-client-credentials", group: "应用接入", eyebrow: "HEIMDALL 5.3.19 · MACHINE IDENTITY", title: "Client Credentials 与后端服务身份", description: "注册、签发、轮换并撤销可被 Asgard 资源 API 安全接受的租户 BackendService 身份。", sections: [
      { id: "registration-contract", title: "注册合同", bullets: ["clientType=confidential；public client 不能使用 client_credentials", "applicationType 不能是 native，grantTypes 必须包含 client_credentials", "必须配置 client_secret；tokenEndpointAuthMethods 只登记实际使用的 client_secret_basic 和/或 client_secret_post，不能包含 none", "客户端 allowed scopes 必须包含每次请求的 scope；不要授予 openid/profile 等与机器调用无关的范围", "面向 stock Asgard API 时 accessTokenFormat 必须为 jwt；opaque access token 需要外部 introspection 设计", "租户客户端使用 /{tenantId}/connect/token 与 /{tenantId} issuer；不要把平台根 issuer Token 交给 Asgard 5.1.3 host.auth"] },
      { id: "secret-authentication", title: "Secret 与 Token 端点认证", paragraphs: ["优先使用 client_secret_basic；client_secret_post 只在客户端登记且调用环境能确保表单 body 不进入访问日志/Trace 时使用。Basic 与 body 同时存在、Basic client_id 与 body 不一致、未允许的认证方法或错误 Secret 都会失败。", "Secret 只属于机密后端，不进入浏览器、移动端、URL、仓库、镜像、日志、Trace、提示词或遥测。由 Secret Manager 注入并限制读权限；不同 workload 使用不同 client，不能共享一个万能 Secret。"], code: { language: "bash", value: `${clientCredentialsBasic}\n\n# Only when client_secret_post is explicitly registered\n${clientCredentialsPost}` } },
      { id: "scope-resource-audience", title: "Scope → Resources → audience", paragraphs: ["Heimdall 先验证请求 scope 属于客户端权限，再查询这些自定义租户 Scope 的 Resources。所有非空 Resources 组成 Access Token aud；若没有资源则回退 client_id。IdentityAuthorizationAudienceTests 已分别证明 built-in scopes 的 client_id fallback 与自定义 resource audience。", "生产 API 不应依赖 fallback：为 API 创建专用 Scope，把 Resources 设置为资源服务器配置的唯一 audience，让客户端允许并实际请求该 Scope。Scope 被允许但请求未携带时不会自动进入 Token；多个 Scope 可产生多个 aud，而 Asgard 5.1.3 的单值 audience 只要求其中一个 aud 精确匹配。"] },
      { id: "token-and-claims", title: "签发 Token 与 claims", bullets: ["每次成功交换都会创建 client_credentials authorization record，并签发 Access Token；includeRefreshToken=false，因此没有 Refresh Token", "sub 与 client_id 都是调用客户端 ID；token_type=BackendService", "租户客户端带 tenant_id；roles 与 permissions 是空数组，不应伪装用户权限", "scope 是获准范围，tenantMetadata 可恢复；没有 user_id 或用户 session 语义", "Token 响应的 expires_in 决定缓存上限；消费者应提前带抖动刷新，但不能并发风暴式兑换"] },
      { id: "asgard-resource-server", title: "Asgard 5.1.3 资源服务器兼容合同", paragraphs: ["host.auth.jwt.issuerTemplate 必须恰好包含一个 {tenant}，从 Token iss 提取 tenant；host.auth.jwt.audience 是全局单值，必须与 Token 任一 aud 精确相等。资源 API 使用租户 Discovery/JWKS 离线验证 JWT 签名、issuer、audience 与生命周期。", "认证成功后再用 token_type=BackendService 与 scope 做后端授权，例如 AsgardAuthMatch；不要依赖空 roles/permissions。stock host.auth 不支持 opaque Token、平台根 issuer、同时信任平台/租户 issuer 或每请求 introspection，这些需要单独认证方案。"] },
      { id: "secret-rotation", title: "双 Secret 轮换", paragraphs: ["POST 客户端 secret reset 生成 16 个随机字节的十六进制新 Secret，只在响应返回明文；数据库保存 password hash。gracePeriodMinutes 为 0–1440，默认 60；大于 0 时旧 hash 保留到 PreviousClientSecretExpiresAt，验证器同时接受新旧 Secret。", "先把新 Secret 写入消费者 Secret Manager，重启/刷新所有实例并用新 Secret 成功兑换，再等待旧凭据调用归零。过渡窗到期后旧 Secret 自动不再通过验证，但旧 hash 字段不会因此自动清空。紧急泄露使用 grace=0；普通轮换窗口必须短于组织风险容忍度。"] },
      { id: "revocation-boundaries", title: "撤销与传播边界", paragraphs: ["轮换 Secret 只改变以后谁能兑换，不撤销已经签发的 Access Token。停用或删除客户端的管理路径会把该 client 的协议 Access/Refresh Token 和 authorization 状态标为 revoked；Client Credentials 本身不产生 Refresh Token。", "外部 Asgard API 的 JWKS 离线验证不会每请求查询 Heimdall revocation。已签发 JWT 通常仍可用到 exp，除非资源侧实现 deny-list/invalidation 或采用经验证的在线方案。Heimdall introspection 只对同 client+tenant 所有的 Access Token 返回 active，不是通用资源服务器 RFC 7662。"] },
      { id: "operations-and-observability", title: "运行与可观测性", bullets: ["按 client_id、tenant、scope、audience、结果、延迟和错误类别统计 token exchange；绝不记录 Authorization、client_secret 或 Access Token", "区分 invalid_client、unauthorized_client、invalid_scope、429、5xx 与网络超时；配置/凭据错误停机告警，瞬时错误指数退避加抖动", "Token 在进程内按 expires_in 缓存并单飞刷新；不要每次 API 调用都访问 /connect/token", "为每个 workload 建立 owner、用途、允许 Scope、目标 audience、轮换周期、最后使用时间和撤销 Runbook", "发现 client_id 异常来源时先禁用/删除或紧急轮换，再评估已签发 JWT 的剩余 TTL 与资源侧隔离"] },
      { id: "production-acceptance", title: "真实生产验收", bullets: ["用 Basic 成功兑换；若未登记 post，则 post 失败；错误/过期旧 Secret、public/native client 和未允许 grant 都失败", "未允许/未请求 Scope 失败或不进入 Token；专用 Scope Resources 产生预期 aud，fallback client_id 仅在显式测试中接受", "解码但不信任地检查 claims，再由 Asgard API 真实验证 tenant issuer、JWKS、audience、exp、tenant_id、BackendService 和 scope", "错误 audience、平台 issuer、opaque Token、用户策略、跨 tenant 路由均被拒绝", "轮换窗口内新旧 Secret 按计划工作，窗口后旧 Secret 失败；多个消费者实例无兑换风暴", "停用/删除客户端后不能兑换；记录的 JWT 离线传播边界与最长残余有效期符合事故预案"] },
      { id: "release-boundaries", title: "Release、HEAD 与未证明边界", paragraphs: ["Release：confidential/client_credentials 注册校验、Basic/Post reader 与 validator、current/previous hash 验证、Scope/Resources audience、BackendService claims、无 Refresh Token、authorization 创建、client 状态撤销，以及 reader/auth/audience/application tests 的核心合同由 5.1.2 引入；当前 clean v5.3.19 / 0032070 保留这些行为，HEAD 与 tag 相同。", "未证明/未发布：private_key_jwt、mTLS client authentication、自动 Secret Manager 分发、无限旧 Secret 叠加、多 audience 的每 API 动态配置、stock Asgard opaque introspection、通用 RFC 7662 resource-server introspection、外部 API 即时 JWT 撤销或完整生产多副本验收。"] },
    ],
  },
  {
    slug: "heimdall-tenant-signing-key-rotation", group: "部署与运维", eyebrow: "HEIMDALL 5.3.19 · TRUST TRANSITION", title: "租户签名密钥轮换", description: "以已发布状态机、缓存和存储合同轮换租户 RSA 密钥，并把多副本并发与灾难替换作为独立验收边界。", sections: [
      { id: "system-versus-tenant", title: "先分清 system key 与 tenant keys", paragraphs: ["system signing key 来自 oidc.signing.rsa_private_key，为平台 issuer、默认客户端和根 JWKS 服务；它不进入 tenant_oidc_key 状态机。tenant keys 存在 tenant_oidc_key，私钥经 EncryptionService 加密后落库，为 /{tenantId} issuer 签名。轮换租户 key 不会轮换 system key，反过来也一样。", "根 /.well-known/jwks 包含 system key 和所有租户当前验证 key；/{tenantId}/.well-known/jwks 只包含该租户 Active/Retiring 验证 key。资源服务器应使用与 Authority 对应的 JWKS，不能把根 JWKS 当作租户最小信任集。"] },
      { id: "state-machine", title: "已发布状态机与时间语义", bullets: ["Generate/Create 创建 Draft；Draft 不签名、不验签、不进入 JWKS", "Activate 只接受 Draft，并把目标写为 Active、ActivateAt=request、RetireAt=null；未来 ActivateAt 在运行时显示 pending_activation", "当请求时刻命中旧 Active，旧 key 在同一数据库事务中转为 Retiring，RetireAt=ActivateAt+retentionDays", "Active 只有在 ActivateAt<=UTC now 且未过 RetireAt 时签名；Active/Retiring 满足同一时间窗时用于验签和 JWKS", "CompleteRetirementAsync 只接受 Retiring 且 RetireAt<=UTC now，然后写为 Retired；它不是时间到达后自动发生的状态变化"] },
      { id: "generate-and-activate", title: "生成、预发布与激活", paragraphs: ["管理调用需要 platform.admin 或 platform.oidc_key.manage；租户权限仍受 TenantResourceAccessGuard 限制。常规轮换使用服务端 generate，不复制私钥到响应日志、截图、文档或工单。RSA 最低 2048；自动配置接受 2048、3072、4096。", "retentionDays 必须覆盖最大 Token TTL、验证方 JWKS 缓存、Heimdall 5 分钟内部缓存、传播和时钟偏差；存在旧 Active 时必须大于 0。生产先创建 Draft、记录 kid，再在受控窗口调用 Activate。"], code: { language: "bash", value: `${keyGenerateCode}\n\n${keyActivateCode}` } },
      { id: "transaction-and-concurrency", title: "事务不等于多副本串行化", paragraphs: ["ActivateAsync 使用 FreeSql UnitOfWork：检查 Draft、查询当前 Active、更新新 key、回读校验，再更新旧 key 为 Retiring。失败会回滚数据库事务并写 activate_failed 审计；但审计日志与主事务的原子关系、并发隔离级别和跨实例互斥没有端到端证明。", "5.3.19 没有已验证用于密钥轮换的分布式锁，也没有证明每租户只能有一个 Active 的数据库约束。Kid 创建的 PostgreSQL 23505/uk_tenant_oidc_key_tenant_kid 最多 5 次重试只解决 Kid 冲突，不串行化两个 Activate 或多节点自动作业。发布运维必须指定单一轮换 leader，并禁止并发人工操作。"] },
      { id: "cache-and-propagation", title: "缓存刷新不是即时广播", paragraphs: ["TenantSecurityKeyProvider 分别缓存 signing keyset、validation keysets、按 kid validation key 和 JWKS，固定 5 分钟。Repository 更新会清自己的实体/列表缓存，但 5.3.19 密钥变更路径没有显式删除这些 provider cache key，也没有发布跨节点失效事件。", "因此不同副本可能在窗口内继续使用旧签名快照或返回不同 JWKS。先确认所有副本的租户 JWKS 都可见新 kid，再观察每个副本签出的 Token kid；完成退役后至少等待 Heimdall 内部窗口和外部 verifier 的 JWKS TTL，再判断旧 kid 已消失。"] },
      { id: "retirement-and-failure-recovery", title: "RetireAt、最终退役与失败恢复", bullets: ["RetireAt 前保留旧 key，让已签发 Token 在原有效期内继续验签；不要为了清理页面而缩短窗口", "RetireAt 到达不自动把状态改为 Retired，但查询时间窗已排除该 key；随后调用 /complete-retirement，或由启用的作业完成", "CompleteRetirementAsync 没有自己的显式 UnitOfWork/read-back 测试或 provider-cache 清理；失败时保留 Retiring 记录，调查数据库/审计后幂等式重试，不直接改表", "若新 key 激活后签名/验证失败，先停止继续轮换和最终退役；在旧 key 仍处于保留窗时恢复流量并修复新 key，而不是删除旧材料", "若出现两个有效 Active、错误 RetireAt 或部分节点 kid 不一致，隔离轮换 leader、保存审计与数据库快照并人工裁决；stock 5.3.19 没有自动仲裁器"] },
      { id: "automation", title: "自动作业合同与命名双轨", paragraphs: ["RotateTenantOidcKeysJob 默认每 6 小时调度，但运行时 oidc.key_rotation.enabled 决定是否执行。作业逐租户 generate/activate，并完成已到期 Retiring；没有已验证的集群 DisallowConcurrentExecution 或分布式锁。多副本部署只能让一个节点承担当期作业，除非平台另有已验收的单例调度。", "作业读取 oidc.key_rotation.enabled、retention_days、interval_days、rsa_key_size；typed 配置仍是 oidc.tenant_key_rotation.*。两套名称未统一，不能只改 typed 节点就声称运行时已生效。"] },
      { id: "backup-and-disaster-replacement", title: "备份与灾难 key replacement", paragraphs: ["可恢复备份必须同时覆盖 tenant_oidc_key 的公私钥密文、状态/ActivateAt/RetireAt、主数据库一致性，以及能解密这些密文的 Asgard Encryption Key；还要独立备份 system oidc.signing.rsa_private_key。只恢复数据库但丢失加密主密钥，租户私钥不可用于签名。", "正常恢复优先恢复原 system/tenant keys，保持既有 Token 信任链。若确认私钥泄露或永久丢失，key replacement 是破坏性事件：为受影响 trust domain 生成新 key、发布 JWKS、切换签名并按风险决定立即终止旧 key；旧 Token 可能立即失效。system key replacement 与每个 tenant key replacement 分别执行、分别通知资源服务器，不能用一次租户轮换代替平台灾难恢复。"] },
      { id: "multi-replica-acceptance", title: "真实多副本验收门槛", bullets: ["至少两个 Heimdall 副本共享生产同类数据库与缓存；分别直连/带副本标记读取租户 JWKS，不能只测负载均衡后的一个响应", "轮换前保存 system/root 与目标 tenant JWKS；轮换期间持续从每个副本签发 Token，记录 kid、issuer 和时间，不记录 Token 内容", "证明新 kid 在所有租户 JWKS 可见后才接受新签名；RetireAt 前旧 Token 在每个副本和外部资源 API 均可验证", "故障注入一个副本重启、缓存损坏/未命中、数据库暂时失败和作业重叠；证明回源恢复或明确失败，不产生第二个 Active", "最终退役并等待双方缓存 TTL 后，所有副本与外部 verifier 都拒绝旧 kid；根 JWKS 仍保留 system key，其他租户 JWKS 不受影响", "保留脱敏证据：commit、配置、节点、UTC 时间、kid、状态、JWKS 哈希、Token 验签结果和回滚决定"] },
      { id: "release-boundaries", title: "Release、HEAD 与未证明边界", paragraphs: ["Release：Draft/Active/Retiring/Retired 模型、事务化 Activate 回读、RetireAt 查询时间窗、5 分钟可序列化 provider cache、system/tenant JWKS 分界、租户路由保护、Kid 冲突重试及相应单元/集成测试由 5.1.2 引入；当前 clean v5.3.19 / 0032070 保留这些合同，HEAD 与 tag 相同，未增加密钥轮换并发或缓存一致性保证。", "未证明/未发布：每租户 Active 唯一数据库约束、跨实例锁/leader election、provider cache 主动失效、集群级自动作业去重、CompleteRetirement 原子回读、多副本轮换端到端测试、备份恢复演练、HSM/KMS 托管或泄露后的自动撤销广播。完成上述真实验收前，不要把本页称为零停机保证。"] },
    ],
  },
];

export const enAsgardLifecycleDocs: DocPage[] = [
  {
    slug: "host-lifecycle", group: "Host Runtime", eyebrow: "BUILD PHASES", title: "Host build lifecycle", description: "Put configuration, infrastructure, services, plugins, and the Web pipeline into the correct Yggdrasil build phase.", sections: [
      { id: "phases", title: "The five build phases", bullets: ["Phase 1 merges app.yaml, environment YAML, environment variables, and command-line configuration", "Phase 2 loads and validates Host, Logging, Trace, Cache, Database, MQ, Job, and Plugin configuration", "Phase 3 synchronously initializes enabled Trace, Cache, MQ, and Job managers", "Phase 4 registers framework, database, security, MVC, plugins, health checks, rate limiting, and hosted services", "Phase 5 builds the container, initializes and starts plugins, then configures middleware"] },
      { id: "hooks", title: "What belongs in each hook", paragraphs: ["BeforeConfigurationLoad can observe or add ASP.NET configuration sources and AfterConfigurationLoad inspects the merged view. Asgard typed module objects come from the framework's own configuration graph; do not assume a hook-added provider overrides them. Framework registrations can replace a BeforeServiceRegistration entry. AfterServiceRegistration is better for application services, although Swagger is still added afterwards. ConfigureMiddleware is fixed after tenant context and before authorization. AfterHostBuild runs after plugins and pipeline assembly but before listening starts.", "Each hook stores one delegate. Calling the same hook twice replaces the earlier delegate instead of composing it; place multiple ordered actions in one callback."], code: { language: "csharp", value: hostLifecycleCode } },
      { id: "build", title: "Build does more than create the container", paragraphs: ["CreateBuilder construction already reads the base app.yaml, validates HostConfig/LogConfig, and creates bootstrap logging. The base file must therefore be valid without later environment overrides. Build() then initializes infrastructure and initializes/starts plugins synchronously before RunAsync. Configuration, service-registration, or dependency-graph failures can stop the build. Do not put unbounded network work into build hooks."] },
      { id: "availability", title: "Capability availability", bullets: ["Service registration has IServiceCollection but not the final provider", "Plugin GetService, CreateLogger, and GetAsgardContext become valid in InitializeAsync", "JobManager receives the final provider after WebApplication is built", "Plugin middleware is attached after plugin Initialize/Start succeeds"] },
      { id: "shutdown", title: "Shutdown boundary", paragraphs: ["On host stop, AsgardRuntimeHostedService shuts down the active job scheduler before disposing PluginManager. Plugins must still make Stop/Dispose idempotent and ensure their own background work observes CancellationToken."] },
    ],
  },
  {
    slug: "middleware-pipeline", group: "Host Runtime", eyebrow: "REQUEST PIPELINE", title: "Exact middleware order", description: "Understand the real order of tracing, routing, authentication, tenancy, plugin extensions, and authorization.", sections: [
      { id: "order", title: "Asgard 5.1.3 default order", code: { language: "text", value: middlewarePipeline }, note: "This is the current YggdrasilHostBuilder.Configurator order, not an interchangeable architecture sketch." },
      { id: "identity", title: "Authentication, tenancy, and authorization", paragraphs: ["The host adds UseAuthentication only when host.auth.enabled=true. UseAsgardTenant follows authentication. Host and plugin extension points may then enrich the principal, and UseAuthorization always executes afterwards—even when the host-owned JWT handler is disabled."] },
      { id: "extensions", title: "Extension boundaries", bullets: ["Static files run first and may short-circuit, bypassing Trace, CORS, limiting, authentication, tenancy, and authorization", "The host ConfigureMiddleware callback runs before plugin middleware", "Both extension points follow tenant resolution; adding custom authentication there after auth=false may be too late for the correct tenant snapshot", "Map plugin endpoints through IEndpointRouteBuilder.Map...", "Do not call UseEndpoints inside a plugin; it can execute endpoints before authorization", "Only a fully custom pipeline should reproduce the authentication and authorization sequence itself"] },
      { id: "routing", title: "Why routing comes first", paragraphs: ["Endpoint metadata must be selected before authentication and authorization can consume [Authorize], AsgardAuth, and endpoint policies. Incorrect placement causes missing identity or missing-authorization-middleware failures."] },
      { id: "verify", title: "Verification after a pipeline change", bullets: ["Anonymous protected requests return 401", "Authenticated but unauthorized requests return 403", "tenant_id restores the correct tenant context", "CORS preflight is not trapped by authentication", "Authorize/AsgardAuth executes on plugin-mapped endpoints", "Trace, Swagger, health checks, and controller routes remain reachable"] },
    ],
  },
  {
    slug: "health-and-rate-limiting", group: "Host Runtime", eyebrow: "OPERATIONS", title: "Health checks and global rate limiting", description: "Configure live/ready endpoints and the three global limiters while retaining the current runtime boundaries.", sections: [
      { id: "config", title: "Complete configuration and node semantics", paragraphs: ["healthCheck and rateLimiting are nullable nodes: omission means no registration or mapping, while a present node with enabled omitted defaults to enabled. Paths, policy, and numeric values are validated during module loading even when a present node says enabled=false, so an incomplete disabled node can still prevent startup."], code: { language: "yaml", value: healthRateYaml } },
      { id: "health-semantics", title: "Separate live, ready, and all checks", bullets: ["path defaults to /health and runs every registered check", "readyPath defaults to /health/ready and runs only checks tagged ready", "livePath defaults to /health/live and runs only checks tagged live", "The built-in self check carries live and ready but always returns Healthy; it proves nothing about PostgreSQL, Redis, RabbitMQ, or downstreams", "Path collisions retain only the first mapping in path → readyPath → livePath order; never use one path to imply several semantics"] },
      { id: "dependency-checks", title: "Register dependency readiness explicitly", paragraphs: ["Add checks tagged ready through AfterServiceRegistration. Keep live process-only so a transient dependency outage does not make the orchestrator repeatedly kill a recoverable process. Checks should perform lightweight, read-only, cancellable real operations and use distinct names; never use a business write as a probe.", "host.healthCheck.timeoutSeconds is validated as positive but is not passed to MapHealthChecks or HealthCheckRegistration. Each dependency check must own an explicit timeout and honor CancellationToken; the configured 30 seconds is not an execution bound."], code: { language: "csharp", value: readinessRegistrationCode } },
      { id: "health-surface", title: "Health endpoints are public dynamic requests", paragraphs: ["MapHealthChecks uses the ASP.NET Core default response and provides no Asgard Response envelope, dependency-detail JSON, or built-in authorization. Endpoints execute after the global rate-limiter middleware and compete with other dynamic requests for the same limiter; a business surge can starve orchestrator probes. Static files run before limiting and may short-circuit, so they bypass this limiter."], note: "If probes must bypass business limiting, isolate them at the gateway/orchestrator network or implement and verify a custom pipeline. The 5.1.3 configuration surface has no endpoint exclusion." },
      { id: "rate-policies", title: "Three policies and validation traps", bullets: ["FixedWindow uses permitLimit plus windowSeconds", "SlidingWindow additionally uses segmentsPerWindow", "TokenBucket uses tokenLimit, replenishes tokensPerSecond each second, and sets AutoReplenishment=true", "Policy strings are case-sensitive", "TokenBucket does not use permitLimit/windowSeconds/segmentsPerWindow at runtime, but Validate still requires all three to be positive", "queueLimit defaults to zero; when positive, all policies queue OldestFirst"], code: { language: "yaml", value: tokenBucketYaml } },
      { id: "global-partition", title: "global means one bucket per process", paragraphs: ["PartitionedRateLimiter assigns every request reaching UseRateLimiter the fixed key global. It does not partition by IP, tenant_id, user, client_id, route, or HTTP method. Authentication runs after limiting, so this implementation cannot safely partition by identity anyway.", "Counters are process-local. N replicas may offer roughly N times the theoretical permits, but uneven load, connection reuse, autoscaling, and restarts change observed behavior. This is neither a cluster quota nor a security anti-abuse boundary. Put tenant fairness and cluster totals at a gateway or a deliberately designed custom limiter."] },
      { id: "queue-rejection", title: "Queueing, rejection, and client contract", paragraphs: ["queueLimit>0 converts rejection into in-memory waiting. Queue time shares the upstream request timeout budget; test client disconnects, proxy timeout, and process shutdown rather than describing the queue as reliable delivery. Prefer queueLimit=0 in production unless a bounded-queue capacity model justifies it.", "Rejection sets only HTTP 429. The current OnRejected writes no Retry-After, Asgard Response, error code, or retry time. Clients must treat 429 as a distinct transport result, use bounded exponential backoff with jitter, and preserve business idempotency; they cannot infer recovery time from the response."] },
      { id: "rollout-capacity", title: "Rollout and capacity planning", bullets: ["Choose permit/token values from per-instance target concurrency, latency percentiles, and resource limits—not one peak-QPS number", "Align proxy connection limits, Kestrel maxConcurrentConnections, the global limiter, database pools, and downstream quotas", "Rolling releases and autoscaling add empty buckets; never rely on this limiter to stop attacks or guarantee global fairness", "Route traffic only after readiness; remove an instance from load balancing before draining its limiter queue and in-flight requests", "Treat policy or replica-count changes as capacity changes and canary load-test them"] },
      { id: "failure-diagnostics", title: "Failure diagnostics", bullets: ["live and ready remain green during dependency failure: verify the dependency check has a ready tag and is not a stub/self check", "Health probes receive 429: they share the global bucket; inspect business surge and queueLimit", "Every tenant is throttled together: this is expected from the fixed global key, not tenant partitioning", "Threshold drifts across replicas: inspect per-instance load and counters instead of only the load-balancer entry", "429 has no JSON/Retry-After: this is the current rejection contract; clients must not deserialize it as Response<T>", "Static assets are not throttled because they short-circuit before UseRateLimiter"] },
      { id: "acceptance", title: "Production acceptance matrix", bullets: ["Verify the selected check set and default response for /health, /health/ready, and /health/live", "Disconnect PostgreSQL, Redis, RabbitMQ, and downstreams one at a time: ready fails, live remains healthy, and ready recovers", "Make a dependency check time out and prove the bound belongs to the check rather than timeoutSeconds", "For each policy verify first 429, window/token recovery, queue bound, cancellation, and process drain", "Hit APIs, Swagger, health, and static files concurrently to prove the shared bucket and static bypass", "With two replicas and rolling restarts record per-instance behavior, 429 ratio, p95/p99, and resource use"], code: { language: "bash", value: healthRateAcceptance } },
      { id: "ai-ready-sources", title: "AI Ready and source evidence", paragraphs: ["Agents maintaining this page must load asgard-host-features, asgard-host-project, and asgard-configuration first; add the database/cache/messaging Skill for a concrete dependency probe. Prove behavior from the primary RegisterHealthChecks, RegisterRateLimiting, ConfigureMiddlewarePipeline, and MapHealthChecks paths. Options fields do not prove endpoint exclusion, cluster counters, or a wired timeout."] },
    ],
  },
  {
    slug: "plugin-lifecycle", group: "Plugins", eyebrow: "PLUGIN STATE", title: "Plugin lifecycle and failure boundaries", description: "Register services, initialize resources, map endpoints, start work, and stop plugins in the correct phases.", sections: [
      { id: "build-sequence", title: "Actual sequence from registration to traffic", bullets: ["Discovery, dependency sorting, and ConfigureServicesAsync run before the final container Build; only mutate IServiceCollection and do not resolve the final provider", "After WebApplication Build, the host synchronously calls PluginManager.InitializeAsync(default), performing Initialize in dependency order and then Start in dependency order", "PluginBase.StartAsync runs OnStartAsync, reads plugin.yaml from PluginDirectory, schedules each job, and writes Running only after all succeed", "The host then constructs the middleware pipeline and synchronously waits for every ConfigureMiddlewareAsync; AfterHostBuild follows before returning app", "Lifecycle hooks run before app.RunAsync begins listening; never make a hook depend on a self-HTTP check against a listener that is not ready"] },
      { id: "stage-capabilities", title: "Capabilities by stage", bullets: ["ConfigureServicesAsync: register services/configuration; never BuildServiceProvider, start threads/connections, or resolve scoped services", "OnInitializeAsync: ServiceProvider, CreateLogger, GetService/GetOptionalService/GetAsgardContext are available; prepare compensation before acquiring fallible resources", "OnStartAsync: start plugin-owned work; automatic jobs are registered afterwards, so OnStart success is not job-registration success", "OnConfigureMiddlewareAsync: attach middleware or map via IEndpointRouteBuilder.Map...; never call UseEndpoints and execute endpoints before host authorization", "OnStopAsync: stop accepting plugin work and drain; OnDisposeAsync: idempotently release remaining resources without relying on new requests"] },
      { id: "example", title: "A phase-correct plugin", code: { language: "csharp", value: pluginLifecycleCode }, note: "The example maps an endpoint without UseEndpoints, leaving authorization to the host's later UseAuthorization call." },
      { id: "observable-states", title: "Trust only states written by the primary path", paragraphs: ["PluginBase writes Unloaded, Initialized, Running, Stopped, and Unloaded again after successful Dispose. InitializeAsync writes Initialized before OnInitializeAsync; if that hook throws, the object can still say Initialized but is not added to PluginManager.LoadedPlugins. Start failure also leaves Initialized. Do not present Loading, Starting, Error, or other PluginState enum members as guaranteed observable 5.1.3 transitions, and never persist lifecycle state as business state."] },
      { id: "failure-domains", title: "Build failure and partial startup are different failure domains", bullets: ["Discovery, duplicate IDs, missing/cyclic dependencies, assembly loading, or ConfigureServices failure occurs before container build and prevents host construction", "Initialize failure logs Error and skips Initialize for every dependent while continuing independent plugins", "Start failure logs Error and skips dependent Start; those dependents were already initialized in the previous pass and remain in LoadedPlugins", "The host only logs `Plugin system ready (N running)`; it does not fail Build or RunAsync when fewer critical plugins run", "Critical plugins need business readiness/startup gates; process live, default ready, or a listening host cannot replace Running count and functional acceptance"] },
      { id: "middleware-after-failure", title: "Non-Running plugins can still attach to the Web pipeline", paragraphs: ["PluginManager.ConfigureMiddlewareAsync iterates LoadedPlugins without checking State. An Initialized plugin whose Start failed, and an Initialized dependent skipped after dependency Start failure, still receive ConfigureMiddlewareAsync and may map endpoints or middleware. A middleware-hook exception is synchronously surfaced and prevents host Build from returning.", "Handlers must check real plugin readiness instead of treating route existence as availability. A release must fail when a critical endpoint exists while its plugin is not Running."] },
      { id: "timeouts-cancellation", title: "Version 5.1.3 has no lifecycle timeout guard", paragraphs: ["Yggdrasil explicitly initializes plugins with default CancellationToken and synchronously waits for middleware configuration. LoadTimeoutSeconds is not wired into these primary-path calls. A non-returning Initialize, Start, job registration, or ConfigureMiddleware can block construction indefinitely. Apply explicit timeouts to external I/O, pass available cancellation tokens, and avoid untracked fire-and-forget tasks in lifecycle hooks."] },
      { id: "resources-compensation", title: "Resource acquisition needs compensation", bullets: ["When OnInitialize fails after state becomes Initialized, the manager never adds the instance to LoadedPlugins and the failure branch does not Stop/Dispose it; the hook must clean acquired resources in catch/finally", "If OnStart succeeds but automatic job registration fails midway, the plugin remains Initialized and OnStart resources are not automatically rolled back", "Acquire resources in reversible steps, publish readiness only after all succeed, and compensate in reverse order", "Do not retain a scoped service resolved from the root provider; create and dispose an explicit scope per operation"] },
      { id: "shutdown", title: "Stop, dispose, and tail-loss boundaries", bullets: ["AsgardRuntimeHostedService shuts down JobManager before disposing PluginManager; OnStop cannot expect the scheduler to accept or run jobs", "PluginManager unloads in dependency-aware order; a Running plugin gets Stop before Dispose", "Unload removes the plugin from its dictionary before Stop; an OnStop exception skips Dispose for that plugin, while manager disposal logs a warning and continues", "DisposeAsync receives no host-stop CancellationToken; hooks must still be bounded and idempotent and tolerate forced process termination", "Remove traffic before draining plugin queues/connections and document separate graceful versus forced-termination loss boundaries"] },
      { id: "reload-boundary", title: "Reload is not a production hot upgrade", paragraphs: ["Built-in plugins explicitly cannot Reload. External Reload unloads one target, reloads its descriptor, initializes a new instance, and puts it back in the dictionary. It does not call ConfigureServices, Start, automatic job registration, or ConfigureMiddleware, and it rebuilds neither root DI, MVC ApplicationParts, dependency topology, nor host pipeline. A returned instance is not proof of Running state or connected APIs. Use immutable process replacement for production upgrade and rollback."] },
      { id: "release-rollback", title: "Release and rollback gates", bullets: ["Pin plugin DLLs, dependencies, plugin.yaml, configuration, and digests in the release manifest; expected and Running plugin sets from startup evidence must match", "Give every critical plugin an owned ready check covering external dependencies, background loops, and required jobs; do not route traffic until it passes", "Canary plugin controllers, mapped endpoints, 401/403, tenant context, job/message side effects, and independent-plugin failure isolation", "On failure stop the new replicas and restore the previous complete host+plugin+config set; never replace a DLL in place or invoke Reload as repair", "After rollback repeat Running-set, endpoint, background-work, and graceful-stop acceptance to catch an old plugin reading a new configuration"] },
      { id: "acceptance", title: "Real-process acceptance matrix", bullets: ["Happy path: dependency order, one marker per stage, expected Running count, and critical readiness all match", "Fault injection: make ConfigureServices, Initialize, Start, automatic job registration, and ConfigureMiddleware throw or hang; record whether host builds, which dependents skip, and whether endpoints still appear", "Authorization: anonymous, unauthorized, and valid identities receive the intended 401/403/success on mapped endpoints and controllers; UseEndpoints never bypasses host authorization", "Shutdown: drain with in-flight requests, background loops, jobs, and external connections; prove unload order, final markers, and forced-kill boundary", "Multi-replica rollout: route only after critical readiness, then remove old traffic before stopping; halt rollout on any Running-set mismatch", "Rollback: after restoring the previous artifact/config, re-verify state, endpoints, unique jobs, and absence of duplicate consumption"], code: { language: "bash", value: pluginAcceptance } },
      { id: "ai-ready-sources", title: "AI Ready and source evidence", paragraphs: ["Agents maintaining this page must load asgard-plugin-lifecycle, asgard-host-project, and asgard-host-features; add asgard-job-scheduling for automatic jobs. Inspect PluginBase, PluginManager/PluginManager.Lifecycle, PluginServiceConfigurator, Yggdrasil PluginIntegration/Configurator, and AsgardRuntimeHostedService together. Never infer primary-path states, timeouts, failure rollback, or hot-upgrade guarantees from the complete PluginState enum or an older Skill state diagram."] },
    ],
  },
];

export const enHeimdallOperationsRunbooks: DocPage[] = [
  {
    slug: "heimdall-database-migrations", group: "Deployment & Operations", eyebrow: "HEIMDALL 5.3.19 · POSTGRESQL", title: "Database bootstrap, migrations, and rollback", description: "Manage empty databases, upgrades, and failure recovery using twelve released increments, CodeFirst, and real-database acceptance as separate evidence.", sections: [
      { id: "release-inventory", title: "Exact 5.3.19 released SQL inventory", paragraphs: ["Tag v5.3.19 / commit 0032070 contains twelve PostgreSQL increments: the original seven identity_webhook, mcp_credentials, object_storage, tenant_login_branding, tenant_oidc_cors, security_event_lifecycle, and sys_user_profile files, plus four 20260720_application_domain precheck/migrate/postcheck/cleanup stages and 20260720_mcp_credential_policy.", "The Application stages are ordered responsibilities, not interchangeable filenames: block duplicates/orphans/invalid states in precheck, build and backfill ApplicationId/relations in migrate, prove counts and constraints in postcheck, and run cleanup only after stable rollout and rollback-window closure. MCP policy expands platform/tenant credential extension columns to varchar(8192)."] },
      { id: "missing-migration-system", title: "Baseline, ledger, and down remain missing", paragraphs: ["Version 5.3.19 still has no complete empty-PostgreSQL baseline, built-in version/checksum/success ledger, or down scripts. Idempotent DDL does not prove safe replay of data migration, backfill, deduplication, and constraints in arbitrary states.", "Operators externally maintain starting version, reviewed order, SHA-256, executor, UTC time, transaction policy, and result. Schema-diff, precheck, and backup/PITR rehearsal precede an unknown-origin upgrade."] },
      { id: "auto-sync-boundary", title: "The real auto_sync_schema boundary", paragraphs: ["oidc.bootstrap.auto_sync_schema defaults false. When enabled, OidcPlugin calls FreeSql CodeFirst.SyncStructure for discovered entity types during OnStart. This is current-model structure synchronization, not a versioned migration engine; it emits no ledger, reviewed SQL, down path, or cross-version compatibility proof.", "Disabling it skips SyncStructure only. Startup then backfills tenant CORS, ensures PostgreSQL partial indexes, migrates runtime settings, and seeds the default administrator, all against expected tables. Empty database + false is not a released initialization path, and concurrent replicas starting with true have no proven schema leader/lock."], code: { language: "yaml", value: databaseProductionYaml } },
      { id: "empty-database-bootstrap", title: "Treat empty-database bootstrap as controlled acceptance", paragraphs: ["Use an immutable 5.3.19 image, one Heimdall instance, a dedicated empty PostgreSQL database, and explicit SyncStructure only as a controlled candidate. Export schema, run protocol acceptance, switch to false, and restart.", "PostgreSqlCompatibilityIntegrationTests remain focused real-database evidence, not a complete stock-host release baseline."], code: { language: "yaml", value: databaseBootstrapYaml } },
      { id: "upgrade-and-order", title: "Stage 5.1.2 → 5.3.19 from the real source database", paragraphs: ["Clone the real 5.1.2 production backup, verify the seven old increments, then run Application precheck → migrate → postcheck. Apply MCP policy before the 5.3.0+ application starts. Schedule cleanup separately after rollback closure.", "Run each file with psql -X -v ON_ERROR_STOP=1 and record its digest. Measure locks, WAL, backfill, and failure replay on production-scale data before production."], code: { language: "bash", value: migrationCommand } },
      { id: "expand-contract", title: "Expand → deploy → contract", bullets: ["Expand: precheck duplicates/orphans; build Application structures and backfill ApplicationId for soft-deleted/history OIDC Clients too", "Deploy: run 5.3.19 backend and matching Web, observing sign-in, issuance, Manifest, Grants, tenant RBAC, and MCP", "Contract: run cleanup only after postcheck and rollback closure; with no down SQL, rollback depends on backup/PITR and a compatible image", "Prove locks, elapsed time, replication lag, and replay boundaries for large UPDATE/index work"] },
      { id: "backup-pitr-and-recovery", title: "Backup, PITR, and failure recovery", paragraphs: ["Before migration, keep a consistent full backup, schema dump, configuration/secret references, image digest, and script digest. Confirm PostgreSQL WAL archive and a usable PITR restore point, then perform an isolated restore drill; a successful backup command is not recovery evidence.", "On failure, stop later scripts and new-version replicas and retain psql error, transaction state, and schema diff. If rolled back, fix and retry from the verified state. If DDL/data changes committed, never invent reverse SQL: choose reviewed forward repair/compensation or restore backup/PITR, then run an application image compatible with that database state."] },
      { id: "multi-instance-startup", title: "Multi-instance startup gate", paragraphs: ["Schema change is a separate pre-deploy stage with management writes stopped and one migration runner. Never start multiple 5.3.19 replicas with auto_sync_schema=true; startup backfills, indexes, RBAC sync, runtime settings, and seed are not a cluster migrator.", "After migration/postcheck, roll out auto_sync_schema=false replicas. Gate each on database, Discovery/JWKS, system/tenant login, Application Client, and MCP smoke before traffic."] },
      { id: "schema-and-application-acceptance", title: "Accept empty and upgraded databases separately", code: { language: "sql", value: migrationVerificationSql }, bullets: ["Empty: bootstrap a new database under control, restart with false, and compare exported schema to a reviewed snapshot rather than counting tables", "Upgrade: rehearse from every supported real source-version backup and verify tables, columns, indexes, backfills, and duplicate-data boundaries touched by all seven increments", "Check critical type/nullability/default, partial unique-index predicates, primary/tenant_id, runtime settings/history, and retain queries/results", "Smoke root/tenant Discovery/JWKS, Authorization Code + S256 PKCE, Refresh, UserInfo, logout, management APIs, and affected MCP/webhook/security-event paths", "Repeated auto_sync_schema=false starts make no additional schema change; multi-replica writes and rollback image both pass", "On a production-scale clone record DDL locks, elapsed time, WAL, replica lag, CPU/IO, and disk growth"] },
      { id: "release-boundaries", title: "Release and unproven boundaries", paragraphs: ["Release: v5.3.19 / 0032070 proves the twelve increments, staged Application scripts and SQL contract tests, and default-false auto_sync_schema. HEAD equals the tag and the worktree is clean.", "Unproven/unshipped: complete baseline, universal historical-version order matrix, built-in ledger/checksum, down scripts, complete stock-host empty-database acceptance, multi-instance schema leader, automatic rollback, or repository-managed PITR."] },
    ],
  },
  {
    slug: "heimdall-reverse-proxy", group: "Deployment & Operations", eyebrow: "HEIMDALL 5.3.19 · TLS BOUNDARY", title: "Reverse proxy, TLS, and secure cookies", description: "Accept public issuer, trusted scheme, root-path routing, request transport, and real-browser cookies as separate production boundaries.", sections: [
      { id: "issuer-versus-scheme", title: "Issuer and Request.Scheme are separate facts", paragraphs: ["Set the HTTPS authority browsers actually reach. Tenant issuers append /{tenantId}. OidcAuthorityService derives authority from Request.Scheme, Host, and PathBase only when oidc.issuer is empty. A fixed HTTPS issuer changes Discovery, token iss, and generated protocol URLs but does not rewrite an internally HTTP Request.Scheme.", "A correct Discovery issuer therefore does not prove cookie safety. When TLS terminates at a proxy, a trusted host layer must restore the real scheme/host before cookie and authentication handling and reject forwarded headers from untrusted sources. Accept these two facts separately."], code: { language: "yaml", value: reverseProxyIssuerYaml } },
      { id: "stock-forwarded-header-gap", title: "Stock 5.3.19 Forwarded Headers gap", paragraphs: ["Heimdall 5.3.19 tag v5.3.19 / commit 0032070 and the Asgard 5.1.3 stock host expose no verified UseForwardedHeaders, ForwardedHeadersOptions, KnownProxies, or KnownNetworks configuration surface. Nginx sending X-Forwarded-Proto/Host/For is input only: it proves neither consumption nor that the application trusts only that proxy.", "Production must either customize the host to register and constrain Forwarded Headers before all cookie/authentication/redirect logic, or use a platform with verified equivalent Request.Scheme/Host restoration. Otherwise treat the stock host as proxy-unaware and never base a security decision on forwarded values."] },
      { id: "tls-and-network-boundary", title: "TLS termination and network isolation", bullets: ["Require TLS 1.2+ with a valid full certificate chain at the sole client entry; redirect HTTP under a controlled policy or close it", "Use an isolated container/private network from proxy to Kestrel; add and verify upstream TLS/mTLS when the threat model requires end-to-end encryption", "Never publish Kestrel port 5000 to the internet or an untrusted LAN; firewall/security-group/container policy permits only proxy and operations probes", "Overwrite rather than append client Forwarded/X-Forwarded-* values; constrain Host and reject unknown Host/SNI", "HSTS, certificate renewal, OCSP/chain changes, and proxy clock synchronization are entry-point operations, not features of oidc.issuer"] },
      { id: "root-path-and-pathbase", title: "Path Base and rewrite boundary", paragraphs: ["Request-derived OidcAuthorityService includes Request.PathBase, but stock startup has no proven UsePathBase or X-Forwarded-Prefix consumption contract. Hosted login/consent assets and some frontend calls also use root paths. The released 5.3.19 guidance is a dedicated domain root such as https://id.example.com, not /heimdall.", "Do not merely strip/add a proxy prefix and put that path in oidc.issuer. A required subpath needs a custom host/static assets plus verification of Discovery, JWKS, authorize/token/userinfo/introspect/revoke/end-session, login/consent callbacks, APIs, MCP, and every Location/form/script URL. Until that evidence exists, label subpath deployment unsupported."] },
      { id: "proxy-request-contract", title: "Headers, bodies, streams, and timeouts", paragraphs: ["Preserve Host, method, query, Content-Type, Authorization, Cookie, Set-Cookie, Location, and response status. Never log Authorization, cookies, codes, tokens, passwords, MFA material, or SAML Responses. Token/consent uses forms, management APIs use JSON, SAML callback uses POST, and branding/Passkey endpoints have their own body limits; one undersized global body limit surfaces as misleading 413 protocol failures.", "The timeout values below are an operator-reviewed starting point, not Heimdall defaults. Accept them across Authorization Code, LDAP/SAML return, uploads, webhook administration, and failure injection. Proxy retries must not replay non-idempotent POST automatically. /mcp is Streamable HTTP and needs response buffering disabled. Version 5.3.19 has no released protocol endpoint requiring WebSocket Upgrade; never set Connection: upgrade site-wide. Add a dedicated route and acceptance only when a WebSocket capability ships."], code: { language: "nginx", value: nginxProxyCode } },
      { id: "secure-cookie-contract", title: "Asgard.Identity cookie contract", paragraphs: ["The Heimdall login cookie is Asgard.Identity with HttpOnly=true, SameSite=Lax, 30-minute sliding expiry, and SecurePolicy=SameAsRequest. A fixed HTTPS issuer does not add Secure when the application sees an internal HTTP request; SameAsRequest produces Secure only when Request.Scheme has been restored to trusted HTTPS.", "Do not mechanically append another Set-Cookie or rewrite Secure at the proxy to hide a wrong scheme: redirects, external-login callbacks, and other absolute URLs may still be wrong. Restore the trusted scheme at its source and inspect both the network response and browser cookie store."] },
      { id: "multi-tenant-route-matrix", title: "Multi-tenant protocol route matrix", bullets: ["Platform: /.well-known/openid-configuration, /.well-known/jwks, and /connect/authorize|token|userinfo|introspect|revoke|end-session", "Tenant: /{tenantId}/.well-known/openid-configuration, /{tenantId}/.well-known/jwks, and /{tenantId}/connect/*; the proxy never normalizes, decodes into a different value, or drops tenantId", "Interaction and return: /login.html, /consent.html, /logout-complete.html, /external-login/*, and /external-logout/*; preserve the full local returnUrl/query", "Management/API: /api/*, /scim/v2/{tenantId}, /mcp, and health according to their own authentication, body, buffering, and exposure policies", "Platform clients never use tenant endpoints and tenant clients never use root endpoints; a wrong route fails instead of entering a proxy fallback/SPA rewrite"] },
      { id: "browser-and-protocol-acceptance", title: "Real-browser and protocol acceptance", bullets: ["Root plus one tenant Discovery exposes the expected public HTTPS issuer, jwks_uri, authorization_endpoint, token_endpoint, userinfo_endpoint, introspection_endpoint, revocation_endpoint, and end_session_endpoint with correct paths", "In a real browser complete platform and tenant Authorization Code + S256 PKCE, sign-in/MFA, consent, UserInfo, Refresh, and End Session; callbacks and post_logout_redirect_uri exactly match registration", "In the login response and cookie store verify Asgard.Identity is Secure, HttpOnly, SameSite=Lax with the intended Domain/Path; an internal HTTP hop never removes Secure", "Wrong Host, forged X-Forwarded-Proto/Host/For, direct :5000, wrong tenant, double-slash/encoded paths, oversized bodies, slow requests, and upstream timeout all fail under policy", "Verify /mcp streams without buffering, ordinary routes do not perform unjustified WebSocket Upgrade, and 413/408/502/504 remain distinguishable from application 400/401/403"] },
      { id: "rollout-observability-and-rollback", title: "Rollout, observability, and rollback", bullets: ["Validate certificate, DNS, Host allowlist, Discovery, and browser cookie on a canary hostname before shifting production DNS/LB; retain the old proxy config and upstream for immediate return", "nginx -t or equivalent validation, reload, HTTP smoke, and browser acceptance form one gate. Current deploy.sh neither manages nor rolls back Nginx", "Monitor TLS handshake, 4xx/413/429, 502/504, upstream latency, login/callback/logout failures, wrong issuer, unknown kid, repeated-login cookie symptoms, and tenant-route errors", "On proxy failure, restore entry configuration and traffic first; do not regenerate signing/encryption keys or turn a transport incident into key rotation", "After rollback repeat Discovery, PKCE, cookie, and logout acceptance. Retain redacted request id, Host, path, status, and upstream timing—never secrets/tokens/cookies"] },
      { id: "release-boundaries", title: "Release, HEAD, and unproven boundaries", paragraphs: ["Release: 5.1.2 introduced the core explicit/request-derived authority, platform and tenant Discovery/JWKS/protocol routes, Asgard.Identity SameAsRequest cookie, sign-in/consent/callback/logout logic, and tenant-route tests. Current clean v5.3.19 / 0032070 preserves those contracts and includes friendly logout-error rendering, login.html UTC localization, and the expired RP logout-hint validation fix. HEAD equals the tag and still adds no forwarded-header or proxy configuration.", "Unproven/unshipped: stock UseForwardedHeaders, KnownProxies/KnownNetworks configuration, trusted X-Forwarded-Prefix/UsePathBase subpath deployment, automatic Secure-cookie repair, Nginx management/rollback, proxy body/timeout defaults, WebSocket endpoints, or end-to-end mTLS. The Nginx example and rollout are operator policy that require real target-platform acceptance, not a Heimdall control plane."] },
    ],
  },
  {
    slug: "heimdall-client-credentials", group: "Application Integration", eyebrow: "HEIMDALL 5.3.19 · MACHINE IDENTITY", title: "Client Credentials and backend-service identity", description: "Register, issue, rotate, and revoke tenant BackendService identities that Asgard resource APIs can safely accept.", sections: [
      { id: "registration-contract", title: "Registration contract", bullets: ["clientType=confidential; public clients cannot use client_credentials", "applicationType is not native and grantTypes contains client_credentials", "client_secret is required; tokenEndpointAuthMethods lists only actually used client_secret_basic and/or client_secret_post, never none", "Allowed scopes include every requested scope; omit human-only openid/profile grants from machine clients", "accessTokenFormat is jwt for stock Asgard APIs; opaque tokens need an external introspection design", "Tenant clients use /{tenantId}/connect/token and a /{tenantId} issuer; never send a platform-root token to Asgard 5.1.3 host.auth"] },
      { id: "secret-authentication", title: "Secret and token-endpoint authentication", paragraphs: ["Prefer client_secret_basic. Use client_secret_post only when registered and request bodies cannot enter access logs/Trace. Conflicting Basic/body credentials, mismatched client IDs, an unregistered method, or bad secret fail authentication.", "Secrets belong only in confidential backends—never browsers, mobile apps, URLs, repositories, images, logs, traces, prompts, or telemetry. Inject through secret management with constrained readers; give each workload its own client instead of sharing one universal secret."], code: { language: "bash", value: `${clientCredentialsBasic}\n\n# Only when client_secret_post is explicitly registered\n${clientCredentialsPost}` } },
      { id: "scope-resource-audience", title: "Scope → Resources → audience", paragraphs: ["Heimdall validates requested scopes against client permissions, then resolves Resources from those custom tenant scopes. Non-empty Resources become access-token aud values; otherwise it falls back to client_id. IdentityAuthorizationAudienceTests prove built-in-scope fallback and custom-resource audience separately.", "Production APIs should avoid fallback: create an API-specific scope whose Resources is the resource server's single configured audience, allow it, and actually request it. Allowed-but-unrequested scope is not inserted automatically. Multiple scopes can produce multiple aud values; Asgard 5.1.3 single-value audience requires one exact match."] },
      { id: "token-and-claims", title: "Token issuance and claims", bullets: ["Every successful exchange creates a client_credentials authorization record and access token; includeRefreshToken=false means no refresh token", "sub and client_id identify the calling client; token_type=BackendService", "Tenant clients carry tenant_id; roles and permissions are empty arrays and do not represent user authority", "scope contains approved values and tenantMetadata may be restored; there is no user_id or user-session meaning", "expires_in bounds token caching; refresh early with jitter and single-flight, not a concurrent exchange storm"] },
      { id: "asgard-resource-server", title: "Asgard 5.1.3 resource-server contract", paragraphs: ["host.auth.jwt.issuerTemplate contains exactly one {tenant} and extracts tenant from iss. host.auth.jwt.audience is one global value that must exactly equal one token aud. The API validates JWT signature, tenant issuer, audience, and lifetime through tenant Discovery/JWKS.", "After authentication, authorize with token_type=BackendService plus scope, for example AsgardAuthMatch; do not rely on empty roles/permissions. Stock host.auth supports neither opaque tokens, platform-root issuer, simultaneous platform/tenant issuers, nor per-request introspection; each needs a separate authentication design."] },
      { id: "secret-rotation", title: "Dual-secret rotation", paragraphs: ["Secret reset generates 16 random bytes rendered as hex and returns plaintext once; the database stores a password hash. gracePeriodMinutes is 0–1440 (default 60). Above zero, the previous hash remains accepted until PreviousClientSecretExpiresAt alongside the new secret.", "Write the new secret to consumer secret management, refresh every instance, and prove new-secret exchange before waiting for old usage to reach zero. Expiry stops old-secret validation but does not automatically clear the old hash columns. Use grace=0 for confirmed compromise and keep routine grace within risk tolerance."] },
      { id: "revocation-boundaries", title: "Revocation and propagation boundaries", paragraphs: ["Secret rotation affects future exchange only; it does not revoke issued access tokens. Client disable/delete management paths mark that client's protocol access/refresh tokens and authorizations revoked. Client Credentials itself issues no refresh token.", "External Asgard JWKS validation does not query Heimdall revocation per request, so issued JWTs usually remain valid until exp unless the resource adds deny-list/invalidation or a verified online design. Heimdall introspection returns active only for an access token owned by the same client and tenant; it is not general resource-server RFC 7662."] },
      { id: "operations-and-observability", title: "Operations and observability", bullets: ["Measure exchange by client_id, tenant, scope, audience, result, latency, and error class; never record Authorization, client_secret, or access token", "Separate invalid_client, unauthorized_client, invalid_scope, 429, 5xx, and timeout; stop-alert configuration/credential failures and jitter transient retry", "Cache token in-process by expires_in with single-flight refresh; never call /connect/token for every API request", "Track owner, purpose, allowed scopes, target audience, rotation schedule, last use, and revoke runbook per workload", "On anomalous client use, disable/delete or emergency-rotate first, then evaluate remaining JWT TTL and resource isolation"] },
      { id: "production-acceptance", title: "Real production acceptance", bullets: ["Basic exchange succeeds; post fails when unregistered; wrong/expired old secret, public/native client, and disallowed grant fail", "Disallowed/unrequested scopes fail or stay absent; API scope Resources yields expected aud, with client_id fallback accepted only in explicit tests", "Inspect claims without trusting them, then make Asgard API validate tenant issuer, JWKS, audience, exp, tenant_id, BackendService, and scope", "Wrong audience, platform issuer, opaque token, user policy, and cross-tenant route are rejected", "New/old secret work only for the planned grace window; after expiry old fails and multiple consumers cause no exchange storm", "After disable/delete exchange fails; incident plan accepts the documented offline JWT residual lifetime"] },
      { id: "release-boundaries", title: "Release, HEAD, and unproven boundaries", paragraphs: ["Release: 5.1.2 introduced the core confidential/client_credentials registration validation, Basic/Post reader and validator, current/previous hash verification, Scope/Resources audiences, BackendService claims, no refresh token, authorization creation, client-state revocation, and reader/auth/audience/application tests. Current clean v5.3.19 / 0032070 preserves those behaviors, and HEAD equals the tag.", "Unproven/unshipped: private_key_jwt, mTLS client authentication, automatic secret-manager distribution, unlimited previous-secret overlap, per-API dynamic multi-audience configuration, stock Asgard opaque introspection, general RFC 7662 resource-server introspection, immediate JWT revocation at external APIs, or complete production multi-replica acceptance."] },
    ],
  },
  {
    slug: "heimdall-tenant-signing-key-rotation", group: "Deployment & Operations", eyebrow: "HEIMDALL 5.3.19 · TRUST TRANSITION", title: "Tenant signing-key rotation", description: "Rotate tenant RSA keys against the released state, cache, and storage contracts while accepting multi-replica concurrency and disaster replacement separately.", sections: [
      { id: "system-versus-tenant", title: "Separate the system key from tenant keys", paragraphs: ["The system signing key comes from oidc.signing.rsa_private_key and serves the platform issuer, default clients, and root JWKS; it does not enter the tenant_oidc_key state machine. Tenant keys live in tenant_oidc_key, with private material encrypted through EncryptionService, and sign for /{tenantId} issuers. Rotating one does not rotate the other.", "Root /.well-known/jwks contains the system key plus current validation keys from all tenants. /{tenantId}/.well-known/jwks contains only that tenant's Active/Retiring validation keys. Resource servers must use the JWKS matching their Authority; root JWKS is not a tenant-minimal trust set."] },
      { id: "state-machine", title: "Released state machine and time semantics", bullets: ["Generate/Create makes Draft; Draft neither signs, validates, nor enters JWKS", "Activate accepts Draft only and writes Active, ActivateAt=request, RetireAt=null; a future ActivateAt renders as pending_activation at runtime", "When an old Active is found at the requested instant, the same database transaction changes it to Retiring with RetireAt=ActivateAt+retentionDays", "Active signs only when ActivateAt<=UTC now and RetireAt has not passed; Active/Retiring inside that window validate and enter JWKS", "CompleteRetirementAsync accepts only Retiring with RetireAt<=UTC now, then writes Retired; time passing alone does not perform that state transition"] },
      { id: "generate-and-activate", title: "Generate, prepublish, and activate", paragraphs: ["Management requires platform.admin or platform.oidc_key.manage, with TenantResourceAccessGuard still constraining tenant-level authority. Use server-side generate and never copy private material into response logs, screenshots, documentation, or tickets. RSA minimum is 2048; automation accepts 2048, 3072, or 4096.", "retentionDays must cover maximum token TTL, verifier JWKS TTL, Heimdall's five-minute internal cache, propagation, and clock skew; it must be positive when an old Active exists. Create a Draft and record its kid before activating in a controlled window."], code: { language: "bash", value: `${keyGenerateCode}\n\n${keyActivateCode}` } },
      { id: "transaction-and-concurrency", title: "A transaction is not multi-replica serialization", paragraphs: ["ActivateAsync uses a FreeSql UnitOfWork: check Draft, query current Active, update the new key, read it back, then mark the old key Retiring. Failure rolls back the database transaction and writes activate_failed audit, but end-to-end evidence does not prove audit atomicity, isolation level, or cross-instance exclusion.", "Version 5.3.19 has no distributed lock verified for key rotation and no proven database constraint enforcing one Active per tenant. The at-most-five PostgreSQL 23505/uk_tenant_oidc_key_tenant_kid retries solve Kid creation conflicts only; they do not serialize two Activate calls or multi-node jobs. Assign one rotation leader and prohibit concurrent manual changes."] },
      { id: "cache-and-propagation", title: "Cache refresh is not an instant broadcast", paragraphs: ["TenantSecurityKeyProvider separately caches signing keysets, validation keysets, per-kid validation keys, and JWKS for five minutes. Repository writes clear repository entity/list caches, but 5.3.19 key-mutation paths do not explicitly remove those provider cache keys or publish cross-node invalidation.", "Replicas can therefore sign from old snapshots or expose different JWKS during the window. Confirm the new kid on every replica's tenant JWKS before observing which kid each replica signs with. After final retirement, wait both Heimdall's internal window and external verifier JWKS TTL before declaring the old kid gone."] },
      { id: "retirement-and-failure-recovery", title: "RetireAt, final retirement, and failure recovery", bullets: ["Keep the old key through RetireAt so already-issued tokens remain verifiable; do not shorten it merely to clean the UI", "RetireAt excludes a key from time-window queries but does not write Retired; then call /complete-retirement or let an enabled job do so", "CompleteRetirementAsync has no dedicated explicit UnitOfWork/read-back test or provider-cache clearing; on failure retain Retiring, investigate database/audit, and retry through the service rather than editing tables", "If new-key signing or validation fails, stop further rotations and retirement; use the still-retained old trust path while repairing the new key", "If two effective Active rows, a wrong RetireAt, or replica kid disagreement appears, isolate the leader, preserve audit/database snapshots, and arbitrate manually; stock 5.3.19 has no automatic reconciler"] },
      { id: "automation", title: "Automation contract and namespace split", paragraphs: ["RotateTenantOidcKeysJob is scheduled every six hours by default, while oidc.key_rotation.enabled controls execution. It loops tenants, generates/activates, and completes expired Retiring keys, with no verified cluster-wide DisallowConcurrentExecution or distributed lock. Run it on one node unless the platform supplies independently accepted singleton scheduling.", "The job reads oidc.key_rotation.enabled, retention_days, interval_days, and rsa_key_size, while typed configuration remains oidc.tenant_key_rotation.*. These namespaces are not unified; changing only the typed node does not prove the runtime override took effect."] },
      { id: "backup-and-disaster-replacement", title: "Backup and disaster key replacement", paragraphs: ["A recoverable backup needs tenant_oidc_key ciphertext plus status/ActivateAt/RetireAt in a consistent database snapshot and the Asgard Encryption Key that decrypts it. Back up system oidc.signing.rsa_private_key separately. Restoring the database without the encryption master key does not restore usable tenant signing keys.", "Prefer restoring original system/tenant keys to preserve token trust. Confirmed compromise or permanent key loss makes replacement disruptive: generate a new key for the affected trust domain, publish JWKS, switch signing, and decide whether risk requires immediate old-key termination; existing tokens can fail immediately. Replace system and tenant keys separately and notify their respective resource servers."] },
      { id: "multi-replica-acceptance", title: "Real multi-replica acceptance gate", bullets: ["Use at least two Heimdall replicas with production-equivalent shared database/cache; query each replica's tenant JWKS directly or with an observable replica marker", "Capture system/root and target-tenant JWKS before rotation; during rotation issue through every replica and record kid, issuer, and UTC time without recording token bodies", "Accept new signing only after every tenant JWKS exposes the new kid; before RetireAt, old tokens validate through every replica and external resource API", "Inject one replica restart, corrupt/cache miss, transient database failure, and overlapping-job attempt; prove source fallback or explicit failure without creating a second Active", "After retirement and both cache TTLs, every replica/verifier rejects the old kid; root JWKS retains system key and other tenant JWKS remain unchanged", "Retain redacted evidence: commit, configuration, node, UTC time, kid, state, JWKS hash, validation result, and rollback decision"] },
      { id: "release-boundaries", title: "Release, HEAD, and unproven boundaries", paragraphs: ["Release: 5.1.2 introduced the Draft/Active/Retiring/Retired model, transactional Activate read-back, RetireAt query windows, five-minute serializable provider cache, system/tenant JWKS split, tenant route guard, Kid conflict retry, and the corresponding unit/integration tests. Current clean v5.3.19 / 0032070 preserves those contracts; HEAD equals the tag and adds no key-rotation concurrency or cache-consistency guarantee.", "Unproven/unshipped: one-Active-per-tenant database constraint, cross-instance lock/leader election, proactive provider-cache invalidation, cluster job deduplication, atomic CompleteRetirement read-back, end-to-end multi-replica rotation, backup restore drill, HSM/KMS custody, or automatic compromise revocation broadcast. Do not call this a zero-downtime guarantee until those target-platform acceptances pass."] },
    ],
  },
];
