export const skillReferencesBySlug: Record<string, string[]> = {
  overview: ["asgard-framework-overview"],
  "quick-start": ["asgard-host-project", "asgard-plugin-development", "asgard-dotnet-10-csharp-14"],
  "packages-and-installation": ["asgard-framework-overview", "asgard-host-project"],
  "upgrade-to-5-1": ["asgard-framework-overview", "asgard-identity-userinfo", "asgard-admin-frontend", "asgard-host-features"],
  "host-and-plugins": ["asgard-host-project", "asgard-plugin-development", "asgard-plugin-lifecycle"],
  "host-lifecycle": ["asgard-host-project", "asgard-framework-overview", "asgard-configuration"],
  "middleware-pipeline": ["asgard-host-features", "asgard-plugin-lifecycle", "asgard-auth-authorization"],
  "health-and-rate-limiting": ["asgard-host-features", "asgard-host-project", "asgard-configuration", "asgard-context-usage"],
  "plugin-lifecycle": ["asgard-plugin-lifecycle", "asgard-plugin-development", "asgard-host-project", "asgard-host-features", "asgard-job-scheduling", "asgard-dotnet-10-csharp-14"],
  deployment: ["asgard-host-project", "asgard-host-features", "asgard-configuration", "asgard-security"],
  "external-plugin-operations": ["asgard-plugin-lifecycle", "asgard-plugin-development", "asgard-host-project", "asgard-configuration"],
  "kestrel-tls-operations": ["asgard-host-features", "asgard-host-project", "asgard-configuration", "asgard-security"],
  "dependency-registration": ["asgard-repository-service-registration", "asgard-plugin-development", "asgard-plugin-lifecycle", "asgard-database", "asgard-backend-guard", "asgard-dotnet-10-csharp-14"],
  "static-files": ["asgard-host-features", "asgard-host-project", "asgard-security"],
  "swagger-openapi": ["asgard-host-features", "asgard-host-project", "asgard-api-development"],
  "api-development": ["asgard-api-development", "asgard-dotnet-10-csharp-14", "asgard-backend-guard"],
  "api-contracts-and-errors": ["asgard-api-development", "asgard-host-features", "asgard-backend-guard"],
  "crud-vertical-slice": ["asgard-api-development", "asgard-database", "asgard-repository-service-registration", "asgard-backend-guard"],
  "tenant-background-work": ["asgard-context-usage", "asgard-identity-userinfo", "asgard-database", "asgard-job-scheduling"],
  infrastructure: ["asgard-context-usage", "asgard-framework-overview"],
  "context-usage": ["asgard-context-usage", "asgard-framework-overview"],
  configuration: ["asgard-configuration", "asgard-host-features"],
  "configuration-reference": ["asgard-configuration", "asgard-host-features", "asgard-security"],
  "configuration-fields": ["asgard-configuration", "asgard-host-features", "asgard-security"],
  "infrastructure-configuration-fields": ["asgard-configuration", "asgard-database", "asgard-cache", "asgard-messaging", "asgard-job-scheduling", "asgard-tracing-observability"],
  "host-configuration-fields": ["asgard-configuration", "asgard-host-features", "asgard-plugin-development", "asgard-plugin-lifecycle"],
  database: ["asgard-database", "asgard-repository-service-registration", "asgard-backend-guard"],
  "database-operations": ["asgard-database", "asgard-repository-service-registration", "asgard-dotnet-10-csharp-14", "asgard-backend-guard"],
  caching: ["asgard-cache", "asgard-context-usage"],
  "cache-operations": ["asgard-cache", "asgard-context-usage", "asgard-database"],
  "distributed-lock-operations": ["asgard-context-usage", "asgard-cache", "asgard-dotnet-10-csharp-14", "asgard-backend-guard"],
  "cors-operations": ["asgard-host-features", "identity-integration", "asgard-dotnet-10-csharp-14"],
  messaging: ["asgard-messaging", "asgard-context-usage"],
  "messaging-operations": ["asgard-messaging", "asgard-context-usage", "asgard-tracing-observability"],
  "job-scheduling": ["asgard-job-scheduling", "asgard-plugin-lifecycle"],
  "job-operations": ["asgard-job-scheduling", "asgard-dotnet-10-csharp-14", "asgard-plugin-lifecycle"],
  "resource-api-authentication": ["identity-integration", "asgard-host-features", "asgard-auth-authorization"],
  "identity-and-tenancy": ["asgard-identity-userinfo", "identity-integration"],
  authorization: ["asgard-auth-authorization", "asgard-identity-userinfo"],
  "identity-authorization-operations": ["asgard-identity-userinfo", "asgard-auth-authorization", "asgard-context-usage", "identity-integration", "asgard-backend-guard"],
  security: ["asgard-security", "asgard-dotnet-10-csharp-14"],
  "security-operations": ["asgard-security", "asgard-configuration", "asgard-context-usage", "asgard-dotnet-10-csharp-14"],
  observability: ["asgard-tracing-observability", "asgard-context-usage"],
  "observability-operations": ["asgard-tracing-observability", "asgard-context-usage", "asgard-api-development"],
  "logging-operations": ["asgard-tracing-observability", "asgard-configuration", "asgard-host-project"],
  "typescript-generation": ["asgard-admin-frontend", "asgard-host-features"],
  "tsgen-operations": ["asgard-admin-frontend", "asgard-host-features", "asgard-api-development", "asgard-dotnet-10-csharp-14"],
  analyzers: ["asgard-dotnet-10-csharp-14", "asgard-backend-guard"],
  "analyzers-operations": ["asgard-dotnet-10-csharp-14", "asgard-backend-guard"],
  heimdall: ["identity-integration", "asgard-framework-overview"],
  "heimdall-quick-start": ["identity-integration", "asgard-configuration", "asgard-host-features", "asgard-security"],
  "heimdall-release-notes": ["heimdall-application-rbac", "heimdall-mcp-management", "heimdall-service-integration", "identity-integration", "asgard-security"],
  "heimdall-integration": ["identity-integration", "asgard-host-features", "asgard-auth-authorization"],
  "heimdall-application-rbac": ["heimdall-application-rbac", "asgard-identity-userinfo", "identity-integration", "asgard-api-development", "asgard-auth-authorization", "asgard-backend-guard"],
  "heimdall-service-integration": ["heimdall-service-integration", "heimdall-application-rbac", "identity-integration", "asgard-auth-authorization"],
  "heimdall-custom-frontend": ["identity-integration", "asgard-security", "asgard-auth-authorization"],
  "heimdall-deployment": ["identity-integration", "asgard-configuration", "asgard-security"],
  "heimdall-disaster-recovery": ["identity-integration", "asgard-database", "asgard-configuration", "asgard-security", "asgard-cache", "asgard-messaging"],
  "heimdall-database-migrations": ["asgard-database", "asgard-configuration", "asgard-security", "identity-integration"],
  "heimdall-reverse-proxy": ["identity-integration", "asgard-host-features", "asgard-security", "asgard-configuration"],
  "heimdall-client-credentials": ["identity-integration", "asgard-auth-authorization", "asgard-host-features", "asgard-security"],
  "heimdall-device-authorization": ["identity-integration", "asgard-security", "asgard-host-features"],
  "heimdall-token-lifecycle": ["identity-integration", "asgard-host-features", "asgard-auth-authorization"],
  "heimdall-resource-server-revocation": ["identity-integration", "asgard-host-features", "asgard-auth-authorization", "heimdall-service-integration"],
  "heimdall-account-security-sessions": ["identity-integration", "asgard-security", "asgard-auth-authorization"],
  "heimdall-tenant-onboarding-api": ["identity-integration", "asgard-security", "asgard-api-development"],
  "heimdall-management-api": ["heimdall-application-rbac", "identity-integration", "asgard-api-development", "asgard-auth-authorization"],
  "heimdall-tenant-signing-key-rotation": ["identity-integration", "asgard-security", "asgard-job-scheduling", "asgard-cache", "asgard-database"],
  "heimdall-jwt-signing": ["asgard-mini-jwt-issuer", "asgard-host-features", "identity-integration", "asgard-security"],
  "heimdall-mcp": ["heimdall-mcp-management", "identity-integration", "asgard-auth-authorization", "asgard-security", "asgard-backend-guard"],
  "heimdall-identity-webhooks": ["identity-integration", "asgard-tracing-observability", "asgard-security"],
  "heimdall-federation-mfa": ["identity-integration", "asgard-security", "asgard-cache", "asgard-auth-authorization"],
  "heimdall-scim": ["identity-integration", "asgard-security"],
  "heimdall-scim-operations": ["identity-integration", "asgard-security", "asgard-api-development"],
  "heimdall-siem": ["asgard-tracing-observability", "asgard-security", "asgard-database", "identity-integration"],
  "skills-ecosystem-onboarding": ["asgard-framework-overview"],
};

export function getSkillReferences(slug: string) {
  return skillReferencesBySlug[slug] ?? [];
}
